# Generated by Django 4.2.20 on 2025-04-22 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfactionToolFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='The URL of the page from which the feedback originates.', max_length=255)),
                ('was_useful', models.BooleanField(help_text='Is this page useful?')),
                ('did_not_find_what_i_wanted', models.BooleanField(blank=True, help_text='I did not find what I was looking for.', null=True)),
                ('difficult_navigation', models.BooleanField(blank=True, help_text='I found it difficult to navigate the page.', null=True)),
                ('lacks_feature', models.BooleanField(blank=True, help_text='The page lacks a feature I need.', null=True)),
                ('unable_to_load', models.BooleanField(blank=True, help_text='I was unable to load/refresh/enter the page.', null=True)),
                ('inaccurate_information', models.BooleanField(blank=True, help_text='I did not find the information accurate.', null=True)),
                ('other_issues', models.BooleanField(blank=True, help_text='Something else went wrong.', null=True)),
                ('other_issues_detail', models.TextField(blank=True, help_text='Something else went wrong and this is the detail.', null='')),
                ('improvement_suggestion', models.TextField(blank=True, help_text='Feedback on how to improve the service provided on the page.', null='')),
            ],
            options={
                'verbose_name': 'H-CSAT Result',
                'verbose_name_plural': 'H-CSAT Results',
                'ordering': ('-created_on',),
            },
        ),
    ]
