# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSubscriber',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='order.Order')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ordersubscriber',
            unique_together=set([('order', 'adviser')]),
        ),
        migrations.AlterModelOptions(
            name='ordersubscriber',
            options={'ordering': ['created_on']},
        ),
    ]
