# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_squashed_0030_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
