# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170719_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersubscriber',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
