# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_team_roles_regions_countries'),
        ('order', '0003_auto_20170721_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.Sector'),
        ),
    ]
