# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_add_default_id_for_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
