# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 10:23
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations
from django.utils.timezone import utc


def update_uk_regions(apps, schema_editor):
    Order = apps.get_model('order', 'Order')

    release_date = datetime(2017, 11, 23, tzinfo=utc)
    orders_after_release = Order.objects.filter(
        created_on__gt=release_date
    ).select_related('company')

    for order in orders_after_release:
        order.uk_region = order.company.uk_region
        order.save(update_fields=('uk_region',))  # so that modified_on doesn't change


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_uk_region'),
    ]

    operations = [
        migrations.RunPython(update_uk_regions, migrations.RunPython.noop, elidable=True),
    ]
