# Generated by Django 2.0.3 on 2018-03-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_populate_uk_region'),
    ]

    operations = [
    ]
