# Generated by Django 2.0.8 on 2018-08-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_add_sector_hierarchy'),
        ('core', '0003_rename_read_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
