# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_added_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='orders', to='order.ServiceType'),
        ),
    ]
