# Generated by Django 2.1.3 on 2018-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_add_export_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vat_verified',
            field=models.BooleanField(null=True),
        ),
    ]
