# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_add_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
