# Generated by Django 2.2.1 on 2019-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_switch_to_booleanfield_with_null_kwarg'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_on', 'id'], name='order_order_created_db8872_idx'),
        ),
    ]
