# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omis-quote', '0001_initial'),
        ('order', '0012_contact-email-phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='omis-quote.Quote'),
        ),
    ]
