# Generated by Django 3.1.12 on 2021-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_add_created_on_id_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_created_db8872_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['modified_on', 'id'], name='order_order_modifie_87c98b_idx'),
        ),
    ]
