# Generated by Django 4.2.11 on 2024-05-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0080_update_services'),
        ('company', '0141_auto_20240222_1534'),
        ('order', '0013_auto_20210922_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='company.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='company.contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hourly_rate',
            field=models.ForeignKey(default='7e1ca5c3-dc5a-e511-9d3c-e4115bead28a', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='order.hourlyrate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='primary_market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='metadata.country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='order.servicetype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uk_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='metadata.ukregion'),
        ),
    ]
