# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('quote_awaiting_acceptance', 'Quote awaiting acceptance'), ('quote_accepted', 'Quote accepted'), ('paid', 'Paid'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='draft', max_length=100),
        ),
    ]
