# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('rate_value', models.PositiveIntegerField(help_text='Rate in pence. E.g. 1 pound should be stored as 100 (100 pence).')),
                ('vat_value', models.DecimalField(decimal_places=2, help_text='VAT to apply as percentage value (0.00 to 100.00).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'db_table': 'omis-order_hourlyrate',
            },
        ),
    ]
