# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 17:15
from __future__ import unicode_literals

from django.db import migrations


def create_default_hourlyrate(apps, schema_editor):
    HourlyRate = apps.get_model('order', 'HourlyRate')
    HourlyRate.objects.get_or_create(
        id='7e1ca5c3-dc5a-e511-9d3c-e4115bead28a',
        defaults={
            'name': 'Default rate',
            'rate_value': 1000,
            'vat_value': '20.00'
        }
    )

def noop_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_hourlyrate'),
    ]

    operations = [
        migrations.RunPython(create_default_hourlyrate, noop_reverse),
    ]
