# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_hourly_rate_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hourly_rate',
            field=models.ForeignKey(default='7e1ca5c3-dc5a-e511-9d3c-e4115bead28a', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.HourlyRate'),
        ),
    ]
