# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
