# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20170912_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_status',
            field=models.CharField(blank=True, choices=[('uk', 'UK'), ('eu', 'EU excluding the UK'), ('outside_eu', 'Outside the EU')], max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_verified',
            field=models.NullBooleanField(),
        ),
    ]
