# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20170912_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_cost',
            field=models.PositiveIntegerField(default=0, help_text='Total hours * hourly rate in pence.'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_cost',
            field=models.PositiveIntegerField(default=0, help_text='Net cost - discount value in pence.'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, help_text='Subtotal + VAT cost in pence.'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_cost',
            field=models.PositiveIntegerField(default=0, help_text='VAT amount of subtotal in pence.'),
        ),
    ]
