# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_pricing-fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.CharField(blank=True, help_text='Used for public facing access.', max_length=100),
        ),
    ]
