# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:10
from __future__ import unicode_literals
import secrets

from django.db import migrations


def get_random_public_token(Order):
    public_token = secrets.token_urlsafe(37)
    if not Order.objects.filter(public_token=public_token).exists():
        return public_token
    return get_random_public_token(Order)


def populate_public_token(apps, schema_editor):
    """Populate the Order.public_token field."""
    Order = apps.get_model('order', 'Order')
    for order in Order.objects.filter(public_token=''):
        order.public_token = get_random_public_token(Order)
        order.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_public_token'),
    ]

    operations = [
        migrations.RunPython(populate_public_token, noop_reverse),
    ]
