# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0001_initial'),
        ('order', '0025_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='omis-invoice.Invoice'),
        ),
    ]
