# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrate',
            name='disabled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
