# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_hourlyrate_disabled_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_documents_url_path',
            field=models.CharField(blank=True, help_text='Legacy field. Link to the archived documents for this order.', max_length=255),
        ),
    ]
