# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
