# Generated by Django 2.0.1 on 2018-01-03 12:12

from django.db import migrations


FIELDS = (
        'billing_company_name', 'billing_contact_name',
        'billing_address_1', 'billing_address_2',
        'billing_address_town', 'billing_address_county',
        'billing_address_postcode', 'billing_address_country_id',
        'po_number'
    )

def update_billing_fields(apps, schema_editor):
    Order = apps.get_model('order', 'Order')

    for order in Order.objects.filter(invoice__isnull=False).select_related('invoice'):
        for field in FIELDS:
            order_field_value = getattr(order, field)
            setattr(order.invoice, field, order_field_value)
        order.invoice.save(update_fields=FIELDS)


class Migration(migrations.Migration):
    dependencies = [
        ('omis-invoice', '0004_billing_fields'),
        ('order', '0005_order_billing_company_name'),
    ]

    operations = [
        migrations.RunPython(update_billing_fields, migrations.RunPython.noop, elidable=True),
    ]
