# Generated by Django 2.0.1 on 2018-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0005_populate_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address of the contact at the time of invoice creation.', max_length=255),
        ),
    ]
