# Generated by Django 2.0.1 on 2018-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0006_invoice_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='net_cost',
            field=models.PositiveIntegerField(default=0, help_text='Net value in pence.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_cost',
            field=models.PositiveIntegerField(default=0, help_text='Net cost - any discount in pence.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, help_text='Subtotal + VAT cost in pence.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_cost',
            field=models.PositiveIntegerField(default=0, help_text='VAT amount of subtotal in pence.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_verified',
            field=models.NullBooleanField(),
        ),
    ]
