# Generated by Django 2.0.1 on 2018-01-07 09:05

from django.db import migrations

FIELDS = (
    'vat_status', 'vat_number', 'vat_verified', 'net_cost',
    'subtotal_cost', 'vat_cost', 'total_cost'
)

def update_pricing_fields(apps, schema_editor):
    Order = apps.get_model('order', 'Order')

    for order in Order.objects.filter(invoice__isnull=False).select_related('invoice'):
        for field in FIELDS:
            order_field_value = getattr(order, field)
            setattr(order.invoice, field, order_field_value)
        order.invoice.save(update_fields=FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0007_pricing_fields'),
        ('order', '0001_squashed_0030_cancellation'),
    ]

    operations = [
        migrations.RunPython(update_pricing_fields, migrations.RunPython.noop, elidable=True),
    ]
