# Generated by Django 2.0.1 on 2018-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0008_populate_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
