# Generated by Django 2.0.1 on 2018-01-08 16:34

from django.db import migrations


def update_order_reference(apps, schema_editor):
    Order = apps.get_model('order', 'Order')

    for order in Order.objects.filter(invoice__isnull=False).select_related('invoice'):
        order.invoice.order_reference = order.reference
        order.invoice.save(update_fields=('order_reference',))


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0009_order_ref'),
        ('order', '0001_squashed_0030_cancellation'),
    ]

    operations = [
        migrations.RunPython(update_order_reference, migrations.RunPython.noop, elidable=True),
    ]
