# Generated by Django 2.0.8 on 2018-08-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis-invoice', '0010_populate_order_ref'),
        ('core', '0003_rename_read_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
    ]
