# Generated by Django 3.2.6 on 2021-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis_invoice', '0012_switch_to_booleanfield_with_null_kwarg'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='omis-invoice_invoice',
        ),
    ]
