# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_squashed_0011_add_default_id_for_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metadata.Country')),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OMIS Market',
                'verbose_name_plural': 'OMIS Markets',
            },
        ),
    ]
