# Generated by Django 3.2.6 on 2021-08-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='market',
            table='omis-market_market',
        ),
    ]
