# Generated by Django 2.1 on 2018-08-31 13:39

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('search_export', 'Exported search results')], max_length=255)),
                ('api_url_path', models.CharField(db_index=True, max_length=5000, verbose_name='API URL path')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['api_url_path', 'timestamp'], name='user_event__api_url_1a6014_idx'),
        ),
    ]
