# Generated by Django 2.1 on 2018-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='type',
            field=models.CharField(choices=[('search_export', 'Exported search results'), ('proposition_document_delete', 'Deleted proposition document'), ('evidence_document_delete', 'Deleted evidence document')], max_length=255),
        ),
    ]
