# Generated by Django 3.0.4 on 2020-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_log', '0002_update_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['type', 'adviser'], name='user_event__type_6deef3_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['timestamp', 'type', 'adviser'], name='user_event__timesta_957ef8_idx'),
        ),
    ]
