# Generated by Django 3.0.5 on 2020-04-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_log', '0003_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='type',
            field=models.CharField(choices=[('search_export', 'Exported search results'), ('proposition_document_delete', 'Deleted proposition document'), ('evidence_document_delete', 'Deleted evidence document'), ('oauth_token_introspection', 'OAuth token introspection')], max_length=255),
        ),
    ]
