# Generated by Django 3.0.5 on 2020-05-12 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_log', '0004_add_introspection_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='api_url_path',
            field=models.CharField(blank=True, db_index=True, max_length=5000, verbose_name='API URL path'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
