# Generated by Django 3.2.20 on 2023-09-15 09:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_log', '0005_make_timestamp_overridable_url_path_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
