# Generated by Django 3.2.23 on 2024-01-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_log', '0006_alter_userevent_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='type',
            field=models.CharField(choices=[('search_export', 'Exported search results'), ('proposition_document_delete', 'Deleted proposition document'), ('evidence_document_delete', 'Deleted evidence document'), ('oauth_token_introspection', 'OAuth token introspection'), ('task_created', 'Task created')], max_length=255),
        ),
    ]
