# Generated by Django 4.2.15 on 2024-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_auto_20180831_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencedocument',
            name='tags',
            field=models.ManyToManyField(related_name='+', to='evidence.evidencetag'),
        ),
    ]
