# Generated by Django 4.2.11 on 2024-05-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_auto_20180831_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencedocument',
            name='tags',
            field=models.ManyToManyField(related_name='+', to='evidence.evidencetag'),
        ),
    ]
