# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('interaction', '0001_initial'), ('interaction', '0002_auto_20170201_1648'), ('interaction', '0003_servicedelivery_feedback'), ('interaction', '0004_auto_20170302_1421'), ('interaction', '0005_auto_20170405_1406')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0012_auto_20170201_1458'),
        ('metadata', '0004_servicedeliverystatus'),
        ('metadata', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('notes', models.TextField(max_length=4000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Contact')),
                ('dit_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('dit_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Team')),
                ('interaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.InteractionType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDelivery',
            fields=[
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(null=True)),
                ('archived_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('notes', models.TextField(max_length=4000)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to='company.Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to='company.Contact')),
                ('country_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Country')),
                ('dit_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to=settings.AUTH_USER_MODEL)),
                ('dit_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Team')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Sector')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dit_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Team')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Service')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Event')),
            ],
        ),
        migrations.AddField(
            model_name='servicedelivery',
            name='service_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.ServiceOffer'),
        ),
        migrations.AddField(
            model_name='servicedelivery',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.ServiceDeliveryStatus'),
        ),
        migrations.AddField(
            model_name='servicedelivery',
            name='uk_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.UKRegion'),
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived_on',
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived_reason',
        ),
        migrations.AddField(
            model_name='servicedelivery',
            name='feedback',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='servicedelivery',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Event'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='country_of_interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Sector'),
        ),
    ]
