# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:00
from __future__ import unicode_literals

import datahub.core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0003_merge_20161207_0414'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    primary_key=True,
                    serialize=False)),
                ('date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('notes', models.TextField()),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='interaction_interaction_related',
                    related_query_name='(app_label)s_interactions',
                    to='company.Company')),
                ('contact', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='interaction_interaction_related',
                    related_query_name='(app_label)s_interactions',
                    to='company.Contact')),
                ('dit_advisor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='interaction_interaction_related',
                    related_query_name='(app_label)s_interactions',
                    to=settings.AUTH_USER_MODEL)),
                ('dit_team', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='metadata.Team')),
                ('interaction_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='metadata.InteractionType')),
                ('service', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='metadata.Service')),
            ],
            options={'abstract': False, },
            bases=(datahub.core.mixins.KorbenSaveModelMixin, models.Model), ),
    ]
