# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='archived_on',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='archived_reason',
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived_on',
        ),
        migrations.RemoveField(
            model_name='servicedelivery',
            name='archived_reason',
        ),
    ]
