# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20170201_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedelivery',
            name='feedback',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
