# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_add_investment_project_to_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Contact'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dit_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='interaction.CommunicationChannel', help_text='For interactions only.'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Service'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to='company.Contact'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='country_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='dit_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedeliverys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='dit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Event'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='feedback',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Sector'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Service'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='service_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.ServiceOffer'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='uk_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.UKRegion'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='dit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Team'),
        ),
    ]
