# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_fix_blank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='dit_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.InteractionType'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Service'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='country_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='dit_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedeliverys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='dit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Event'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Sector'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Service'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='service_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.ServiceOffer'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.ServiceDeliveryStatus'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='uk_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.UKRegion'),
        ),
    ]
