# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_fix_blank_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='dit_advisor',
            new_name='dit_adviser',
        ),
        migrations.RenameField(
            model_name='servicedelivery',
            old_name='dit_advisor',
            new_name='dit_adviser',
        ),
    ]
