# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_event'),
        ('interaction', '0003_servicedelivery_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedelivery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Event'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Event'),
        ),
    ]
