# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_rename_advsor_fkeys_to_adviser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'permissions': (('view_interaction', 'Can View Interaction'),)},
        ),
        migrations.AlterModelOptions(
            name='servicedelivery',
            options={'permissions': (('view_servicedelivery', 'Can View Service Delivery'),), 'verbose_name_plural': 'service deliveries'},
        ),
        migrations.AlterModelOptions(
            name='serviceoffer',
            options={'permissions': (('view_serviceoffer', 'Can View Service Offer'),)},
        ),
    ]
