# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_auto_20170405_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Contact'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dit_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dit_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.InteractionType'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Service'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to='company.Contact'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='dit_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicedeliverys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='dit_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Service'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='dit_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Team'),
        ),
    ]
