# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_created_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'permissions': (('view_interaction', 'Can view interaction'),)},
        ),
        migrations.AlterModelOptions(
            name='servicedelivery',
            options={'permissions': (('view_servicedelivery', 'Can view service delivery'),), 'verbose_name_plural': 'service deliveries'},
        ),
        migrations.AlterModelOptions(
            name='serviceoffer',
            options={'permissions': (('view_serviceoffer', 'Can view service offer'),)},
        ),
    ]
