# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_auto_20170511_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedelivery',
            options={'verbose_name_plural': 'service deliveries'},
        ),
    ]
