# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_auto_20170807_1124'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['-date', '-created_on'], name='interaction_date_06c266_idx'),
        ),
    ]
