# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_correct_model_plural_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicedelivery',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
