# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_add_service'),
        ('interaction', '0008_add_interaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='event.Event', help_text='For service deliveries only.'),
        ),
    ]
