# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0011_move_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='communication_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL,
                                    to='interaction.CommunicationChannel',
                                    help_text='For interactions only.')
        )
    ]
