# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0012_update_interaction_type_fkeys'),
    ]

    operations = [
    ]
