# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0013_rename_interaction_type_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'permissions': (('read_interaction', 'Can read interaction'),)},
        ),
        migrations.AlterModelOptions(
            name='servicedelivery',
            options={'permissions': (('read_servicedelivery', 'Can read service delivery'),), 'verbose_name_plural': 'service deliveries'},
        ),
    ]
