# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0013_rename_interaction_type_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDelivery',
        ),
        migrations.DeleteModel(
            name='ServiceOffer',
        ),
    ]
