# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0015_adding_read_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='archived_documents_url_path',
            field=models.CharField(blank=True, help_text='Legacy field. File browser path to the archived documents for this interaction.', max_length=255),
        ),
    ]
