# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0017_add_default_id_for_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'permissions': (('read_all_interaction', 'Can read all interaction'), ('read_associated_investmentproject_interaction', 'Can read interaction for associated investment projects'), ('add_associated_investmentproject_interaction', 'Can add interaction for associated investment projects'), ('change_associated_investmentproject_interaction', 'Can change interaction for associated investment projects'))},
        ),
    ]
