# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:36
from __future__ import unicode_literals

import datahub.interaction.models
from django.db import migrations


permission_rename_operations = (
    (
        'read_interaction',
        'Can read interaction',
        'read_all_interaction',
        'Can read all interaction',
    ),
    (
        'change_interaction',
        'Can change interaction',
        'change_all_interaction',
        'Can change all interaction',
    ),
    (
        'add_interaction',
        'Can add interaction',
        'add_all_interaction',
        'Can add all interaction',
    )
)


def update_permissions(apps, schema_editor):
    Permission = apps.get_model('auth.Permission')

    for old_codename, old_name, new_codename, new_name in permission_rename_operations:
        try:
            permission = Permission.objects.get(codename=old_codename)
            permission.codename = new_codename
            permission.name = new_name
            permission.save()
        except Permission.DoesNotExist:
            # Permissions won't exist yet when running tests or in new environments
            pass


def update_permissions_reverse(apps, schema_editor):
    Permission = apps.get_model('auth.Permission')

    for old_codename, old_name, new_codename, new_name in permission_rename_operations:
        permission = Permission.objects.get(codename=new_codename)
        permission.codename = old_codename
        permission.name = old_name
        permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0018_add_assoc_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'default_permissions': ('add_all', 'change_all', 'delete'), 'permissions': (('read_all_interaction', 'Can read all interaction'), ('read_associated_investmentproject_interaction', 'Can read interaction for associated investment projects'), ('add_associated_investmentproject_interaction', 'Can add interaction for associated investment projects'), ('change_associated_investmentproject_interaction', 'Can change interaction for associated investment projects'))},
        ),
        migrations.RunPython(update_permissions, update_permissions_reverse, elidable=True),
    ]
