# Generated by Django 2.0.2 on 2018-02-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0020_add_status_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='service_delivery_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interaction.ServiceDeliveryStatus'),
        ),
    ]
