# Generated by Django 2.0.2 on 2018-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0021_add_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='grant_amount_offered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
