# Generated by Django 2.0.2 on 2018-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0022_grant_amount_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='net_company_receipt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, help_text='For service deliveries only.'),
        ),
    ]
