# Generated by Django 2.0.3 on 2018-04-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0024_add_policy_area_and_type_20180321_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='policy_area',
            field=models.ForeignKey(
                blank=True,
                help_text='For policy feedback only.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='interaction.PolicyArea'
            ),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='policy_issue_type',
            field=models.ForeignKey(
                blank=True,
                help_text='For policy feedback only.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='interaction.PolicyIssueType'
            ),
        ),
    ]
