# Generated by Django 2.0.6 on 2018-06-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0027_add_policy_areas'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='interaction',
                    name='policy_area',
                ),
            ],
        ),
    ]
