# Generated by Django 2.0.6 on 2018-06-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0028_remove_policy_area_from_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='interaction',
                    name='policy_area',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Deprecated; replaced by policy areas.',
                        null=True, on_delete=django.db.models.deletion.PROTECT,
                        related_name='+', to='interaction.PolicyArea',
                        verbose_name='legacy policy area',
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='policy_area',
        ),
    ]
