# Generated by Django 2.1 on 2018-08-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_read_permissions'),
        ('interaction', '0030_add_export_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'default_permissions': ('add_all', 'change_all', 'delete', 'view_all'), 'permissions': (('view_associated_investmentproject_interaction', 'Can view interaction for associated investment projects'), ('add_associated_investmentproject_interaction', 'Can add interaction for associated investment projects'), ('change_associated_investmentproject_interaction', 'Can change interaction for associated investment projects'), ('view_policy_feedback_interaction', 'Can view policy feedback interaction'), ('add_policy_feedback_interaction', 'Can add policy feedback interaction'), ('change_policy_feedback_interaction', 'Can change policy feedback interaction'), ('export_interaction', 'Can export interaction'))},
        ),
    ]
