# Generated by Django 2.1 on 2018-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0031_update_permissions_django_21'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
