# Generated by Django 2.1.4 on 2018-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0032_increase_notes_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='policy_feedback_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='policy_issue_types',
            field=models.ManyToManyField(blank=True, related_name='interactions', to='interaction.PolicyIssueType'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='was_policy_feedback_provided',
            field=models.BooleanField(null=True),
        ),
    ]
