# Generated by Django 2.1.4 on 2019-01-04 13:27

from logging import getLogger

from django.db import migrations


PERMISSIONS_TO_DELETE = (
    'view_policy_feedback_interaction',
    'change_policy_feedback_interaction',
    'add_policy_feedback_interaction',
)


logger = getLogger(__name__)


def delete_policy_feedback_permissions(apps, schema_editor):
    permission_model = apps.get_model('auth', 'Permission')

    _, deletions_by_model = permission_model.objects.filter(
        codename__in=PERMISSIONS_TO_DELETE,
        content_type__app_label='interaction',
    ).delete()

    logger.info(
        f'Deleted policy feedback permissions, breakdown of deleted objects: {deletions_by_model}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0035_remove_policy_fedback_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'default_permissions': ('add_all', 'change_all', 'delete', 'view_all'), 'permissions': (('view_associated_investmentproject_interaction', 'Can view interaction for associated investment projects'), ('add_associated_investmentproject_interaction', 'Can add interaction for associated investment projects'), ('change_associated_investmentproject_interaction', 'Can change interaction for associated investment projects'), ('export_interaction', 'Can export interaction'))},
        ),
        migrations.RunPython(delete_policy_feedback_permissions, migrations.RunPython.noop, elidable=True),
    ]
