# Generated by Django 2.1.5 on 2019-01-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0036_remove_policy_fedback_permissions'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='interaction',
                    name='policy_issue_type',
                ),
            ],
        ),
    ]
