# Generated by Django 2.1.5 on 2019-01-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0037_remove_policy_issue_type_from_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='interaction',
                    name='policy_issue_type',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Used for legacy policy feedback interactions only.',
                        related_name='+',
                        null=True,
                        on_delete=models.deletion.PROTECT,
                        to='interaction.PolicyIssueType',
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='policy_issue_type',
        ),
    ]
