# Generated by Django 2.1.5 on 2019-01-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0038_remove_policy_issue_type_from_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='policy_feedback_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='was_policy_feedback_provided',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
