# Generated by Django 2.1.5 on 2019-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0039_make_policy_provided_and_notes_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='was_policy_feedback_provided',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
