# Generated by Django 2.1.5 on 2019-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_trading_names_not_null'),
        ('interaction', '0040_make_policy_provided_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='interactions_m2m', to='company.Contact'),
        ),
    ]
