# Generated by Django 2.1.5 on 2019-01-31 09:25

from logging import getLogger

from django.db import migrations
from django.db.models import Exists, OuterRef

logger = getLogger(__name__)


def copy_contacts(apps, schema_editor):
    """Copies contact to contacts."""
    interaction_model = apps.get_model('interaction', 'Interaction')
    no_contacts_subquery = Exists(
        interaction_model.objects.filter(
            pk=OuterRef('pk'),
            contacts__id__isnull=True,
        ).only(
            'pk',
        )
    )
    interactions_with_uncopied_contacts = interaction_model.objects.select_for_update().annotate(
        has_no_contacts=no_contacts_subquery,
    ).filter(
        contact__isnull=False,
        has_no_contacts=True,
    ).only(
        'pk',
        'contact',
    )

    num_updated = 0

    for interaction in interactions_with_uncopied_contacts:
        interaction.contacts.add(interaction.contact)
        num_updated += 1

    logger.info(
        f'Interaction.contact copied to Interaction.contacts for {num_updated} interactions',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0041_add_contacts_field'),
    ]

    operations = [
        migrations.RunPython(copy_contacts, migrations.RunPython.noop, elidable=True)
    ]
