# Generated by Django 2.1.7 on 2019-03-08 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0042_copy_contact_to_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='dit_adviser',
            field=models.ForeignKey(help_text='This field is deprecated and has been replaced by DIT participants.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dit_team',
            field=models.ForeignKey(help_text='This field is deprecated and has been replaced by DIT participants.', null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.Team'),
        ),
    ]
