# Generated by Django 2.1.7 on 2019-03-11 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_add_chinese_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0043_stricter_dit_adviser_and_dit_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionDITParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dit_participants', to='interaction.Interaction')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metadata.Team')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='interactionditparticipant',
            unique_together={('interaction',)},
        ),
    ]
