# Generated by Django 2.1.7 on 2019-03-12 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0044_add_dit_participants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interactionditparticipant',
            unique_together={('interaction', 'adviser')},
        ),
    ]
