# Generated by Django 2.1.7 on 2019-03-15 16:00

from logging import getLogger

from django.db import migrations
from django.db.models import Exists, OuterRef, Q

logger = getLogger(__name__)


def populate_dit_participants(apps, schema_editor):
    """
    Creates InteractionDITParticipant objects using Interaction.dit_adviser and
    Interaction.dit_team.
    """
    interaction_model = apps.get_model('interaction', 'Interaction')
    interaction_dit_participant_model = apps.get_model('interaction', 'InteractionDITParticipant')

    queryset = interaction_model.objects.select_for_update().annotate(
        has_participants=Exists(
            interaction_dit_participant_model.objects.filter(
                interaction_id=OuterRef('pk'),
            ),
        ),
    ).filter(
        Q(dit_adviser__isnull=False) | Q(dit_team__isnull=False),
        has_participants=False,
    ).values(
        'pk',
        'dit_adviser_id',
        'dit_team_id',
    )

    num_created = 0

    for interaction in queryset.iterator():
        interaction_dit_participant_model(
            interaction_id=interaction['pk'],
            adviser_id=interaction['dit_adviser_id'],
            team_id=interaction['dit_team_id'],
        ).save()

        num_created += 1

    logger.info(
        f'InteractionDITParticipant objects created for {num_created} interactions',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0045_update_dit_participants_unique_constaint'),
    ]

    operations = [
        migrations.RunPython(populate_dit_participants, migrations.RunPython.noop, elidable=True)
    ]
