# Generated by Django 2.2 on 2019-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0046_populate_dit_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('complete', 'Complete')], max_length=255, null=True),
        ),
    ]
