# Generated by Django 2.1.7 on 2019-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0046_populate_dit_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='complete', max_length=255),
        ),
    ]
