# Generated by Django 2.2 on 2019-04-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0047_add_status_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='archived',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
