# Generated by Django 2.1.7 on 2019-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0047_add_state_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='meeting_uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
