# Generated by Django 2.1.7 on 2019-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0048_interaction_meeting_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='meeting_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
