# Generated by Django 2.1.7 on 2019-03-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0049_interaction_source'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='interaction',
                    name='contact',
                ),
            ],
        ),
    ]
