# Generated by Django 2.2 on 2019-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0051_remove_contact_from_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='theme',
            field=models.CharField(blank=True, choices=[(None, 'Not set',), ('export', 'Export'), ('investment', 'Investment'), ('other', 'Something else')], max_length=255, null=True),
        ),
    ]
