# Generated by Django 2.2 on 2019-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0052_add_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='complete', max_length=255),
        ),
    ]
