# Generated by Django 2.2.1 on 2019-05-28 10:18
from pathlib import PurePath

from django.db import migrations

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_service_questions_and_answers(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0057_add_service_questions_and_answers.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0056_add_serviceadditionalquestion_serviceansweroption_servicequestion'),
    ]

    operations = [
        migrations.RunPython(load_service_questions_and_answers, migrations.RunPython.noop),
    ]
