# Generated by Django 2.2.1 on 2019-05-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0056_add_serviceadditionalquestion_serviceansweroption_servicequestion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['modified_on', 'id'], name='interaction_modifie_d52a56_idx'),
        ),
    ]
