# Generated by Django 2.2 on 2019-05-28 10:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0057_add_modified_on_id_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['source'], name='interaction_source_cfbd11_gin'),
        ),
    ]
