# Generated by Django 2.2.1 on 2019-06-05 07:20

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0057_add_service_questions_and_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='service_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
