# Generated by Django 2.2.3 on 2019-07-28 19:24

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0063_add_index_for_company_list'),
        ('metadata', '0037_add_service_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='service',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='metadata.Service',
            ),
        ),
        migrations.AlterField(
            model_name='servicequestion',
            name='service',
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='interaction_questions',
                to='metadata.Service',
            ),
        ),
    ]
