# Generated by Django 2.2.4 on 2019-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0066_remove_dit_adviser_and_team_from_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='interaction',
                    name='location',
                ),
            ],
        ),
    ]
