# Generated by Django 2.2.5 on 2019-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_squashed_0068_remove_interaction_location_from_database'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['created_on', 'id'], name='interaction_created_9a2917_idx'),
        ),
    ]
