# Generated by Django 2.2.7 on 2019-11-22 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0010_auto_20180613_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0069_add_composite_index_to_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='were_countries_discussed',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='InteractionExportCountry',
            fields=[
                (
                    'created_on',
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    'modified_on',
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    'id',
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                (
                    'status',
                    models.CharField(choices=[
                        ('not_interested', 'Not interested'),
                        ('currently_exporting', 'Currently exporting to'),
                        ('future_interest', 'Future country of interest')
                    ], max_length=255),
                ),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='interaction_discussed',
                        to='metadata.Country'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'interaction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='export_countries',
                        to='interaction.Interaction'
                    ),
                ),
                (
                    'modified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'interaction export countries',
            },
        ),
        migrations.AddConstraint(
            model_name='interactionexportcountry',
            constraint=models.UniqueConstraint(
                fields=('country', 'interaction'),
                name='unique_country_interaction',
            ),
        ),
    ]
