# Generated by Django 3.1.5 on 2021-02-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0070_add_interaction_export_countries'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='theme',
            field=models.CharField(blank=True, choices=[(None, 'Not set'), ('export', 'Export'), ('investment', 'Investment'), ('large_capital_opportunity', 'Large capital opportunity'), ('other', 'Something else')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='large_capital_opportunity',
            field=models.ForeignKey(blank=True, help_text='For interactions only.', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='interactions',
                                    to='opportunity.largecapitalopportunity'),
        ),
    ]
