# Generated by Django 3.1.6 on 2021-02-22 10:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0071_add_large_capital_opportunity_and_update_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='service_answers',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='source',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
