# Generated by Django 3.1.7 on 2021-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0072_auto_20210222_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='theme',
            field=models.CharField(blank=True, choices=[(None, 'Not set'), ('export', 'Export'), ('investment', 'Investment'), ('large_capital_opportunity', 'Large capital opportunity'), ('trade_agreement', 'Trade agreement'), ('other', 'Something else')], max_length=255, null=True),
        ),
    ]
