# Generated by Django 3.1.7 on 2021-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_tradeagreement'),
        ('interaction', '0074_update_service_questions_and_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='has_related_trade_agreements',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='related_trade_agreements',
            field=models.ManyToManyField(blank=True, to='metadata.TradeAgreement'),
        ),
    ]
