# Generated by Django 3.1.8 on 2021-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0111_add_telephone_validation'),
        ('interaction', '0075_add_trade_agreement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='company_interactions', to='company.Company'),
        ),
    ]
