# Generated by Django 3.1.12 on 2021-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0076_interaction_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='has_related_opportunity',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
