# Generated by Django 3.2.16 on 2023-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0038_add_export_barrier_type'),
        ('interaction', '0080_add_new_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='export_barrier_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interaction',
            name='export_barrier_types',
            field=models.ManyToManyField(blank=True, related_name='interactions', to='metadata.ExportBarrierType'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='helped_remove_export_barrier',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
