# Generated by Django 4.2.11 on 2024-05-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0019_alter_investmentproject_status'),
        ('event', '0028_alter_event_teams'),
        ('opportunity', '0003_add_export_permission'),
        ('company', '0141_auto_20240222_1534'),
        ('interaction', '0081_auto_20230130_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='company.company'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='company.contact'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='event',
            field=models.ForeignKey(blank=True, help_text='For service deliveries only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='event.event'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='investment_project',
            field=models.ForeignKey(blank=True, help_text='For interactions only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='investment.investmentproject'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='large_capital_opportunity',
            field=models.ForeignKey(blank=True, help_text='For interactions only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='opportunity.largecapitalopportunity'),
        ),
    ]
