# Generated by Django 5.2.1 on 2025-05-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0083_interaction_company_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='theme',
            field=models.CharField(blank=True, choices=[(None, 'Not set'), ('export', 'Export'), ('investment', 'Investment'), ('large_capital_opportunity', 'Large capital opportunity'), ('trade_agreement', 'Trade agreement'), ('domestic', 'Domestic'), ('other', 'Something else')], max_length=255, null=True),
        ),
    ]
