# Generated by Django 2.1.3 on 2018-12-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub.mi_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miinvestmentproject',
            name='number_new_jobs_with_zero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='miinvestmentproject',
            name='number_safeguarded_jobs_with_zero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='miinvestmentproject',
            name='total_investment_with_zero',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True),
        ),
    ]
