# Generated by Django 2.1.3 on 2018-12-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub.mi_dashboard', '0002_add_extra_number_fields'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='miinvestmentproject',
            table='mi_dashboard_miinvestmentproject',
        ),
    ]
