# Generated by Django 2.1.5 on 2019-01-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub.mi_dashboard', '0003_set_explicit_table_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='miinvestmentproject',
            index=models.Index(fields=['financial_year'], name='mi_dashboar_financi_3f378f_idx'),
        ),
    ]
