# Generated by Django 2.1 on 2018-08-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencedocument',
            options={'default_permissions': ('add_all', 'change_all', 'delete_all', 'view_all'), 'permissions': (('view_associated_evidencedocument', 'Can view evidence document for associated investment projects'), ('add_associated_evidencedocument', 'Can add evidence document for associated investment projects'), ('change_associated_evidencedocument', 'Can change evidence document for associated investment projects'), ('delete_associated_evidencedocument', 'Can delete evidence document for associated investment projects')), 'verbose_name': 'investment project evidence document'},
        ),
    ]
