# Generated by Django 2.1 on 2018-08-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_initial_evidence_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencedocument',
            options={'default_permissions': ('add_all', 'change_all', 'delete_all', 'view_all'), 'permissions': (('add_associated_evidencedocument', 'Can add evidence document for associated investment projects'), ('change_associated_evidencedocument', 'Can change evidence document for associated investment projects'), ('delete_associated_evidencedocument', 'Can delete evidence document for associated investment projects'), ('view_associated_evidencedocument', 'Can view evidence document for associated investment projects')), 'verbose_name': 'investment project evidence document'},
        ),
    ]
