version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8-bugbear # TET-129
    versions:
    - "> 22.1.11"
    dependency-name: pylint-pytest
    versions:
    - "> 1.1.2"
  rebase-strategy: disabled
