---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- fixtures/
- dummy-korben/
- "**/migrations/"
- "**.yml"
- "**.txt"
- "**.rst"
- "**.sh"
- Dockerfile
- "**/test/"
- "**/tests/"


