---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
      - 69aa4cac78f91a365e565175a509ada2
      - 660e3d488a88ca2f495208adb50268d1
      - 335103688873a625dc7e953702e3e40b
      - a94c5caddd731c16fbe7406a3af4c77a
      - 551ddad31bbc5d8349c9cd514c98f089
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 32
  fixme:
    enabled: true
  radon:
    enabled: true
    exclude_fingerprints:
      - 578a67a5fc01bf16f9af5b9ec8c0c328
    config:
      python_version: 3
      threshold: "B"
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- config/
- fixtures/
- "**/migrations/"
- "**.yml"
- "**.xml"
- "**.txt"
- "**.rst"
- "**.sh"
- Dockerfile
- "**/test/"
- "**/tests/"


