# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20170822_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('read_permissionmodel', 'Can read permission'),),
            },
        ),
    ]
