# Generated by Django 2.1 on 2018-08-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_add_metadata_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('published_on', models.DateField()),
                ('genre', models.CharField(null=True, choices=[('horror', 'Horror'), ('non_fiction', 'Non-fiction')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='permissionmodel',
            options={},
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='support.Person'),
        ),
        migrations.AddField(
            model_name='book',
            name='proofreader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofread_books', to='support.Person'),
        ),
    ]
