# Generated by Django 2.1.4 on 2019-01-03 11:23

import datahub.core.test.support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_add_book_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullableWithDefaultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nullable_with_default', models.BooleanField(default=True, null=True)),
                ('nullable_with_callable_default', models.CharField(default=datahub.core.test.support.models._default_value_for_nullable_with_callable_default, max_length=255, null=True)),
                ('nullable_without_default', models.BooleanField(null=True)),
                ('non_nullable_with_default', models.BooleanField(default=True)),
            ],
        ),
    ]
