# Generated by Django 2.1.5 on 2019-01-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_add_nullable_with_default_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignAndM2MModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='support.MetadataModel')),
                ('values', models.ManyToManyField(blank=True, related_name='_foreignandm2mmodel_values_+', to='support.MetadataModel')),
            ],
        ),
    ]
