# Generated by Django 2.1.5 on 2019-01-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_add_m2m_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
