# Generated by Django 2.1.5 on 2019-01-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0010_auto_20180613_1553'),
        ('support', '0008_add_person_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_address_1', models.CharField(max_length=255)),
                ('primary_address_2', models.CharField(blank=True, max_length=255)),
                ('primary_address_town', models.CharField(max_length=255)),
                ('primary_address_county', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_address_postcode', models.CharField(blank=True, max_length=255)),
                ('secondary_address_1', models.CharField(blank=True, max_length=255)),
                ('secondary_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_address_town', models.CharField(blank=True, max_length=255)),
                ('secondary_address_county', models.CharField(blank=True, max_length=255)),
                ('secondary_address_postcode', models.CharField(blank=True, max_length=255)),
                ('primary_address_area', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='++', blank=True, null=True, to='metadata.AdministrativeArea')),
                ('primary_address_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.Country')),
                ('secondary_address_area', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='++', blank=True, null=True, to='metadata.AdministrativeArea')),
                ('secondary_address_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.Country')),
            ],
        ),
    ]
