# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omis-quote', '0002_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='expires_on',
            field=models.DateField(default=datetime.datetime(2030, 1, 1, 00, 00, 00, 000000)),
            preserve_default=False,
        ),
    ]
