# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis-quote', '0004_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': (('read_quote', 'Can read quote'),)},
        ),
    ]
