# Generated by Django 2.0.8 on 2018-08-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis-quote', '0007_initial_tsandcs'),
        ('core', '0003_rename_read_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
    ]
