# Generated by Django 3.2.6 on 2021-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis_quote', '0008_update_permissions_django_21'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quote',
            table='omis-quote_quote',
        ),
        migrations.AlterModelTable(
            name='termsandconditions',
            table='omis-quote_termsandconditions',
        ),
    ]
