# Generated by Django 4.2.15 on 2024-08-15 14:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EYBLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.TextField(blank=True, null=True)),
                ('triage_id', models.IntegerField()),
                ('triage_hashed_uuid', models.CharField(max_length=200)),
                ('triage_created', models.DateTimeField()),
                ('triage_modified', models.DateTimeField()),
                ('sector', models.CharField(max_length=255)),
                ('sector_sub', models.CharField(default=None, max_length=255, null=True)),
                ('intent', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=6)),
                ('intent_other', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_city', models.CharField(default=None, max_length=255, null=True)),
                ('location_none', models.BooleanField(default=None, null=True)),
                ('hiring', models.CharField(max_length=255)),
                ('spend', models.CharField(max_length=255)),
                ('spend_other', models.CharField(max_length=255, null=True)),
                ('is_high_value', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('user_hashed_uuid', models.CharField(max_length=200)),
                ('user_created', models.DateTimeField()),
                ('user_modified', models.DateTimeField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=255)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_info_email', models.BooleanField(default=False)),
                ('landing_timeframe', models.CharField(default=None, max_length=255, null=True)),
                ('company_website', models.CharField(max_length=255, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
