# Generated by Django 3.0.3 on 2020-02-06 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreferral',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyreferral',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyreferral',
            name='status',
            field=models.CharField(choices=[('outstanding', 'Outstanding'), ('closed', 'Closed'), ('complete', 'Complete')], default='outstanding', max_length=255),
        ),
    ]
