# Generated by Django 3.0.3 on 2020-02-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0070_add_interaction_export_countries'),
        ('company_referral', '0002_add_additional_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreferral',
            name='interaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interaction.Interaction'),
        ),
    ]
