# Generated by Django 3.0.3 on 2020-02-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_referral', '0004_add_interaction_related_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='companyreferral',
                    name='closed_by',
                ),
                migrations.RemoveField(
                    model_name='companyreferral',
                    name='closed_on',
                ),
            ],
        )
    ]
