# Generated by Django 3.0.3 on 2020-03-02 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_referral', '0005_remove_closed_fields_from_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='companyreferral',
                    name='closed_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_referrals', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='companyreferral',
                    name='closed_on',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='companyreferral',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='companyreferral',
            name='closed_on',
        ),
    ]
