# Generated by Django 3.0.4 on 2020-03-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_referral', '0006_remove_closed_fields_from_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreferral',
            name='notes',
            field=models.TextField(),
        ),
    ]
