# Generated by Django 3.0.4 on 2020-03-31 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0070_add_interaction_export_countries'),
        ('company_referral', '0007_make_notes_non_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreferral',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text="This should be filled in if the referral status is 'Complete'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyreferral',
            name='completed_on',
            field=models.DateTimeField(blank=True, help_text="This should be filled in if the referral status is 'Complete'.", null=True),
        ),
        migrations.AlterField(
            model_name='companyreferral',
            name='interaction',
            field=models.OneToOneField(blank=True, help_text="This should be filled in if the referral status is 'Complete'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_referral', to='interaction.Interaction'),
        ),
    ]
