# Generated by Django 3.2.11 on 2022-02-08 15:48

import datahub.core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment', '0005_update_specific_programmes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estimated_land_date', datahub.core.fields.MultipleChoiceField(blank=True, choices=(('30', '30 days'), ('60', '60 days')), max_length=255)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investment_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investment.investmentproject')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='investmentnotificationsubscription',
            constraint=models.UniqueConstraint(fields=('investment_project_id', 'adviser_id'), name='Unique Investment Notification Subscription'),
        ),
    ]
