# Generated by Django 3.2.15 on 2022-08-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationinnertemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentNotificationSubscription',
        ),
    ]
