# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinfo',
            options={'verbose_name_plural': 'Task info'},
        ),
    ]
