# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0002_auto_20170117_1007'),]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='db_table',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,),
        migrations.AddField(
            model_name='taskinfo',
            name='update',
            field=models.BooleanField(default=True),
            preserve_default=False,),
    ]
