# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0003_auto_20170118_1600'),]

    operations = [migrations.RemoveField(
        model_name='taskinfo',
        name='name',),]
