# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_taskinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='taskinfo',
            name='note',
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='task_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
