# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taskinfo_manual_rerun_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfo',
            name='manual_rerun_task',
        ),
        migrations.RemoveField(
            model_name='taskinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskInfo',
        ),
    ]
