# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_number', models.CharField(db_index=True, max_length=8, verbose_name='Company number')),
                ('company_name', models.CharField(max_length=160, verbose_name='Company name')),
                ('registered_address_care_of', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address care of')),
                ('registered_address_po_box', models.CharField(blank=True, max_length=10, null=True, verbose_name='Address POBox')),
                ('registered_address_address_1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 1 (House number and street')),
                ('registered_address_address_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 2 (area)')),
                ('registered_address_town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address town')),
                ('registered_address_county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address county')),
                ('registered_address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address country')),
                ('registered_address_postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Address postcode')),
                ('company_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company category')),
                ('company_status', models.CharField(blank=True, max_length=70, null=True, verbose_name='Company status')),
                ('sic_code_1', models.CharField(blank=True, max_length=170, null=True)),
                ('sic_code_2', models.CharField(blank=True, max_length=170, null=True)),
                ('sic_code_3', models.CharField(blank=True, max_length=170, null=True)),
                ('sic_code_4', models.CharField(blank=True, max_length=170, null=True)),
                ('uri', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_number', models.CharField(db_index=True, max_length=8, verbose_name='Company number')),
                ('uk_based', models.BooleanField()),
                ('business_type', models.CharField(max_length=160, verbose_name='Business type')),
                ('registered_name', models.CharField(max_length=160, verbose_name='Registered name')),
                ('trading_name', models.CharField(max_length=160, verbose_name='Trading name')),
                ('website', models.URLField(null=True, verbose_name='Website')),
                ('number_of_employees', models.CharField(blank=True, max_length=20, null=True, verbose_name='Number of employees')),
                ('annual_turnover', models.CharField(blank=True, max_length=20, null=True, verbose_name='Annual turnover')),
                ('trading_address_1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 1 (House number and street')),
                ('trading_address_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 2 (area)')),
                ('trading_address_town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address town')),
                ('trading_address_county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address county')),
                ('trading_address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address country')),
                ('trading_address_postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Address postcode')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Region')),
                ('account_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account manger')),
                ('currently_exporting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Role')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 1 (House number and street')),
                ('address_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 2 (area)')),
                ('address_town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address town')),
                ('address_county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address county')),
                ('address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address country')),
                ('address_postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Address postcode')),
                ('alt_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alt phone')),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject')),
                ('date_of_interaction', models.DateField()),
                ('advisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adviser')),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='title')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='api.Company')),
            ],
        ),
    ]
