# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcompany',
            name='incorporation_date',
            field=models.DateField(null=True),
        ),
    ]
