# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chcompany_incorporation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chcompany',
            name='id',
        ),
        migrations.AlterField(
            model_name='chcompany',
            name='company_number',
            field=models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False, verbose_name='Company number'),
        ),
    ]
