# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160824_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='currently_exporting',
        ),
        migrations.AddField(
            model_name='company',
            name='connections',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='countries_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='currently_exporting_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
