# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160830_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trading_name',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Trading name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
