# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160830_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uk_based',
            field=models.BooleanField(default=True),
        ),
    ]
