# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160830_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='Company number'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.Company'),
        ),
    ]
