# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160907_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_description',
            field=models.TextField(blank=True, help_text='A brief description of this company and what it does or things to be considered.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_contact_team',
            field=models.TextField(blank=True, help_text='A comma separated list of teams of which this is the primary contact for, e.g. Post teams - Estonia', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='annual_turnover',
            field=models.CharField(blank=True, choices=[('£0 to £1.34M', '£0 to £1.34M'), ('£1.34M to £6.7M', '£1.34M to £6.7M'), ('£6.7M to £33.5M', '£6.7M to £33.5M'), ('£33.5M +', '£33.5M +')], max_length=20, null=True, verbose_name='Annual turnover'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('Business partnership', 'Business partnership'), ('Private limited company', 'Private limited company'), ('Public limited company', 'Public limited company'), ('Sole trader', 'Sole trader')], help_text='The classification of the business type, e.g. Private Limited Company', max_length=160, verbose_name='Business type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(blank=True, db_index=True, help_text='The company number for companies filed with companies house so they can be displayed if provided.', max_length=8, null=True, verbose_name='Company number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='countries_of_interest',
            field=models.TextField(blank=True, help_text='A comma separated list of countries the company has expressed an interest in exporting to.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='currently_exporting_to',
            field=models.TextField(blank=True, help_text='A comma separated list of countries the company is already exporting to.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.CharField(blank=True, choices=[('1 to 9', '1 to 9'), ('10 to 49', '10 to 49'), ('50 to 249', '50 to 249'), ('500+', '500+')], max_length=20, null=True, verbose_name='Number of employees'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, help_text='The region responsible for this company, e.g. North-East', max_length=50, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=models.TextField(blank=True, help_text='A comma separated list of business sectors the company belongs to, e.g. Aerospace', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_name',
            field=models.CharField(blank=True, help_text='The name the company trades as, if this differs from the name it is registered as', max_length=160, null=True, verbose_name='Trading name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Does the company have a website?', null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Director', max_length=50, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Mr, Mrs', max_length=20, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('Face to face', 'Face to face'), ('Social media', 'Social media'), ('Video/teleconference', 'Video/teleconference'), ('Email', 'Email'), ('Fax', 'Fax'), ('Letter', 'Letter'), ('Phone call', 'Phone call')], max_length=20, null=True, verbose_name='Interaction type'),
        ),
    ]
