# Generated by Django 2.1.5 on 2019-01-10 11:14

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_squashed_0096_company_global_ultimate_duns_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnBMatchingCSVRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_id', models.UUIDField()),
                ('batch_number', models.PositiveIntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='DnBMatchingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
