# Generated by Django 2.2.9 on 2020-01-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_match', '0002_dnbmatchingresult_modified_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DnBMatchingCSVRecord',
        ),
        migrations.DeleteModel(
            name='DnBMatchingResult',
        ),
    ]
