# Generated by Django 2.2 on 2019-04-17 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnb_match', '0002_dnbmatchingresult_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnbmatchingcsvrecord',
            name='no_match_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnbmatchingcsvrecord',
            name='no_match_reason',
            field=models.CharField(blank=True, choices=[('not_listed', 'The correct company is not listed, it is not possible to make a match'), ('more_than_one', 'There is more than one company in the list that could be a match'), ('not_confident', 'I am not confident to make the match'), ('other', 'Other')], help_text='Reason why does not match.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dnbmatchingcsvrecord',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dnbmatchingcsvrecord',
            name='selected_duns_number',
            field=models.CharField(blank=True, help_text='Dun & Bradstreet unique identifier. Nine-digit number with leading zeros.', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='dnbmatchingcsvrecord',
            name='selected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
