# Generated by Django 2.2.9 on 2020-01-13 10:54

from django.db import migrations

from datahub.core.migration_utils import DeleteModelWithMetadata


def forward_func(apps, schema_editor):
    """
    Remove the rows associated with dnb_match in:
      - django_content_type
      - auth_permission
    """
    DeleteModelWithMetadata.delete_metadata(
        apps,
        'dnb_match',
        'dnbmatchingcsvrecord',
    )
    DeleteModelWithMetadata.delete_metadata(
        apps,
        'dnb_match',
        'dnbmatchingresult',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_match', '0003_delete'),
    ]

    operations = [
        migrations.RunPython(forward_func, migrations.RunPython.noop)
    ]
