# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0010_auto_20180613_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_add_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Seminar', 'Seminar'), ('Exhibition', 'Exhibition'), ('Inward mission', 'Inward mission'), ('Outward mission', 'Outward mission'), ('UK region local service', 'UK region local service')], max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('HQ', 'HQ'), ('Post', 'Post'), ('Regional network', 'Regional network'), ('Other', 'Other')], max_length=255, null=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('address_town', models.CharField(max_length=255)),
                ('address_county', models.CharField(blank=True, max_length=255)),
                ('address_postcode', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('additional_teams', models.ManyToManyField(blank=True, related_name='_event_additional_teams_+', to='metadata.Team')),
                ('address_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.Team')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_programmes', models.ManyToManyField(blank=True, to='event.Programme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
