# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_add_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_type',
            field=models.CharField(blank=True, choices=[('HQ', 'HQ'), ('Post', 'Post'), ('Regional network', 'Regional network'), ('Other', 'Other')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
