# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_add_location_type_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_teams',
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='_event_teams_+', to='metadata.Team'),
        ),
    ]
