# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_add_uk_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.Service'),
        ),
    ]
