# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_add_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='disabled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='disabled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='disabled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
