# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20171002_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='disabled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
