# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_disabled_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('read_event', 'Can read event'),)},
        ),
    ]
