# Generated by Django 2.2.6 on 2019-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_update_service_foreign_key'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_on', 'id'], name='event_event_created_4b24c3_idx'),
        ),
    ]
