# Generated by Django 3.1.7 on 2021-03-31 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_add_composite_index_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAgreement',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='has_related_trade_agreements',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='related_trade_agreements',
            field=models.ManyToManyField(blank=True, to='event.TradeAgreement'),
        ),
    ]
