# Generated by Django 3.1.7 on 2021-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_tradeagreement'),
        ('event', '0017_add_related_trade_agreement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='related_trade_agreements',
            field=models.ManyToManyField(blank=True, to='metadata.TradeAgreement'),
        ),
    ]
