# Generated by Django 3.1.7 on 2021-04-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_move_to_metadata_trade_agreement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeAgreement',
        ),
    ]
