# Generated by Django 4.2.11 on 2024-05-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0080_update_services'),
        ('event', '0027_update_event_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='+', to='metadata.team'),
        ),
    ]
