# Generated by Django 4.2.16 on 2024-12-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0020_rename_event_id_from_stova'),
        ('event', '0029_alter_event_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stova_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datahub_event', to='company_activity.stovaevent'),
        ),
    ]
