# Generated by Django 2.2.3 on 2019-07-18 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0001_add_list_item_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylistitem',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companylistitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_list_items', to='company.Company'),
        ),
    ]
