# Generated by Django 2.2.3 on 2019-08-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_list', '0002_alter_list_item_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_legacy_default', models.BooleanField(default=False, help_text='Temporary field that designates this as the list that the legacy company list API endpoints operate on.')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_lists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='companylist',
            constraint=models.UniqueConstraint(condition=models.Q(is_legacy_default=True), fields=('adviser',), name='unique_adviser_if_legacy_default'),
        ),
        migrations.AddConstraint(
            model_name='companylist',
            constraint=models.CheckConstraint(check=models.Q(is_legacy_default=True), name='disallow_is_legacy_default_false'),
        ),
    ]
