# Generated by Django 2.2.3 on 2019-08-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0003_add_company_list_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylistitem',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='company_list.CompanyList'),
        ),
    ]
