# Generated by Django 2.2.3 on 2019-08-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0005_populate_list_on_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='company_list.CompanyList'),
        ),
        migrations.AddConstraint(
            model_name='companylistitem',
            constraint=models.UniqueConstraint(fields=('list', 'company'), name='unique_list_and_company'),
        ),
    ]
