# Generated by Django 2.2.3 on 2019-08-16 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0006_make_item_list_non_nullable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companylistitem',
            name='unique_adviser_and_company',
        ),
        migrations.AlterField(
            model_name='companylistitem',
            name='adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveIndex(
            model_name='companylistitem',
            name='company_lis_adviser_913f84_idx',
        ),
    ]
