# Generated by Django 2.2.3 on 2019-08-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0007_make_item_adviser_nullable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companylist',
            name='disallow_is_legacy_default_false',
        ),
    ]
