# Generated by Django 2.2.4 on 2019-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0010_remove_list_item_adviser_from_database'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companylist',
            name='unique_adviser_if_legacy_default',
        ),
        migrations.AlterField(
            model_name='companylist',
            name='is_legacy_default',
            field=models.NullBooleanField(default=False),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='companylist',
                    name='is_legacy_default',
                ),
            ],
        ),
    ]
