# Generated by Django 2.2.4 on 2019-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0011_remove_is_legacy_default_from_django'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='companylist',
                    name='is_legacy_default',
                    field=models.NullBooleanField(default=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='companylist',
            name='is_legacy_default',
        ),
    ]
