# Generated by Django 3.0.5 on 2020-05-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0105_add_change_one_list_permissions'),
        ('metadata', '0002_add_iso_code_to_honduras'),
        ('company_list', '0014_auto_20200430_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineitem',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_items', to='company.Contact'),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='expected_win_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='likelihood_to_win',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='potential_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.BusinessType'),
        ),
    ]
