# Generated by Django 3.0.6 on 2020-05-19 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0002_add_iso_code_to_honduras'),
        ('company', '0105_add_change_one_list_permissions'),
        ('company_list', '0014_auto_20200430_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineitem',
            name='contact',
            field=models.ForeignKey(
                blank=True, help_text='Preferred company contact',
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='pipeline_items', to='company.Contact'
            ),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='expected_win_date',
            field=models.DateField(
                blank=True, help_text='Approximate expected date for this proposal to succeed',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='likelihood_to_win',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')],
                help_text='How likely the user thinks this proposal will result in success',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='potential_value',
            field=models.DecimalField(
                blank=True, null=True,
                help_text='Potential value (£) of the proposal',
                max_digits=19, decimal_places=0,
            ),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='sector',
            field=models.ForeignKey(
                blank=True, null=True,
                help_text='Sector in which the proposal is being worked on',
                on_delete=django.db.models.deletion.SET_NULL, to='metadata.Sector',
            ),
        ),
        migrations.AlterField(
            model_name='pipelineitem',
            name='adviser',
            field=models.ForeignKey(
                help_text='Owner of the pipeline item',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='pipelineitem',
            name='name',
            field=models.CharField(
                blank=True, null=True,
                help_text='Name to represent the item within the pipeline',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='pipelineitem',
            name='status',
            field=models.CharField(
                choices=[('leads', 'Leads'), ('in_progress', 'In progress'), ('win', 'Win')],
                help_text='Item status within the pipeline', max_length=255,
            ),
        ),
    ]
