# Generated by Django 3.0.6 on 2020-05-26 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_list', '0016_auto_20200519_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='archived_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineitem',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
