# Generated by Django 3.0.6 on 2020-06-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration file for adding multiple contacts for pipeline item."""

    dependencies = [
        ('company', '0105_add_change_one_list_permissions'),
        ('company_list', '0017_add_ArchivableModel_to_PipelineItem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineitem',
            name='contacts',
            field=models.ManyToManyField(
                blank=True, null=True,
                related_name='pipeline_items_m2m',
                to='company.Contact',
                help_text='Preferred company contacts',
            ),
        ),
    ]
