# Generated by Django 3.0.6 on 2020-07-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0019_copy_contact_to_contacts'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='pipelineitem',
                    name='contact',
                ),
            ],
        ),
    ]
