# Generated by Django 3.1.6 on 2021-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0107_remove_accepts_dit_email_marketing_from_django'),
        ('company_list', '0020_remove_pipelineitem_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineitem',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Preferred company contacts', related_name='pipeline_items_m2m', to='company.Contact'),
        ),
    ]
