# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_add_business_leads_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslead',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesslead',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
