# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_fix_blank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslead',
            name='address_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='businesslead',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesslead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_leads', to='company.Company'),
        ),
    ]
