# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_fix_blank_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesslead',
            old_name='advisor',
            new_name='adviser',
        ),
    ]
