# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_created_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslead',
            name='adviser',
        ),
    ]
