# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20170807_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesslead',
            old_name='contactable_by_dit_partners',
            new_name='contactable_by_uk_dit_partners',
        ),
        migrations.AddField(
            model_name='businesslead',
            name='accepts_dit_email_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesslead',
            name='contactable_by_overseas_dit_partners',
            field=models.BooleanField(default=False),
        ),
    ]
