# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20170807_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslead',
            options={'permissions': (('read_businesslead', 'Can read business lead'),)},
        ),
    ]
