# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_update_marketing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslead',
            options={'permissions': (('read_businesslead', 'Can read business lead'),)},
        ),
    ]
