# Generated by Django 2.1.2 on 2018-10-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_update_permissions_django_21'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslead',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='businesslead',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='businesslead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='businesslead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businesslead',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='BusinessLead',
        ),
    ]
