# Generated by Django 2.1 on 2018-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_update_permissions_django_21'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslead',
            name='contactable_by_dit',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesslead',
            name='contactable_by_email',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesslead',
            name='contactable_by_overseas_dit_partners',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesslead',
            name='contactable_by_phone',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesslead',
            name='contactable_by_uk_dit_partners',
            field=models.NullBooleanField(default=False),
        ),
    ]
