# Generated by Django 2.1.5 on 2019-02-11 16:35

from logging import getLogger

from django.db import migrations


PERMISSIONS_TO_DELETE = (
    'view_businesslead',
    'add_businesslead',
    'change_businesslead',
    'delete_businesslead',
)

logger = getLogger(__name__)


def delete_businesslead_permissions(apps, schema_editor):
    permission_model = apps.get_model('auth', 'Permission')

    _, deletions_by_model = permission_model.objects.filter(
        codename__in=PERMISSIONS_TO_DELETE,
        content_type__app_label='leads',
        content_type__model='businesslead',
    ).delete()

    logger.info(
        f'Deleted businesslead permissions, breakdown of deleted objects: {deletions_by_model}',
    )

def delete_businesslead_contenttype(apps, schema_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')

    _, deletions_by_model = content_type_model.objects.filter(
        app_label='leads',
        model='businesslead',
    ).delete()

    logger.info(
        f'Deleted businesslead content type, breakdown of deleted objects: {deletions_by_model}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_delete_businesslead'),
    ]

    operations = [
        migrations.RunPython(delete_businesslead_permissions, migrations.RunPython.noop, elidable=True),
        migrations.RunPython(delete_businesslead_contenttype, migrations.RunPython.noop, elidable=True),
    ]
