global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rq_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['rq_exporter:9726']
