# Generated by Django 2.1.7 on 2019-03-19 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='required_checks_conducted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='required_checks_conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
