# Generated by Django 4.2.15 on 2024-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0087_update_services'),
        ('investor_profile', '0001_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='asset_classes_of_interest',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.assetclassinterest'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='construction_risks',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.constructionrisk'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='deal_ticket_sizes',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.dealticketsize'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='desired_deal_roles',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.desireddealrole'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='investment_types',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.largecapitalinvestmenttype'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='other_countries_being_considered',
            field=models.ManyToManyField(blank=True, help_text='The other countries being considered for investment', related_name='+', to='metadata.country'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.restriction'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='time_horizons',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.timehorizon'),
        ),
        migrations.AlterField(
            model_name='largecapitalinvestorprofile',
            name='uk_region_locations',
            field=models.ManyToManyField(blank=True, related_name='+', to='metadata.ukregion', verbose_name='possible UK regions'),
        ),
    ]
