# Generated by Django 2.2 on 2019-04-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_profile', '0002_auto_20190319_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorprofile',
            options={'permissions': (('export_investorprofile', 'Can export investor profiles'),), 'verbose_name_plural': 'large capital profiles'},
        ),
    ]
