# Generated by Django 2.2 on 2019-05-12 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0025_update_sector_indexes'),
        ('investor_profile', '0003_auto_20190412_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeCapitalInvestorProfile',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('investable_capital', models.BigIntegerField(blank=True, help_text='Investable capital amount in USD', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('global_assets_under_management', models.BigIntegerField(blank=True, help_text='Global assets under management amount in USD', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('investor_description', models.TextField(blank=True)),
                ('required_checks_conducted_on', models.DateField(blank=True, null=True)),
                ('notes_on_locations', models.TextField(blank=True)),
                ('asset_classes_of_interest', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_asset_classes_of_interest_+', to='investor_profile.AssetClassInterest')),
                ('construction_risks', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_construction_risks_+', to='investor_profile.ConstructionRisk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal_ticket_sizes', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_deal_ticket_sizes_+', to='investor_profile.DealTicketSize')),
                ('desired_deal_roles', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_desired_deal_roles_+', to='investor_profile.DesiredDealRole')),
                ('investment_types', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_investment_types_+', to='investor_profile.LargeCapitalInvestmentType')),
                ('investor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profiles', to='company.Company')),
                ('investor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.InvestorType')),
                ('minimum_equity_percentage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.EquityPercentage')),
                ('minimum_return_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.ReturnRate')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('other_countries_being_considered', models.ManyToManyField(blank=True, help_text='The other countries being considered for investment', related_name='_largecapitalinvestorprofile_other_countries_being_considered_+', to='metadata.Country')),
                ('required_checks_conducted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.RequiredChecksConducted')),
                ('required_checks_conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restrictions', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_restrictions_+', to='investor_profile.Restriction')),
                ('time_horizons', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_time_horizons_+', to='investor_profile.TimeHorizon')),
                ('uk_region_locations', models.ManyToManyField(blank=True, related_name='_largecapitalinvestorprofile_uk_region_locations_+', to='metadata.UKRegion', verbose_name='possible UK regions')),
            ],
            options={
                'verbose_name_plural': 'large capital profiles',
                'permissions': (('export_largecapitalinvestorprofile', 'Can export large capital investor profiles'),),
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='InvestorProfile',
                ),
            ],
        ),
    ]
