# Generated by Django 2.2 on 2019-05-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_profile', '0004_auto_20190512_2123'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ProfileType',
                ),
            ],
        ),
    ]
