# Generated by Django 2.2.4 on 2019-09-06 16:13

from pathlib import PurePath

from django.db import migrations
from datahub.core.migration_utils import load_yaml_data_in_migration


def load_metadata(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / f'0006_fix_asset_class_spellings/asset_class_interest.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investor_profile', '0005_delete_profiletype'),
    ]

    operations = [
        migrations.RunPython(load_metadata, migrations.RunPython.noop)
    ]
