# Generated by Django 2.1.2 on 2018-11-15 10:52


from django.db import migrations


def rename_change_permission(apps, schema_editor):
    """
    Prior to Django 2.1 to view a model in the Django Admin a user needed
    'change' permission that also allowed record modification.

    Django 2.1 introduced 'view' permission that can be used to give user a
    permission only to view a model in the Django admin.

    This renames `change_spireport` permission to `view_spireport` as SPI Report
    record is not meant to be modified.
    """
    permission_model = apps.get_model('auth', 'Permission')

    permission_model.objects.filter(
        codename='change_spireport',
    ).update(
        codename='view_spireport',
        name='Can view SPI report',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spireport',
            options={
                'default_permissions': ('view',),
                'verbose_name': 'SPI report'
            },
        ),
        migrations.RunPython(rename_change_permission, elidable=True),
    ]
