# Generated by Django 2.1.4 on 2019-02-11 14:33

from pathlib import PurePath

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datahub.core.migration_utils import load_yaml_data_in_migration
import uuid


def load_profile_type_metadata(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / f'../fixtures/profile_type.yaml',
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0063_populate_company_address_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profiles', to='company.Company')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='investor_profile.ProfileType'),
        ),
        migrations.AlterUniqueTogether(
            name='investorprofile',
            unique_together={('investor_company', 'profile_type')},
        ),
        migrations.RunPython(load_profile_type_metadata, migrations.RunPython.noop),
    ]
