# Generated by Django 3.2.22 on 2023-10-24 14:43

from django.db import migrations, models
from pathlib import PurePath
import uuid

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_experience_categories(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0007_add_experience_categories.yaml'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0006_add_expected_value_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCategories',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
                ('export_win_id', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.RunPython(load_experience_categories, migrations.RunPython.noop),
    ]
