# Generated by Django 3.2.20 on 2023-10-30 10:53

from django.db import migrations, models
from pathlib import PurePath
import uuid


from datahub.core.migration_utils import load_yaml_data_in_migration


def load_hvc(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0015_add_hvc.yaml'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0014_add_associated_programmes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HVC',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
                ('export_win_id', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=4)),
                ('financial_year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('campaign_id', 'financial_year')},
                'abstract': False,
            },
        ),
        migrations.RunPython(load_hvc, migrations.RunPython.noop),
    ]
