# Generated by Django 3.2.23 on 2023-11-27 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0016_breakdown_customerresponse_win_winadviser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerResponseToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expires_on', models.DateTimeField()),
                ('customer_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='export_win.customerresponse')),
            ],
        ),
    ]
