# Generated by Django 3.2.23 on 2023-12-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0138_export_win_match_id'),
        ('export_win', '0017_customerresponsetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponsetoken',
            name='company_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='company.contact'),
        ),
        migrations.AddField(
            model_name='customerresponsetoken',
            name='email_delivery_status',
            field=models.CharField(blank=True, choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('permanent-failure', 'Permanent failure'), ('temporary-failure', 'Temporary failure'), ('technical-failure', 'Technical failure'), ('unknown', 'Unknown')], default='unknown', help_text='Email delivery status', max_length=255),
        ),
        migrations.AddField(
            model_name='customerresponsetoken',
            name='email_notification_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerresponsetoken',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
