# Generated by Django 3.2.23 on 2023-11-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0018_update_customerresponsetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='win',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_response', to='export_win.win'),
        ),
    ]
