# Generated by Django 3.2.23 on 2023-12-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0019_alter_customerresponse_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='company_contacts',
            field=models.ManyToManyField(blank=True, related_name='wins', to='company.Contact'),
        ),
        migrations.AddField(
            model_name='win',
            name='name_of_customer_confidential',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='win',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_export_wins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='win',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='win',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_manager_wins', to=settings.AUTH_USER_MODEL),
        ),        
    ]
