# Generated by Django 3.2.22 on 2024-01-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0020_alter_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponsetoken',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
