# Generated by Django 3.2.23 on 2024-01-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0022_rename_export_experience_win_export_wins_export_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='access_to_contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_to_contacts_customer_responses', to='export_win.rating', verbose_name='Gaining access to contacts?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='access_to_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_to_information_customer_responses', to='export_win.rating', verbose_name='Getting information or improved understanding of the country?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='case_study_willing',
            field=models.BooleanField(default=False, verbose_name='Would you be willing for DBT/Exporting is GREAT to feature your success in marketing materials?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='developed_relationships',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developed_relationships_customer_responses', to='export_win.rating', verbose_name='Developing or nurturing critical relationships?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='expected_portion_without_help',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_responses', to='export_win.withoutoursupport', verbose_name='What value do you estimate you would have achieved without our support?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='gained_confidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gained_confidence_customer_responses', to='export_win.rating', verbose_name='Having confidence to explore or expand in the country?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='improved_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='improved_profile_customer_responses', to='export_win.rating', verbose_name='Improving your profile or credibility in the country?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='involved_state_enterprise',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='The win involved a foreign government or state-owned enterprise (eg as an intermediary or facilitator)'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='last_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_responses', to='export_win.experience', verbose_name='Apart from this win, when did your company last export goods or services?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='marketing_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_responses', to='export_win.marketingsource', verbose_name='How did you first hear about DBT (or its predecessor, DIT)?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='our_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_support_customer_responses', to='export_win.rating', verbose_name='Securing the win overall?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='overcame_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overcame_problem_customer_responses', to='export_win.rating', verbose_name='Overcoming a problem in the country (eg legal, regulatory, commercial)?'),
        ),
    ]
