# Generated by Django 3.2.22 on 2023-10-25 10:09

from django.db import migrations, models
from pathlib import PurePath
import uuid


from datahub.core.migration_utils import load_yaml_data_in_migration


def load_rating(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0024_rename_rating.yaml'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0023_update_customerresponse'),
    ]

    operations = [
        migrations.RunPython(load_rating, migrations.RunPython.noop),
    ]
