# Generated by Django 3.2.23 on 2024-02-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0024_rename_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponse',
            name='lead_officer_email_delivery_status',
            field=models.CharField(blank=True, choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('permanent-failure', 'Permanent failure'), ('temporary-failure', 'Temporary failure'), ('technical-failure', 'Technical failure'), ('unknown', 'Unknown')], default='unknown', help_text='Email delivery status', max_length=255),
        ),
        migrations.AddField(
            model_name='customerresponse',
            name='lead_officer_email_notification_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerresponse',
            name='lead_officer_email_sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
