# Generated by Django 3.2.23 on 2024-02-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0139_auto_20231204_1601'),
        ('export_win', '0025_alter_customerreponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='company_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wins', to='company.companyexport', verbose_name='Related company export project'),
        ),
    ]
