# Generated by Django 3.2.23 on 2024-02-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0026_win_company_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyExportWinsToDataHubCompany',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_wins', to='company.company')),
            ],
        ),
    ]
