# Generated by Django 3.2.24 on 2024-02-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0027_legacyexportwinstodatahubcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponse',
            name='responded_on',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
