# Generated by Django 4.2 on 2024-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0028_customerresponse_responded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='win',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
