# Generated by Django 4.2.10 on 2024-03-19 13:44

from django.db import migrations, models

from datahub.export_win.constants import EXPORT_WINS_LEGACY_ID_START_VALUE


def populate_legacy_id(apps, schema_editor):
    WinAdviserModel = apps.get_model('export_win', 'WinAdviser')
    default_id = EXPORT_WINS_LEGACY_ID_START_VALUE
    for obj in WinAdviserModel.objects.all():
        obj.legacy_id = default_id
        obj.save()
        default_id = default_id + 1

def reverse_populate_legacy_id(apps, schema_editor):
    # No need to do anything, as the legacy_id column will be removed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0029_rename_marketing_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='winadviser',
            name='legacy_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.RunPython(populate_legacy_id, reverse_populate_legacy_id),
    ]
