# Generated by Django 4.2.10 on 2024-03-19 13:44
from functools import partial

from django.db import migrations, models

from datahub.export_win.legacy_id_utils import forwards_func

class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0029_rename_marketing_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='winadviser',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(partial(forwards_func, model='WinAdviser'), migrations.RunPython.noop),
    ]
