# Generated by Django 4.2 on 2024-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0029_win_is_deleted_win_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='win',
            name='updated',
        ),
        migrations.AlterField(
            model_name='win',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
