# Generated by Django 4.2.10 on 2024-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0029_rename_marketing_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
