# Generated by Django 4.2.10 on 2024-03-19 16:24
from functools import partial
from django.db import migrations, models

from datahub.export_win.legacy_id_utils import forwards_func, reverse_func


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0030_winadviser_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(partial(forwards_func, model='Breakdown'), reverse_func),
    ]
