# Generated by Django 4.2.10 on 2024-03-19 16:24
from functools import partial
from django.db import migrations, models

from datahub.export_win.constants import EXPORT_WINS_LEGACY_ID_START_VALUE


def forwards_func(apps, schema_editor, model):
    app_model = apps.get_model('export_win', model)
    default_id = EXPORT_WINS_LEGACY_ID_START_VALUE

    for obj in app_model.objects.all():
        obj.legacy_id = default_id
        obj.save()
        default_id = default_id + 1


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0030_winadviser_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(partial(forwards_func, model='Breakdown'), migrations.RunPython.noop),
    ]
