# Generated by Django 4.2.10 on 2024-03-20 13:40

from django.db import migrations, models
from pathlib import PurePath


from datahub.core.migration_utils import load_yaml_data_in_migration

def load_hvc(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0032_hvc_legacy_id.yaml'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0031_breakdown_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvc',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(load_hvc, migrations.RunPython.noop),
    ]
