# Generated by Django 4.2.10 on 2024-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0033_win_uk_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedWin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('export_win.win',),
        ),
        migrations.AddField(
            model_name='win',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
