# Generated by Django 4.2.10 on 2024-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0041_add_associated_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='case_study_willing',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Would you be willing for DBT/Exporting is GREAT to feature your success in marketing materials?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='company_was_at_risk_of_not_exporting',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="If you hadn't achieved this win, your company might have stopped exporting"),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_enabled_expansion_into_existing_market',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='It enabled you to maintain or expand in an existing market'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_enabled_expansion_into_new_market',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='It enabled you to expand into a new market'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_explicit_export_plans',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apart from this win, you already have specific plans to export in the next 12 months'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_increased_exports_as_percent_of_turnover',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='It enabled you to increase exports as a proportion of your turnover'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='interventions_were_prerequisite',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Our support was a prerequisite to generate this export value'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='support_improved_speed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Our support helped you achieve this win more quickly'),
        ),
    ]
