# Generated by Django 4.2.10 on 2024-05-14 11:19

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0042_alter_customerresponse_case_study_willing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='sector',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wins', to='metadata.sector'),
        ),
    ]
