# Generated by Django 4.2.11 on 2024-05-23 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0044_alter_win_hq_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
