# Generated by Django 4.2.11 on 2024-05-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0047_add_associated_programmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='involved_state_enterprise',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='The win involved a foreign government or state-owned enterprise (such as an intermediary or facilitator)'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='overcame_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overcame_problem_customer_responses', to='export_win.rating', verbose_name='Overcoming a problem in the country (such as legal, regulatory, commercial)?'),
        ),
    ]
