# Generated by Django 4.2.11 on 2024-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0049_add_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousWin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('export_win.win',),
        ),
        migrations.AddField(
            model_name='win',
            name='is_anonymous_win',
            field=models.BooleanField(default=False),
        ),
    ]
