# Generated by Django 4.2.11 on 2024-07-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0050_legacyexportwinstodatahubadminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponsetoken',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerresponsetoken',
            name='legacy_recipient',
            field=models.CharField(blank=True, max_length=256, verbose_name='Legacy recipient'),
        ),
    ]
