# Generated by Django 4.2.11 on 2024-06-18 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('export_win', '0050_anonymouswin_win_is_anonymous_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponsetoken',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
