# Generated by Django 4.2.11 on 2024-06-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0050_legacyexportwinstodatahubadminuser'),
        ('export_win', '0051_customerresponsetoken_adviser'),
    ]

    operations = [
    ]
