# Generated by Django 4.2.10 on 2024-03-20 13:40

from django.db import migrations, models
from pathlib import PurePath


from datahub.core.migration_utils import load_yaml_data_in_migration

def load_export_experience(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0056_update_export_experience.yaml'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0055_customerresponsetoken_adviser'),
        ('company', '0144_update_company_export_experience'),
    ]

    operations = [
        migrations.RunPython(load_export_experience, migrations.RunPython.noop),
    ]
