# Generated by Django 4.2.17 on 2025-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0056_update_export_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='agree_with_win',
            field=models.BooleanField(db_index=True, null=True, verbose_name='Please confirm these details are correct'),
        ),
    ]
