# Generated by Django 4.2.20 on 2025-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_win', '0060_update_associated_programmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='lead_officer_name',
            field=models.CharField(max_length=128, verbose_name='Lead officer name'),
        ),
    ]
