# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

import mptt
import mptt.fields
import mptt.managers


def rebuild_category_mptt(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    Company = apps.get_model('company', 'Company')
    manager.model = Company
    mptt.register(Company, order_insertion_by=['name'])
    manager.contribute_to_class(Company, 'objects')
    manager.rebuild()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_squash_0030_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='company.Company'),
        ),
        migrations.RunPython(rebuild_category_mptt, noop_reverse),
    ]
