# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 08:42
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='dit_team',
            field=models.ForeignKey(default='0167b456-0ddd-49bd-8184-e3227a0b6396', on_delete=django.db.models.deletion.CASCADE, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='username',
            field=models.CharField(blank=True, max_length=255, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='companieshousecompany',
            name='registered_address_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_companieshousecompany_related', related_query_name='(app_label)s_companieshousecompanys', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.BusinessType'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.EmployeeRange'),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_to_countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_export_to_countries', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='future_interest_countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_future_interest_countries', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_company_related', related_query_name='(app_label)s_companys', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_address_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_trading_address_country', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='turnover_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.TurnoverRange'),
        ),
        migrations.AlterField(
            model_name='company',
            name='uk_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.UKRegion'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Role'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='teams',
            field=models.ManyToManyField(blank=True, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Title'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dit_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Team'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.InteractionType'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Service'),
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='EmployeeRange',
        ),
        migrations.DeleteModel(
            name='InteractionType',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='TurnoverRange',
        ),
        migrations.DeleteModel(
            name='UKRegion',
        ),
    ]
