# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20161024_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_to_countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_export_to_countries', to='company.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='future_interest_countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_future_interest_countries', to='company.Country'),
        ),
    ]
