# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20161024_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
