# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('company', '0003_auto_20161125_0332'), ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={}, ),
        migrations.RemoveField(
            model_name='advisor',
            name='username', ),
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.EmailField(max_length=255, unique=True), ),
    ]
