# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_fix_blank_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='advisor',
            new_name='adviser',
        ),
    ]
