# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_lead'),
        ('company', '0004_rename_advsor_fkeys_to_adviser'),
    ]

    operations = [
    ]
