# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20161129_0556'),
        ('company', '0004_auto_20161129_0423'),
    ]

    operations = []
