# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 09:50
from __future__ import unicode_literals

import datahub.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20161129_0423'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advisor',
            managers=[
                ('objects', datahub.company.models.AdvisorManager()),
            ],
        ),
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
