# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_lead_address_3_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='enabled',
            new_name='use_cdms_auth',
        ),
    ]
