# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

import mptt
import mptt.fields
import mptt.managers


def rebuild_category_mptt(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    Company = apps.get_model('company', 'Company')
    manager.model = Company
    mptt.register(Company, order_insertion_by=['name'])
    manager.contribute_to_class(Company, 'objects')
    manager.rebuild()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_reanme_enabled_to_use_cdms_auth'),
    ]

    operations = [
        migrations.RunPython(noop, rebuild_category_mptt),
        migrations.RemoveField(
            model_name='company',
            name='level',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='company.Company'),
        ),
    ]
