# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('company', '0006_auto_20161130_0507'),]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='date_joined',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
