# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20161103_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.EmailField(default='fake@no-email-address-supplied.com', max_length=254),
            preserve_default=False,
        ),
    ]
