# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_advisor_email'),
        ('company', '0007_auto_20161103_1103'),
    ]

    operations = [
    ]
