# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20161201_0527'),
        ('company', '0005_merge_20161129_0926'),
    ]

    operations = []
