# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_mptt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advisor',
            index=models.Index(fields=['first_name', 'last_name'], name='company_adv_first_n_61a74f_idx'),
        ),
    ]
