# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_add_adviser_name_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'permissions': (('view_adviser', 'Can View Adviser'),), 'verbose_name': 'adviser'},
        ),
        migrations.AlterModelOptions(
            name='companieshousecompany',
            options={'permissions': (('view_companieshousecompany', 'Can View Companies House Company'),), 'verbose_name_plural': 'Companies House companies'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_company', 'Can View Company'),), 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': (('view_contact', 'Can View Contact'),)},
        ),
    ]
