# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_merge_20161207_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(default='0167b456-0ddd-49bd-8184-e3227a0b6396', on_delete=django.db.models.deletion.CASCADE, to='metadata.InteractionType'),
            preserve_default=False,
        ),
    ]
