# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('company', '0009_auto_20161214_0343'),]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='metadata.Title'),),
    ]
