# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20161108_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lead',
            field=models.BooleanField(default=False),
        ),
    ]
