# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_created_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'permissions': (('view_advisor', 'Can view adviser'),), 'verbose_name': 'adviser'},
        ),
        migrations.AlterModelOptions(
            name='companieshousecompany',
            options={'permissions': (('view_companieshousecompany', 'Can view companies house company'),), 'verbose_name': 'Companies House company', 'verbose_name_plural': 'Companies House companies'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_company', 'Can view company'),), 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': (('view_contact', 'Can view contact'),)},
        ),
    ]
