# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_created_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='primary',
            field=models.NullBooleanField(),
        ),
    ]
