# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Advisor'),
        ),
    ]
