# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170113_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(max_length=4000),
        ),
    ]
