# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170113_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='dit_advisor',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='dit_team',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='interaction_type',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='service',
        ),
        migrations.AddField(
            model_name='companieshousecompany',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companieshousecompany',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companieshousecompany',
            name='registered_address_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companieshousecompanys', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='metadata.Country'),
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
