# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170113_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='dit_advisor',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='dit_team',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='interaction_type',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='service',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
