# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_add_adviser_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactable_by_dit_partners',
            new_name='contactable_by_uk_dit_partners',
        ),
        migrations.AddField(
            model_name='contact',
            name='accepts_dit_email_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='contactable_by_overseas_dit_partners',
            field=models.BooleanField(default=False),
        ),
    ]
