# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20170201_1458'),
        # ('interaction', '0001_initial')  # Commented out to avoid cyclic dependencies, will be removed shortly
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='date_of_interaction',
            new_name='date'
        ),
        migrations.RunSQL(
            sql='INSERT INTO interaction_interaction ('
                    'id, archived, archived_by_id, archived_reason, archived_on, modified_on, created_on,'
                    'interaction_type_id, subject, "date", dit_advisor_id, notes, company_id, contact_id, service_id, dit_team_id'
                ') SELECT '
                    'id, archived, archived_by_id, archived_reason, archived_on, modified_on, created_on,'
                    'interaction_type_id, subject, "date", dit_advisor_id, notes, company_id, contact_id, service_id, dit_team_id'
                ' FROM company_interaction',
            reverse_sql='INSERT INTO company_interaction ('
                    'id, archived, archived_by_id, archived_reason, archived_on, modified_on, created_on,'
                    'interaction_type_id, subject, "date", dit_advisor_id, notes, company_id, contact_id, service_id, dit_team_id'
                ') SELECT '
                    'id, archived, archived_by_id, archived_reason, archived_on, modified_on, created_on,'
                    'interaction_type_id, subject, "date", dit_advisor_id, notes, company_id, contact_id, service_id, dit_team_id'
                ' FROM interaction_interaction',
            elidable=True,
        )
    ]
