# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20170203_1222'),
        ('company', '0014_auto_20170201_1601'),
    ]

    operations = [
    ]
