# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_add_vat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportExperienceCategory',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='export_experience_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.ExportExperienceCategory'),
        ),
    ]
