# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_merge_20170206_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companieshousecompany',
            options={'verbose_name_plural': 'Companies House companies'},
        ),
    ]
