# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_add_export_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
