# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:28
from __future__ import unicode_literals

import datahub.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20170216_1153'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS citext;',
            reverse_sql=migrations.RunSQL.noop,
            elidable=True
        ),
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=datahub.core.fields.CICharField(max_length=255, unique=True),
        ),
    ]
