# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20170222_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
