# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_add_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='archived_documents_url_path',
            field=models.CharField(blank=True, help_text='Legacy field. File browser path to the archived documents for this company.', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_documents_url_path',
            field=models.CharField(blank=True, help_text='Legacy field. File browser path to the archived documents for this contact.', max_length=255),
        ),
    ]
