# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def enable_users(apps, schema_editor):
    """Enable the users already enabled in the env var."""
    Advisor = apps.get_model("company", "Advisor")
    Advisor.objects.filter(email__in=settings.DIT_ENABLED_ADVISORS).update(enabled=True)


def disable_users(apps, schema_editor):
    """Disable all the users."""
    Advisor = apps.get_model("company", "Advisor")
    Advisor.objects.all().update(enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_advisor_enabled'),
    ]

    operations = [
        migrations.RunPython(enable_users, reverse_code=disable_users)
    ]
