# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.functions import Concat


def correct_website_urls(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    Company.objects.exclude(
        website__contains='://'
    ).update(
        website=Concat(models.Value('http://'), 'website')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_add_archived_documents_url_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(correct_website_urls, migrations.RunPython.noop, elidable=True),
    ]
