# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_advisor_enabled'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop)
    ]
