# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_headquartertype'),
        ('company', '0019_auto_20170227_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarter_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.HeadquarterType'),
        ),
    ]
