# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:53
from __future__ import unicode_literals

from django.db import migrations


def correct_website_urls(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    Company.objects.filter(
        website='http://'
    ).update(
        website=''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_use_urlfield_for_website'),
    ]

    operations = [
        migrations.RunPython(correct_website_urls, migrations.RunPython.noop, elidable=True),
    ]
