# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_companyclassification'),
        ('company', '0020_company_headquarter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.CompanyClassification'),
        ),
        migrations.AlterField(
            model_name='company',
            name='headquarter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.HeadquarterType'),
        ),
    ]
