# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20171116_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportexperiencecategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
