# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20170329_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactable_by_dit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='contactable_by_dit_partners',
            field=models.BooleanField(default=False),
        ),
    ]
