# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20170329_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactable_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contactable_by_phone',
            field=models.BooleanField(default=True),
        ),
    ]
