# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 08:14
from __future__ import unicode_literals

from django.db import migrations


def delete_all_ch_companies(apps, schema_editor):
    CHCompany = apps.get_model('company', 'CompaniesHouseCompany')
    db_alias = schema_editor.connection.alias
    CHCompany.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20170329_1049'),
    ]

    operations = [
        migrations.RunPython(
            delete_all_ch_companies,
            reverse_code=migrations.RunPython.noop
        )
    ]
