# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 09:29
from __future__ import unicode_literals

from django.db import migrations


def update_superuser_status(apps, schema_editor):
    Advisor = apps.get_model('company', 'Advisor')
    Advisor.objects.filter(is_superuser=True, is_staff=False).update(is_superuser=False)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_fix_export_experience_cat_verbose_name'),
    ]

    operations = [
        migrations.RunPython(update_superuser_status, migrations.RunPython.noop, elidable=True)
    ]
