# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20170418_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactable_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contactable_by_phone',
            field=models.BooleanField(default=True),
        ),
    ]
