# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20170419_0918'),
        ('company', '0023_auto_20170418_1047'),
    ]

    operations = [
    ]
