# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20170406_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companieshousecompany',
            name='id',
        ),
        migrations.AlterField(
            model_name='companieshousecompany',
            name='company_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
