# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_update_superuser_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={
                'permissions': (
                    ('read_company', 'Can read company'),
                    ('read_company_document', 'Can read company document'),
                ),
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={
                'permissions': (
                    ('read_contact', 'Can read contact'),
                    ('read_contact_document', 'Can read contact document'),
                ),
            },
        ),
    ]
