# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20170419_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='export_to_countries',
            field=models.ManyToManyField(blank=True, related_name='company_export_to_countries', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='future_interest_countries',
            field=models.ManyToManyField(blank=True, related_name='company_future_interest_countries', to='metadata.Country'),
        ),
    ]
