# Generated by Django 2.0.2 on 2018-02-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_add_custom_document_read_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='global_headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='company.Company'),
        ),
    ]
