# Generated by Django 2.0.1 on 2018-01-03 10:21

from uuid import UUID


from django.db import migrations


uk_establishment = UUID('b0730fc6-fcce-4071-bdab-ba8de4f4fc98')


def add_uk_establishment_business_type(apps, schema_editor):
    BusinessType = apps.get_model('metadata', 'BusinessType')
    BusinessType.objects.create(
        id=uk_establishment,
        name='UK branch of foreign company (BR)'
    )


def remove_uk_establishment_business_type(apps, schema_editor):
    BusinessType = apps.get_model('metadata', 'BusinessType')
    BusinessType.objects.filter(
        id=uk_establishment,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_add_custom_document_read_permission'),
    ]

    operations = [
        migrations.RunPython(
            add_uk_establishment_business_type, remove_uk_establishment_business_type
        )
    ]
