# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20170419_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Deselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
