# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20170502_1331'),
        ('company', '0025_auto_20170428_1421'),
    ]

    operations = [
    ]
