# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20170502_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='dit_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Team'),
        ),
    ]
