# Generated by Django 2.0.3 on 2018-03-12 11:05

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_company_global_headquarters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Sector'),
        ),
    ]
