# Generated by Django 2.0.4 on 2018-05-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_add_sector_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('read_company', 'Can read company'), ('read_company_document', 'Can read company document'), ('read_company_timeline', 'Can read company timeline')), 'verbose_name_plural': 'companies'},
        ),
    ]
