# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_merge_20170503_0918'),
        ('company', '0026_auto_20170503_1410'),
    ]

    operations = [
    ]
