# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20170511_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='teams',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.Company'),
        ),
    ]
