# Generated by Django 2.0.8 on 2018-08-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_core-team'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='parent',
                ),
            ],
        ),
    ]
