# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_fix_created_on_modified_on'),
        ('company', '0029_auto_20170522_1619'),
    ]

    operations = [
    ]
