# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_merge_20170523_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='advisor',
            new_name='adviser',
        ),
    ]
