# Generated by Django 2.0.8 on 2018-08-24 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("company", "0031_remove-parent-column")]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="contact", name="contactable_by_dit"
                ),
                migrations.RemoveField(
                    model_name="contact", name="contactable_by_email"
                ),
                migrations.RemoveField(
                    model_name="contact", name="contactable_by_overseas_dit_partners"
                ),
                migrations.RemoveField(
                    model_name="contact", name="contactable_by_phone"
                ),
                migrations.RemoveField(
                    model_name="contact", name="contactable_by_uk_dit_partners"
                ),
            ]
        )
    ]
