# Generated by Django 2.1 on 2018-08-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_add_export_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': (('view_contact_document', 'Can view contact document'), ('export_contact', 'Can export contact'))},
        ),
    ]
