# Generated by Django 2.1 on 2018-08-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_add_export_permission'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='account_manager',
                ),
            ],
        ),
    ]
