# Generated by Django 2.1 on 2018-09-21 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_remove-account-manager-from-django'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='company',
                    name='account_manager',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='account_manager',
        ),
    ]
