# Generated by Django 2.1.2 on 2018-10-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_add_index_contact_email_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='use_cdms_auth',
            field=models.NullBooleanField(default=False, help_text='No longer used'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='advisor',
                    name='use_cdms_auth',
                ),
            ],
        ),
    ]
