# Generated by Django 2.1.2 on 2018-11-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_add_transfer_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='advisor',
                    name='use_cdms_auth',
                    field=models.NullBooleanField(default=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='use_cdms_auth',
        ),
    ]
