# Generated by Django 2.1.3 on 2018-11-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_remove_cdms_auth_from_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyCoreTeamMember',
            new_name='OneListCoreTeamMember',
        ),
    ]
