# Generated by Django 2.1.3 on 2018-11-23 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_rename_to_one_list_core_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onelistcoreteammember',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_list_core_team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onelistcoreteammember',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_list_core_team_members', to='company.Company'),
        ),
    ]
