# Generated by Django 2.1.3 on 2018-11-27 11:52

from django.db import migrations


def populate_one_list_tier(apps, schema_editor):
    OneListTier = apps.get_model('company', 'OneListTier')
    CompanyClassification = apps.get_model('metadata', 'CompanyClassification')

    classifications = CompanyClassification.objects.filter(disabled_on__isnull=True)
    for classification in classifications:
        OneListTier.objects.get_or_create(
            id=classification.id,
            defaults={
                'name': classification.name,
                'order': classification.order,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_add_one_list_tier'),
        ('metadata', '0010_auto_20180613_1553'),
    ]

    operations = [
        migrations.RunPython(populate_one_list_tier, migrations.RunPython.noop),
    ]
