# Generated by Django 2.1.3 on 2018-11-28 17:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_populate_one_list_tier'),
    ]

    # The duns_number definition in the migration 0044 was changed from NOT NULL to NULL
    # after it was processed in some environments.
    # This SQL query makes sure that the resulting column is NULL for environemtns
    # that processed the first version of that migration.
    operations = [
        migrations.RunSQL(
            'ALTER TABLE "company_company" ALTER COLUMN "duns_number" DROP NOT NULL',
            migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
