# Generated by Django 2.1.3 on 2018-11-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_duns_number_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='one_list_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.OneListTier'),
        ),
        migrations.AlterField(
            model_name='company',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='Deprecated - Please use One List tier field instead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.CompanyClassification'),
        ),
    ]
