# Generated by Django 2.1.3 on 2018-11-27 14:47

from django.db import migrations
from django.db.models import F


def populate_one_list_tier_field(apps, schema_editor):
    Company = apps.get_model('company', 'Company')

    companies = Company.objects.filter(classification__isnull=False)
    companies.update(one_list_tier_id=F('classification_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_one_list_tier_field'),
    ]

    operations = [
        migrations.RunPython(
            populate_one_list_tier_field,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
