# Generated by Django 2.1.3 on 2018-12-10 12:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_duns_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trading_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
