# Generated by Django 2.1.3 on 2018-12-10 14:36

from django.db import migrations, models
from django.db.models import F, Q
from django.db.models.expressions import RawSQL


def populate_trading_names(apps, schema_editor):
    Company = apps.get_model('company', 'Company')

    companies = Company.objects.exclude(Q(alias__isnull=True) | Q(alias=''))
    companies.update(
        trading_names=RawSQL('ARRAY[alias]', params=[]),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_add_trading_names'),
    ]

    operations = [
        migrations.RunPython(
            populate_trading_names,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
