# Generated by Django 2.1.3 on 2018-12-13 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0053_populate_trading_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trading_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='It will eventually replace alias. If you change this please change alias (trading name) as well.', null=True, size=None),
        ),
    ]
