# Generated by Django 2.1.3 on 2018-12-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0055_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_number_of_employees_estimated',
            field=models.BooleanField(blank=True, help_text='Only used when duns_number is set.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, help_text='Only used when duns_number is set.', null=True),
        ),
    ]
