# Generated by Django 2.1.3 on 2019-01-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_squashed_0056_number_of_employees'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='classification',
                ),
            ],
        ),
    ]
