# Generated by Django 2.1.3 on 2019-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_remove_classification_from_django'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='company',
                    name='classification',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        to='metadata.CompanyClassification'
                    )
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='classification',
        ),
    ]
