# Generated by Django 2.1.5 on 2019-01-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0058_remove_classification_from_database'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='alias',
                ),
            ],
        ),
    ]
