# Generated by Django 2.1.5 on 2019-01-17 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_remove_alias_from_django'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trading_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
