# Generated by Django 2.1.5 on 2019-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_trading_names_not_null'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='company',
                    name='alias',
                    field=models.CharField(
                        blank=True,
                        help_text='Trading name.',
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='alias',
        ),
    ]
