# Generated by Django 2.1.5 on 2019-01-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0021_delete_companyclassification'),
        ('company', '0061_remove_alias_from_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies_with_country_address', to='metadata.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address_town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
