# Generated by Django 2.1.5 on 2019-02-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0063_populate_company_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address_town',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
