# Generated by Django 2.1.5 on 2019-02-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_ch_registered_address_2_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieshousecompany',
            name='registered_address_country',
            field=models.ForeignKey(default='80756b9a-5d95-e211-a939-e4115bead28a', on_delete=django.db.models.deletion.PROTECT, related_name='companieshousecompanies_with_country_registered_address', to='metadata.Country'),
            preserve_default=False,
        ),
    ]
