# Generated by Django 2.2 on 2019-04-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0070_make_registered_address_county_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_address_postcode',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
