# Generated by Django 2.2 on 2019-04-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0072_make_address_1_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
