# Generated by Django 2.2 on 2019-04-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0081_make_trading_address_postcode_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_address_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_with_country_registered_address', to='metadata.Country'),
        ),
    ]
