# Generated by Django 2.2 on 2019-05-08 15:09

from django.conf import settings
from django.db import migrations
from django.db import models

MAX_LENGTH = settings.CHAR_FIELD_MAX_LENGTH


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0083_add_email_alternative_upper_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trading_address_1',
            field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_address_2',
            field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_address_county',
            field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_address_postcode',
            field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_address_town',
            field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='trading_address_1',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='trading_address_2',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='trading_address_country',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='trading_address_county',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='trading_address_postcode',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='trading_address_town',
                ),
            ]
        )
    ]
