# Generated by Django 2.2.1 on 2019-05-13 08:37

from django.db import migrations, models

# The value of settings.CHAR_FIELD_MAX_LENGTH at migration time
MAX_LENGTH = 255

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0084_remove_trading_address_from_django'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='company',
                    name='trading_address_1',
                    field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='trading_address_2',
                    field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='trading_address_town',
                    field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='trading_address_county',
                    field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='trading_address_postcode',
                    field=models.CharField(max_length=MAX_LENGTH, blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='trading_address_country',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        to='metadata.Country',
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='trading_address_1'
        ),
        migrations.RemoveField(
            model_name='company',
            name='trading_address_2'
        ),
        migrations.RemoveField(
            model_name='company',
            name='trading_address_town'
        ),
        migrations.RemoveField(
            model_name='company',
            name='trading_address_county'
        ),
        migrations.RemoveField(
            model_name='company',
            name='trading_address_postcode'
        ),
        migrations.RemoveField(
            model_name='company',
            name='trading_address_country'
        ),
    ]
