# Generated by Django 2.2.4 on 2019-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0037_add_service_hierarchy'),
        ('company', '0086_add_adviser_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='disregarded_future_interest_countries',
            field=models.ManyToManyField(blank=True, help_text='These countries of interest are to be disregarded even if present in imputed_future_interest_countries', related_name='companies_with_disregarded_future_interest', to='metadata.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='imputed_future_interest_countries',
            field=models.ManyToManyField(blank=True, help_text='These countries of interest come from external data sources', related_name='companies_with_imputed_future_interest', to='metadata.Country'),
        ),
    ]
