# Generated by Django 2.2.3 on 2019-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0086_add_adviser_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pending_dnb_investigation',
            field=models.BooleanField(blank=True, help_text='Whether this company is to be investigated by DNB.', null=True),
        ),
    ]
