# Generated by Django 2.2.3 on 2019-08-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0087_add_company_pending_dnb_investigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pending_dnb_investigation',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this company is to be investigated by DNB.', null=True),
        ),
    ]
