# Generated by Django 2.2.3 on 2019-08-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0088_make_company_pending_dnb_investigation_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pending_dnb_investigation',
            field=models.BooleanField(default=False, help_text='Whether this company is to be investigated by DNB.'),
        ),
    ]
