# Generated by Django 2.2.3 on 2019-09-09 08:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0089_make_pending_dnb_investigation_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dnb_investigation_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
