# Generated by Django 2.2.4 on 2019-09-13 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0038_remove_service_name_from_db'),
        ('company', '0090_add_company_dnb_investigation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='future_interest_countries',
            field=models.ManyToManyField(blank=True, help_text='This field is now deprecated. Use the get_active_countries_of_interest method.', related_name='companies_with_future_interest', to='metadata.Country'),
        ),
        migrations.CreateModel(
            name='CompanyCountryOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('user', 'User entered'), ('external', 'External')], max_length=16)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_countries_of_interest', to='company.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_with_interest', to='metadata.Country')),
            ],
            options={
                'unique_together': {('country', 'company', 'source')},
            },
        ),
        migrations.AlterModelOptions(
            name='companycountryofinterest',
            options={'verbose_name_plural': 'Company Countries of Interest'},
        ),
    ]
