# Generated by Django 2.2.5 on 2019-09-24 09:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0038_remove_service_name_from_db'),
        ('company', '0090_add_company_dnb_investigation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='future_interest_countries',
            field=models.ManyToManyField(blank=True, help_text='This field is now deprecated. Use the get_active_export_countries method.', related_name='companies_with_future_interest', to='metadata.Country'),
        ),
        migrations.CreateModel(
            name='CompanyExportCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('user', 'User entered'), ('external', 'External')], max_length=16), size=None)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unfiltered_export_countries', to='company.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_with_interest', to='metadata.Country')),
            ],
            options={
                'verbose_name_plural': 'company export countries',
            },
        ),
        migrations.AddConstraint(
            model_name='companyexportcountry',
            constraint=models.UniqueConstraint(fields=('country', 'company'), name='unique_country_company'),
        ),
    ]
