# Generated by Django 2.2.5 on 2019-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0092_auto_20191001_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='export_potential',
            field=models.CharField(blank=True, choices=[('very_high', 'Very High'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('very_low', 'Very Low')], help_text='Score that signifies export potential, imported from Data Science', max_length=255, null=True),
        ),
    ]
