# Generated by Django 2.2.5 on 2019-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0091_add_composite_index_to_contact'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_on', 'id'], name='company_com_created_a7054b_idx'),
        ),
    ]
