# Generated by Django 2.2.5 on 2019-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0091_add_composite_index_to_contact'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='company_con_created_dbaf20_idx',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['id', 'created_on'], name='company_con_id_d1e29b_idx'),
        ),
    ]
