# Generated by Django 2.2.5 on 2019-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0092_company_export_potential'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='great_profile_status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), (None, 'No profile or not known')], help_text='Whether this company has a profile and agreed to be published or not', max_length=255, null=True),
        ),
    ]
