# Generated by Django 2.2.5 on 2019-10-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0093_update_one_list_tiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_company_document', 'Can view company document'), ('view_company_timeline', 'Can view company timeline'), ('export_company', 'Can export company'), ('change_regional_account_manager', 'Can change regional account manager')), 'verbose_name_plural': 'companies'},
        ),
    ]
