# Generated by Django 2.2.5 on 2019-10-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0092_auto_20191001_1520'),
        ('company', '0093_company_great_profile'),
    ]

    operations = [
    ]
