# Generated by Django 2.2.5 on 2019-10-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0094_add_change_regional_account_manager_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='great_profile_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('published', 'Published'),
                    ('unpublished', 'Unpublished'),
                    (None, 'No profile or not known')
                ],
                help_text='Whether this company has a profile and agreed to be published or not',
                max_length=255,
                null=True,
            ),
        ),
    ]
