# Generated by Django 2.2.5 on 2019-10-04 11:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0094_add_change_regional_account_manager_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='future_interest_countries',
            field=models.ManyToManyField(blank=True, help_text='This field is now deprecated. Use the get_active_future_export_countries method.', related_name='companies_with_future_interest', to='metadata.Country'),
        ),
        migrations.CreateModel(
            name='CompanyExportCountry',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('user', 'User entered'), ('external', 'External')], max_length=255), size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unfiltered_export_countries', to='company.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_with_interest', to='metadata.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'company export countries',
            },
        ),
        migrations.AddConstraint(
            model_name='companyexportcountry',
            constraint=models.UniqueConstraint(fields=('country', 'company'), name='unique_country_company'),
        ),
    ]
