# Generated by Django 2.2.3 on 2019-10-21 09:52

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0095_company_great_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='global_ultimate_duns_number',
            field=models.CharField(blank=True, db_index=True, help_text='Dun & Bradstreet unique identifier for global ultimate.', max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
    ]
