# Generated by Django 2.2.6 on 2019-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0096_company_global_ultimate_duns_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advisor',
            index=models.Index(fields=['date_joined', 'id'], name='company_adv_date_jo_c2b29e_idx'),
        ),
    ]
