# Generated by Django 2.2.3 on 2019-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0097_add_adviser_date_pk_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dnb_modified_on',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last updated from D&B', null=True),
        ),
    ]
