# Generated by Django 2.2.7 on 2019-11-21 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0010_auto_20180613_1553'),
        ('company', '0099_delete_companieshousecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExportCountry',
            fields=[
                (
                    'created_on',
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True)
                ),
                (
                    'modified_on',
                    models.DateTimeField(auto_now=True, null=True)
                ),
                (
                    'id',
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_interested', 'Not interested'),
                            ('currently_exporting', 'Currently exporting to'),
                            ('future_interest', 'Future country of interest')
                        ],
                        max_length=255
                    )
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='export_countries',
                        to='company.Company'
                    )
                ),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='companies_with_interest',
                        to='metadata.Country'
                    )
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
                (
                    'modified_by', 
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'verbose_name_plural': 'company export countries',
            },
        ),
        migrations.AddConstraint(
            model_name='companyexportcountry',
            constraint=models.UniqueConstraint(
                fields=('country', 'company'), 
                name='unique_country_company'
            ),
        ),
    ]
