# Generated by Django 3.0.4 on 2020-03-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0102_auto_20200305_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='sso_email_user_id',
            field=models.EmailField(blank=True, help_text='This is the `Email user ID` that is shown for this user in Staff SSO.', max_length=254, null=True, unique=True, verbose_name='SSO email user ID'),
        ),
    ]
