# Generated by Django 3.0.3 on 2020-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0103_add_sso_email_user_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dnb_investigation_id',
            field=models.UUIDField(blank=True, help_text='The ID for a new company investigation with D&B. This ID is provided by dnb-service.', null=True, unique=True),
        ),
    ]
