# Generated by Django 3.0.5 on 2020-05-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0104_company_dnb_investigation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_company_document', 'Can view company document'), ('view_company_timeline', 'Can view company timeline'), ('export_company', 'Can export company'), ('change_regional_account_manager', 'Can change regional account manager'), ('change_one_list_tier_and_global_account_manager', 'Can change one list tier and global account manager'), ('change_one_list_core_team_member', 'Can change one list core team member associated with company'), ('view_export_win', 'Can view company export win')), 'verbose_name_plural': 'companies'},
        ),
    ]
