# Generated by Django 3.0.5 on 2020-06-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0105_add_change_one_list_permissions'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='dnb_investigation_data',
                ),
            ]
        ),
    ]
