# Generated by Django 3.0.8 on 2020-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0106_remove_company_dnb_investigation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='accepts_dit_email_marketing',
            field=models.NullBooleanField(default=False),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='contact',
                    name='accepts_dit_email_marketing',
                ),
            ],
        ),
    ]
