# Generated by Django 3.1.6 on 2021-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0107_remove_accepts_dit_email_marketing_from_django'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address_state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
