# Generated by Django 3.1.7 on 2021-03-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_update_services'),
        ('company', '0107_remove_accepts_dit_email_marketing_from_django'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_with_address_area', to='metadata.administrativearea'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_with_registered_address_area', to='metadata.administrativearea'),
        ),
    ]
