# Generated by Django 3.1.6 on 2021-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0108_create_company_state_base_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['address_state'], name='company_state_1911_idx'),
        ),
    ]
