# Generated by Django 3.1.7 on 2021-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0108_create_company_state_fk_base_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='segment',
            field=models.CharField(blank=True, choices=[(None, 'No segment or not known'), ('hep', 'Hep'), ('non-hep', 'Non-Hep')], help_text='TODO: Get from Cathy', max_length=255, null=True),
        ),
    ]
