# Generated by Django 3.1.7 on 2021-03-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0108_create_company_state_fk_base_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='export_segment',
            field=models.CharField(choices=[(None, 'No Export Segment or not known'), ('hep', ' High Export Potential'), ('non-hep', 'Non- High Export Potential')], default='', help_text='Segmentation of export', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='export_sub_segment',
            field=models.CharField(choices=[(None, 'No Sub-Export Segment or not known'), ('sustain_nurture_and_grow', 'Sustain: Nurture & Grow'), ('sustain_develop_export_capability', 'Sustain: Develop Export Capability'), ('sustain_communicate_benefits', 'Sustain: Communicate Benefits'), ('sustain_increase_competitiveness', 'Sustain: Increase Competitiveness'), ('reassure_nurture_and_grow', 'Reassure: Nurture & Grow'), ('reassure_develop_export_capability', 'Reassure: Develop Export Capability'), ('reassure_leave_be', 'Reassure: Leave Be'), ('reassure_change_the_game', 'Reassure: Change the Game'), ('promote_develop_export_capability', 'Promote: Develop Export Capability'), ('promote_communicate_benefits', 'Promote: Communicate Benefits'), ('promote_change_the_game', 'Promote: Change the Game'), ('challenge', 'Challenge')], default='', help_text='Sub-Segmentation of export', max_length=255),
        ),
    ]
