# Generated by Django 3.1.7 on 2021-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0109_company_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_segment',
            field=models.CharField(blank=True, choices=[(None, 'No Sub-Segment or not known'), ('sustain_nurture_and_grow', 'Sustain: Nurture & Grow'), ('sustain_develop_export_capability', 'Sustain: Develop Export Capability'), ('sustain_communicate_benefits', 'Sustain: Communicate Benefits'), ('sustain_increase_competitiveness', 'Sustain: Increase Competitiveness'), ('reassure_nurture_and_grow', 'Reassure: Nurture & Grow'), ('reassure_develop_export_capability', 'Reassure: Develop Export Capability'), ('reassure_leave_be', 'Reassure: Leave Be'), ('reassure_change_the_game', 'Reassure: Change the Game'), ('promote_develop_export_capability', 'Promote: Develop Export Capability'), ('promote_communicate_benefits', 'Promote: Communicate Benefits'), ('promote_change_the_game', 'Promote: Change the Game'), ('challenge', 'Challenge')], help_text='TODO: Get from Cathy', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='segment',
            field=models.CharField(blank=True, choices=[(None, 'No segment or not known'), ('hep', 'HEP'), ('non-hep', 'Non-HEP')], help_text='TODO: Get from Cathy', max_length=255, null=True),
        ),
    ]
