# Generated by Django 3.1.7 on 2021-02-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0109_add_company_state_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='company_state_1911_idx',
        ),
    ]
