# Generated by Django 3.1.6 on 2021-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag', '0002_user_feature_flag'),
        ('company', '0109_add_export_segment_and_subsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='advisers', to='feature_flag.UserFeatureFlag'),
        ),
    ]
