# Generated by Django 3.1.8 on 2021-07-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_remove_puerto_rico'),
        ('company', '0111_add_telephone_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.administrativearea'),
        ),
    ]
