# Generated by Django 3.1.12 on 2021-07-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_remove_puerto_rico'),
        ('company', '0112_contact_address_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='metadata.administrativearea'),
        ),
    ]
