# Generated by Django 3.2.7 on 2021-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0113_auto_20210722_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dynamic',
            field=models.JSONField(blank=True, help_text='Dynamic fields that can be used to store custom data.', null=True),
        ),
    ]
