# Generated by Django 3.2.12 on 2022-03-14 10:01

import datahub.core.validators.telephone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0113_auto_20210722_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='full_telephone_number',
            field=models.CharField(blank=True, max_length=255, validators=[datahub.core.validators.telephone.InternationalTelephoneValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone_countrycode',
            field=models.CharField(blank=True, max_length=255, validators=[datahub.core.validators.telephone.TelephoneCountryCodeValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=255, validators=[datahub.core.validators.telephone.TelephoneValidator()]),
        ),
    ]
