# Generated by Django 3.2.12 on 2022-03-14 10:01

from django.db import migrations

from datahub.core.utils import join_truthy_strings


def combine_phone_number(apps, schema_editor):
    """Combine phone number fields into a single field"""
    Contact = apps.get_model('company', 'Contact')
    for contact in Contact.objects.all().iterator(chunk_size=2000):
        contact.full_telephone_number = join_truthy_strings(
            contact.telephone_countrycode, contact.telephone_number
        )
        contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0114_contact_full_telephone_number'),
    ]

    operations = [
        migrations.RunPython(combine_phone_number, migrations.RunPython.noop),
    ]
