# Generated by Django 3.2.12 on 2022-03-14 10:01

from django.db import migrations

from django.db.models import F, Q, Value
from django.db.models.functions import Concat


def combine_phone_number(apps, schema_editor):
    """Combine phone number fields into a single field"""
    Contact = apps.get_model('company', 'Contact')
    Contact.objects.filter(
        Q(full_telephone_number='') | Q(full_telephone_number__isnull=True),
    ).update(
        full_telephone_number=Concat(
            F('telephone_countrycode'), Value(' '), F('telephone_number'),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0114_contact_full_telephone_number'),
    ]

    operations = [
        migrations.RunPython(combine_phone_number, migrations.RunPython.noop),
    ]
