# Generated by Django 3.2.12 on 2022-03-23 16:14

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Concat


def combine_names(apps, schema_editor):
    """Combine name fields into a single field"""
    Contact = apps.get_model('company', 'Contact')
    Contact.objects.filter(
        name='',
    ).update(
        name=Concat(
            F('first_name'), Value(' '), F('last_name'),
        ),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0116_contact_full_name'),
    ]

    operations = [
        migrations.RunPython(combine_names, migrations.RunPython.noop),
    ]
