# Generated by Django 3.2.12 on 2022-04-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0116_append_alternative_contacts_to_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='telephone_countrycode',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephone_number',
        ),
    ]
