# Generated by Django 3.2.12 on 2022-04-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0117_remove_telephone_and_countrycode_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_alternative',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephone_alternative',
        ),
    ]
