# Generated by Django 3.2.15 on 2022-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag', '0004_userfeatureflaggroup'),
        ('company', '0118_remove_alternative_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='feature_groups',
            field=models.ManyToManyField(blank=True, help_text="User's feature flag groups. Note that the group also needs to be set to active.", related_name='advisers', to='feature_flag.UserFeatureFlagGroup'),
        ),
    ]
