# Generated by Django 3.2.15 on 2022-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0119_advisor_feature_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='sso_user_id',
            field=models.UUIDField(blank=True, help_text='This is the `User ID` that is shown for this user in Staff SSO.', null=True, unique=True, verbose_name='SSO user ID'),
        ),
    ]
