# Generated by Django 3.2.16 on 2023-01-27 16:23

from django.db import migrations

from django.db.models import Func, F


def save_contact_email_as_lower_case(apps, schema_editor):
    Contact = apps.get_model('company', 'Contact')
    Contact.objects.all().update(
        email=Func(F('email'), function='LOWER')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0120_advisor_sso_user_id'),
    ]

    operations = [
        migrations.RunPython(save_contact_email_as_lower_case, migrations.RunPython.noop),
    ]
