# Generated by Django 3.2.16 on 2023-02-20 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0041_update_export_barrier_type'),
        ('company', '0121_auto_20230127_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExport',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('estimated_export_value_years', models.IntegerField()),
                ('estimated_export_value_amount', models.DecimalField(decimal_places=0, max_digits=19)),
                ('estimated_win_date_month', models.IntegerField()),
                ('estimated_win_date_year', models.IntegerField()),
                ('export_potential', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('inactive', 'Inactive')], max_length=255)),
                ('exporter_experience', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='company.company')),
                ('contacts', models.ManyToManyField(to='company.Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.country')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.sector')),
                ('team_members', models.ManyToManyField(blank=True, related_name='_company_companyexport_team_members_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
