# Generated by Django 3.2.16 on 2023-02-28 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0041_update_export_barrier_type'),
        ('company', '0121_auto_20230127_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportExperience',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportYear',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyExport',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                (
                    'estimated_export_value_amount',
                    models.DecimalField(decimal_places=0, max_digits=19),
                ),
                ('estimated_win_date', models.DateTimeField()),
                (
                    'export_potential',
                    models.CharField(
                        choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')],
                        max_length=255,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('won', 'Won'), ('inactive', 'Inactive')],
                        default='active',
                        max_length=255,
                    ),
                ),
                ('notes', models.TextField(blank=True)),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='exports',
                        to='company.company',
                    ),
                ),
                ('contacts', models.ManyToManyField(related_name='exports', to='company.Contact')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'destination_country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='metadata.country',
                    ),
                ),
                (
                    'estimated_export_value_years',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='company.exportyear'
                    ),
                ),
                (
                    'exporter_experience',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='company.exportexperience'
                    ),
                ),
                (
                    'modified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'sector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='metadata.sector'
                    ),
                ),
                (
                    'team_members',
                    models.ManyToManyField(
                        related_name='_company_companyexport_team_members_+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
