# Generated by Django 3.2.18 on 2023-04-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0123_auto_20230308_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexport',
            name='exporter_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.exportexperience'),
        ),
    ]
