# Generated by Django 3.2.16 on 2023-04-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0124_alter_companyexport_exporter_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexport',
            name='destination_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.country'),
        ),
        migrations.AlterField(
            model_name='companyexport',
            name='estimated_export_value_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='company.exportyear'),
        ),
    ]
