# Generated by Django 3.2.16 on 2023-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0125_alter_companyexport_destination_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexport',
            name='export_potential',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=255),
        ),
    ]
