# Generated by Django 3.2.16 on 2023-04-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0126_alter_companyexport_export_potential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexport',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_exports', to='company.Contact'),
        ),
        migrations.AlterField(
            model_name='companyexport',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.sector'),
        ),
    ]
