# Generated by Django 3.2.16 on 2023-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0127_auto_20230427_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexport',
            name='estimated_export_value_amount',
            field=models.DecimalField(decimal_places=0, max_digits=19, null=True),
        ),
    ]
