# Generated by Django 3.2.16 on 2023-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0128_alter_companyexport_estimated_export_value_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexport',
            name='estimated_win_date',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
