# Generated by Django 3.2.18 on 2023-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0130_alter_companyexport_estimated_win_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='turnover',
            field=models.BigIntegerField(blank=True, help_text='In USD. Only used when duns_number is set.', null=True),
        ),
    ]
