# Generated by Django 3.2.20 on 2023-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0132_auto_20230712_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
