# Generated by Django 3.2.20 on 2023-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0134_auto_20230802_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_out_of_business',
            field=models.BooleanField(default=False, help_text='This value is provided from DNB, and cannot be modified inside datahub'),
        ),
    ]
