# Generated by Django 3.2.20 on 2023-10-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0137_contact_email_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='export_win_last_matched_on',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last updated from Company Matching service', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='export_win_match_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
