# Generated by Django 4.0 on 2024-02-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0139_auto_20231204_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='transfer_reason',
            field=models.CharField(blank=True, choices=[('duplicate', 'Duplicate record')], help_text='The reason data for this company was transferred.', max_length=255, null=True),
        ),
    ]
