# Generated by Django 4.2.11 on 2024-08-01 09:54

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('company', '0141_auto_20240222_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_country',
            field=models.ForeignKey(
                to='metadata.Country',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='companies_with_country_address',
                blank=False,
                null=True,
            ),
        ),
    ]