# Generated by Django 4.2.16 on 2024-10-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0142_alter_company_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='consent_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
