# Generated by Django 4.2.17 on 2025-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0144_update_company_export_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='source',
            field=models.CharField(choices=[('data_hub', 'Data Hub'), ('eyb', 'Expand Your Business'), ('great', 'Great'), ('Stova', 'Stova')], default='data_hub', help_text='Where the company was created from, can be on Data Hub or from external sources.', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('data_hub', 'Data Hub'), ('eyb', 'Expand Your Business'), ('great', 'Great'), ('Stova', 'Stova')], default='data_hub', help_text='Where the contact was created from, can be on Data Hub or from external sources.', max_length=255),
        ),
    ]
