# Generated by Django 3.2.16 on 2023-03-08 13:04
from pathlib import PurePath

from django.db import migrations

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_export_metadata(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0147_update_onelisttier.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0146_set_default_for_new_values'),
    ]

    operations = [
        migrations.RunPython(load_export_metadata, migrations.RunPython.noop),
    ]
