# Generated by Django 4.2.20 on 2025-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0147_update_onelisttier'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_com_name_b51658_idx'),
        ),
    ]
