# Generated by Django 4.2.20 on 2025-05-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0148_add_company_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.CharField(db_collation='und-x-icu', max_length=255, unique=True, verbose_name='username'),
        ),
    ]
