/*
    2 digit codes see https://en.wikipedia.org/wiki/ISO_3166-2
    These were exceptions and may still be problematic
        MEX for Mexico city and Mexico
        https://en.wikipedia.org/wiki/North_Ossetia%E2%80%93Alania
        https://en.wikipedia.org/wiki/Sakha
        https://en.wikipedia.org/wiki/ISO_3166-2:UA under Country Ukraine
        https://en.wikipedia.org/wiki/Tibet_Autonomous_Region
*/

drop table if exists international_state_mapping;

create temp table international_state_mapping(
 country_name varchar not null,
 country_code varchar not null,
 state_code varchar not null,
 state_name varchar not null,
 primary key (state_code, country_code, state_name)
);

insert into international_state_mapping
(country_name, country_code, state_name, state_code)
values
('Canada','CA','ALBERTA','AB'),
('Brazil','BR','ACRE','AC'),
('Australia','AU','AUSTRALIAN CAPITAL TERRITORY','ACT'),
('Italy','IT','AGRIGENTO','AG'),
('Macao','MO','Aguascalientes','AG'),
('Mexico','MX','AGUASCALIENTES','AG'),
('China','CN','Anhui','AH'),
('Japan','JP','AICHI','AI'),
('Japan','JP','AKITA','AK'),
('United States','US','Alaska','AK'),
('Brazil','BR','ALAGOAS','AL'),
('Italy','IT','ALESSANDRIA','AL'),
('United States','US','Alabama','AL'),
('Brazil','BR','AMAZONAS','AM'),
('Colombia','CO','Amazonas','AM'),
('Peru','PE','AMAZONAS','AM'),
('Anguilla','AI','Antofagasta','AN'),
('Belgium','BE','ANTWERP','AN'),
('Chile','CL','Antofagasta','AN'),
('Italy','IT','ANCONA','AN'),
('Italy','IT','AOSTA','AO'),
('Japan','JP','AOMORI','AO'),
('Brazil','BR','AMAPA','AP'),
('India','IN','Andhra Pradesh','AP'),
('Indonesia','ID','Andhra Pradesh','AP'),
('Italy','IT','ASCOLI PICENO','AP'),
('Chile','CL','Araucania','AR'),
('India','IN','Arunachal Pradesh','AR'),
('Italy','IT','AREZZO','AR'),
('United States','US','Arkansas','AR'),
('American Samoa','AS','American Samoa','AS'),
('India','IN','Assam','AS'),
('Spain','ES','ASTURIAS','AS'),
('Italy','IT','ASTI','AT'),
('Italy','IT','AVELLINO','AV'),
('United States','US','Arizona','AZ'),
('Argentina','AR','BUENOS AIRES','BA'),
('Brazil','BR','BAHIA','BA'),
('Italy','IT','BARI','BA'),
('Canada','CA','BRITISH COLUMBIA','BC'),
('Italy','IT','BERGAMO','BG'),
('Chile','CL','Bio-Bio','BI'),
('Italy','IT','BIELLA','BI'),
('China','CN','Beijing','BJ'),
('Christmas Island','CX','BEIJING','BJ'),
('Italy','IT','BELLUNO','BL'),
('Sweden','SE','BLEKINGE','BL'),
('Italy','IT','BENEVENTO','BN'),
('Mexico','MX','BAJA CALIFORNIA','BN'),
('Italy','IT','BOLOGNA','BO'),
('India','IN','BIHAR','BR'),
('Italy','IT','BRINDISI','BR'),
('Italy','IT','BRESCIA','BS'),
('Mexico','MX','BAJA CALIFORNIA SUR','BS'),
('Austria','AT','Burgenland','BU'),
('Belgium','BE','WALLOON BRABANT','BW'),
('Italy','IT','BOLZANO','BZ'),
('Italy','IT','CAGLIARI','CA'),
('Macao','MO','Coahuila','CA'),
('Mexico','MX','COAHUILA','CA'),
('United States','US','California','CA'),
('Argentina','AR','CORDOBA','CB'),
('Colombia','CO','Cordoba','CB'),
('Italy','IT','CAMPOBASSO','CB'),
('Spain','ES','CORDOBA','CB'),
('Argentina','AR','CHACO','CC'),
('Brazil','BR','CEARA','CE'),
('Italy','IT','CASERTA','CE'),
('Spain','ES','CEUTA','CE'),
('Argentina','AR','CHUBUT','CH'),
('India','IN','Chandigarh','CH'),
('Italy','IT','CHIETI','CH'),
('Japan','JP','CHIBA','CH'),
('Macao','MO','Chihuahua','CH'),
('Mexico','MX','CHIHUAHUA','CH'),
('Italy','IT','CARBONIA-IGLESIAS','CI'),
('Republic of Korea','KR','JEJU','CJ'),
('Italy','IT','CALTANISSETTA','CL'),
('Mexico','MX','COLIMA','CL'),
('Mexico','MX','CAMPECHE','CM'),
('Argentina','AR','CORRIENTES','CN'),
('Italy','IT','CUNEO','CN'),
('Chile','CL','Coquimbo','CO'),
('Italy','IT','COMO','CO'),
('United States','US','Colorado','CO'),
('Macao','MO','Chiapas','CP'),
('Mexico','MX','CHIAPAS','CP'),
('China','CN','Chongqing','CQ'),
('Italy','IT','CREMONA','CR'),
('Italy','IT','COSENZA','CS'),
('Argentina','AR','CATAMARCA','CT'),
('India','IN','Chhattisgarh','CT'),
('Italy','IT','CATANIA','CT'),
('United States','US','Connecticut','CT'),
('Italy','IT','CATANZARO','CZ'),
('United States','US','District of Columbia','DC'),
('United States','US','Delaware','DE'),
('Brazil','BR','Brasilia (Federal District of)','DF'),
('Macao','MO','Distrito Federal','DF'),
('Mexico','MX','DISTRITO FEDERAL','DF'),
('Venezuela','VE','DISTRITO FEDERAL','DF'),
('India','IN','The Government of NCT of Delhi','DL'),
('Netherlands','NL','DRENTHE','DR'),
('Mexico','MX','DURANGO','DU'),
('Japan','JP','EHIME','EH'),
('Italy','IT','ENNA','EN'),
('Argentina','AR','ENTRE RIOS','ER'),
('Brazil','BR','ESPIRITO SANTO','ES'),
('Italy','IT','FERRARA','FE'),
('Italy','IT','FOGGIA','FG'),
('Japan','JP','FUKUI','FI'),
('China','CN','Fujian','FJ'),
('Netherlands','NL','FLEVOLAND','FL'),
('United States','US','Florida','FL'),
('Uruguay','UY','FLORIDA','FL'),
('Venezuela','VE','Florida','FL'),
('Argentina','AR','FORMOSA','FM'),
('Italy','IT','FERMO','FM'),
('Japan','JP','FUKUOKA','FO'),
('Italy','IT','FROSINONE','FR'),
('Netherlands','NL','FRIESLAND','FR'),
('Japan','JP','FUKUSHIMA','FS'),
('India','IN','Goa','GA'),
('United States','US','Georgia','GA'),
('China','CN','Guangdong','GD'),
('Christmas Island','CX','GUANGDONG','GD'),
('Netherlands','NL','GELDERLAND','GE'),
('Japan','JP','GIFU','GF'),
('India','IN','Gujarat','GJ'),
('Macao','MO','Guanajuato','GJ'),
('Mexico','MX','GUANAJUATO','GJ'),
('Pakistan','PK','Gujarat','GJ'),
('Brazil','BR','GOIAS','GO'),
('Italy','IT','GORIZIA','GO'),
('Italy','IT','GROSSETO','GR'),
('Mexico','MX','GUERRERO','GR'),
('Netherlands','NL','GRONINGEN','GR'),
('China','CN','Gansu','GS'),
('Sweden','SE','GOTLAND','GT'),
('Guam','GU','Guam','GU'),
('Sweden','SE','GÃ„VLEBORG','GV'),
('China','CN','Guizhou','GZ'),
('China','CN','Hainan','HA'),
('Sweden','SE','HALLAND','HA'),
('China','CN','Hebei','HB'),
('China','CN','Henan','HE'),
('Japan','JP','HYOGO','HG'),
('Macao','MO','Hidalgo','HI'),
('Mexico','MX','HIDALGO','HI'),
('United States','US','Hawaii','HI'),
('Japan','JP','HOKKAIDO','HK'),
('China','CN','Heilongjiang','HL'),
('China','CN','Hunan','HN'),
('India','IN','Himachal Pradesh','HP'),
('India','IN','Haryana','HR'),
('Japan','JP','HIROSHIMA','HS'),
('Belgium','BE','HAINAUT','HT'),
('China','CN','Hubei','HU'),
('United States','US','Iowa','IA'),
('Japan','JP','IBARAKI','IB'),
('United States','US','Idaho','ID'),
('United States','US','Illinois','IL'),
('Italy','IT','IMPERIA','IM'),
('Republic of Korea','KR','INCHEON','IN'),
('United States','US','Indiana','IN'),
('Italy','IT','ISERNIA','IS'),
('Japan','JP','ISHIKAWA','IS'),
('Japan','JP','IWATE','IW'),
('Macao','MO','Jalisco','JA'),
('Mexico','MX','JALISCO','JA'),
('Sweden','SE','JÃ„MTLAND','JA'),
('India','IN','Jharkhand','JH'),
('China','CN','Jilin','JL'),
('Sweden','SE','JÃ–NKÃ–PING','JO'),
('China','CN','Jiangsu','JS'),
('China','CN','Jiangxi','JX'),
('Argentina','AR','JUJUY','JY'),
('Bangladesh','BD','Karnataka','KA'),
('India','IN','Karnataka','KA'),
('Nepal','NP','Karnataka','KA'),
('Pakistan','PK','Karnataka','KA'),
('Singapore','SG','Karnataka','KA'),
('Sweden','SE','KALMAR','KA'),
('Japan','JP','KOCHI','KC'),
('Japan','JP','KAGAWA','KG'),
('Republic of Korea','KR','GWANGJU','KJ'),
('India','IN','Kerala','KL'),
('Japan','JP','KUMAMOTO','KM'),
('Japan','JP','KANAGAWA','KN'),
('Sweden','SE','DALARNA','KO'),
('Italy','IT','CROTONE','KR'),
('Sweden','SE','KRONOBERG','KR'),
('Japan','JP','KAGOSHIMA','KS'),
('United States','US','Kansas','KS'),
('Japan','JP','KYOTO','KY'),
('United States','US','Kentucky','KY'),
('United States','US','Louisiana','LA'),
('Italy','IT','LECCO','LC'),
('India','IN','Lakshadweep','LD'),
('Italy','IT','LECCE','LE'),
('Belgium','BE','LIEGE','LG'),
('Belgium','BE','LIMBURG','LI'),
('Italy','IT','LIVORNO','LI'),
('Netherlands','NL','LIMBURG','LI'),
('Chile','CL','Los Lagos','LL'),
('China','CN','Liaoning','LN'),
('Christmas Island','CX','LIAONING','LN'),
('Italy','IT','LODI','LO'),
('Argentina','AR','LA PAMPA','LP'),
('Argentina','AR','LA RIOJA','LR'),
('Chile','CL','Los Rios','LR'),
('Ecuador','EC','Los Rios','LR'),
('Italy','IT','LATINA','LT'),
('Italy','IT','LUCCA','LU'),
('Belgium','BE','LUXEMBOURG','LX'),
('Brazil','BR','MARANHAO','MA'),
('United States','US','Massachusetts','MA'),
('Canada','CA','MANITOBA','MB'),
('Italy','IT','MONZA E BRIANZA','MB'),
('Italy','IT','MACERATA','MC'),
('Mexico','MX','MICHOACAN','MC'),
('Spain','ES','MURCIA','MC'),
('Spain','ES','MADRID','MD'),
('United States','US','Maryland','MD'),
('Italy','IT','MESSINA','ME'),
('Japan','JP','MIE','ME'),
('United States','US','Maine','ME'),
('Brazil','BR','MINAS GERAIS','MG'),
('Japan','JP','MIYAGI','MG'),
('India','IN','Maharashtra','MH'),
('Thailand','TH','Maharashtra','MH'),
('United States','US','Michigan','MI'),
('Chile','CL','Maule','ML'),
('India','IN','Meghalaya','ML'),
('Spain','ES','MELILLA','ML'),
('Argentina','AR','MISIONES','MN'),
('India','IN','Manipur','MN'),
('Paraguay','PY','MISIONES','MN'),
('Philippines','PH','Manipur','MN'),
('United States','US','Minnesota','MN'),
('Italy','IT','MODENA','MO'),
('United States','US','Missouri','MO'),
('India','IN','Madhya Pradesh','MP'),
('Mexico','MX','MORELOS','MR'),
('Brazil','BR','MATO GROSSO DO SUL','MS'),
('United States','US','Mississippi','MS'),
('Brazil','BR','MATO GROSSO','MT'),
('Italy','IT','MATERA','MT'),
('United States','US','Montana','MT'),
('Argentina','AR','MENDOZA','MZ'),
('India','IN','Mizoram','MZ'),
('Japan','JP','MIYAZAKI','MZ'),
('Belgium','BE','NAMUR','NA'),
('Mexico','MX','NAYARIT','NA'),
('Canada','CA','NEW BRUNSWICK','NB'),
('Netherlands','NL','NOORD-BRABANT','NB'),
('Sweden','SE','NORRBOTTEN','NB'),
('Spain','ES','NAVARRA','NC'),
('United States','US','North Carolina','NC'),
('United States','US','North Dakota','ND'),
('United States','US','Nebraska','NE'),
('Netherlands','NL','NOORD-HOLLAND','NH'),
('United States','US','New Hampshire','NH'),
('Japan','JP','NIIGATA','NI'),
('United States','US','New Jersey','NJ'),
('India','IN','Nagaland','NL'),
('Mexico','MX','NUEVO LEON','NL'),
('United States','US','New Mexico','NM'),
('Japan','JP','NAGANO','NN'),
('Italy','IT','NOVARA','NO'),
('Argentina','AR','NEUQUEN','NQ'),
('Japan','JP','NARA','NR'),
('Canada','CA','NOVA SCOTIA','NS'),
('Japan','JP','NAGASAKI','NS'),
('Australia','AU','NEW SOUTH WALES','NSW'),
('Australia','AU','NORTHERN TERRITORY','NT'),
('Canada','CA','NORTHWEST TERRITORIES','NT'),
('Canada','CA','NUNAVUT','NU'),
('Italy','IT','NUORO','NU'),
('United States','US','Nevada','NV'),
('United States','US','New York','NY'),
('Mexico','MX','OAXACA','OA'),
('Italy','IT','OGLIASTRA','OG'),
('Sweden','SE','Ã–STERGÃ–TLAND','OG'),
('United Kingdom','UK','Ohio','OH'),
('United States','US','Ohio','OH'),
('United States','US','Oklahoma','OK'),
('Canada','CA','ONTARIO','ON'),
('Japan','JP','OKINAWA','ON'),
('India','IN','Odisha','OR'),
('Italy','IT','ORISTANO','OR'),
('Sweden','SE','Ã–REBRO','OR'),
('United States','US','Oregon','OR'),
('Japan','JP','OSAKA','OS'),
('Italy','IT','OLBIA-TEMPIO','OT'),
('Japan','JP','OITA','OT'),
('Netherlands','NL','OVERIJSSEL','OV'),
('Japan','JP','OKAYAMA','OY'),
('Brazil','BR','PARA','PA'),
('Italy','IT','PALERMO','PA'),
('Suriname','SR','Para','PA'),
('United States','US','Pennsylvania','PA'),
('Micronesia','Federated States Of','FM','Palau'),
('Brazil','BR','PARAIBA','PB'),
('India','IN','Punjab','PB'),
('Malaysia','MY','Punjab','PB'),
('Pakistan','PK','Punjab','PB'),
('Italy','IT','PIACENZA','PC'),
('Brazil','BR','PERNAMBUCO','PE'),
('Canada','CA','PRINCE EDWARD ISLAND','PE'),
('Italy','IT','PESCARA','PE'),
('Italy','IT','PERUGIA','PG'),
('Brazil','BR','PIAUL','PI'),
('Italy','IT','PISA','PI'),
('Italy','IT','PORDENONE','PN'),
('Italy','IT','PRATO','PO'),
('Brazil','BR','PARANA','PR'),
('Italy','IT','PARMA','PR'),
('United States','US','Puerto Rico','PR'),
('Italy','IT','PISTOIA','PT'),
('Italy','IT','PESARO E URBINO','PU'),
('Mexico','MX','PUEBLA','PU'),
('New Caledonia','NC','Puebla','PU'),
('Republic of Korea','KR','BUSAN','PU'),
('Italy','IT','PAVIA','PV'),
('Northern Mariana Islands','MP','PALAU','PW'),
('India','IN','Puducherry','PY'),
('Italy','IT','POTENZA','PZ'),
('Canada','CA','QUEBEC','QC'),
('Mexico','MX','QUERETARO','QE'),
('China','CN','Qinghai','QH'),
('Australia','AU','QUEENSLAND','QLD'),
('Mexico','MX','QUINTANA ROO','QR'),
('Italy','IT','RAVENNA','RA'),
('Italy','IT','RAGUSA','RG'),
('Argentina','AR','LA RIOJA','RI'),
('Italy','IT','RIETI','RI'),
('United States','US','Rhode Island','RI'),
('Brazil','BR','RIO DE JANEIRO','RJ'),
('India','IN','Rajasthan','RJ'),
('Argentina','AR','RIO NEGRO','RN'),
('Brazil','BR','RIO GRANDE DO NORTE','RN'),
('Italy','IT','RIMINI','RN'),
('Uruguay','UY','RIO NEGRO','RN'),
('Brazil','BR','RONDONIA','RO'),
('Italy','IT','ROVIGO','RO'),
('Brazil','BR','RORAIMA','RR'),
('Brazil','BR','RIO GRANDE DO SUL','RS'),
('Argentina','AR','SALTA','SA'),
('Australia','AU','SOUTH AUSTRALIA','SA'),
('China','CN','Shaanxi','SA'),
('Italy','IT','SALERNO','SA'),
('Argentina','AR','SANTA CRUZ','SC'),
('Aruba','AW','Santa Cruz','SC'),
('Bolivia','BO','Santa Cruz','SC'),
('Brazil','BR','SANTA CATARINA','SC'),
('China','CN','Sichuan','SC'),
('Ecuador','EC','Santa Cruz','SC'),
('Portugal','PT','SANTA CRUZ','SC'),
('Trinidad and Tobago','TT','Santa Cruz','SC'),
('United States','US','South Carolina','SC'),
('China','CN','Shandong','SD'),
('Sweden','SE','SÃ–DERMANLAND','SD'),
('United States','US','South Dakota','SD'),
('Argentina','AR','SANTIAGO','SE'),
('Brazil','BR','SERGIPE','SE'),
('Argentina','AR','SANTA FE','SF'),
('Japan','JP','SAGA','SG'),
('China','CN','Shanghai','SH'),
('Japan','JP','SHIGA','SH'),
('Italy','IT','SIENA','SI'),
('Mexico','MX','SINALOA','SI'),
('Antigua and Barbuda','AG','San Juan','SJ'),
('Argentina','AR','SAN JUAN','SJ'),
('Costa Rica','CR','San Juan','SJ'),
('Dominican Republic','DO','San Juan','SJ'),
('El Salvador','SV','San Juan','SJ'),
('Nicaragua','NI','San Juan','SJ'),
('Trinidad and Tobago','TT','San Juan','SJ'),
('Canada','CA','SASKATCHEWAN','SK'),
('India','IN','Sikkim','SK'),
('Argentina','AR','SAN LUIS','SL'),
('Mexico','MX','SAN LUIS POTOSI','SL'),
('Japan','JP','SHIMANE','SM'),
('Sweden','SE','SKÃ…NE','SN'),
('Italy','IT','SONDRIO','SO'),
('Mexico','MX','SONORA','SO'),
('Republic of Korea','KR','SEOUL','SO'),
('Brazil','BR','SAO PAULO','SP'),
('Italy','IT','LA SPEZIA','SP'),
('Italy','IT','SASSARI','SS'),
('Japan','JP','SAITAMA','ST'),
('Sweden','SE','STOCKHOLM','ST'),
('Italy','IT','SAVONA','SV'),
('China','CN','Shanxi','SX'),
('Austria','AT','Salzburg','SZ'),
('Japan','JP','SHIZUOKA','SZ'),
('Italy','IT','TARANTO','TA'),
('Australia','AU','TASMANIA','TAS'),
('Mexico','MX','TABASCO','TB'),
('Japan','JP','TOCHIGI','TC'),
('Italy','IT','TERAMO','TE'),
('Argentina','AR','TIERRA DEL FUEGO','TF'),
('Chile','CL','Tierra Del Fuego','TF'),
('Republic of Korea','KR','DAEGU','TG'),
('China','CN','Tianjin','TJ'),
('Republic of Korea','KR','DAEJEON','TJ'),
('Japan','JP','TOKYO','TK'),
('Mexico','MX','TLAXCALA','TL'),
('Argentina','AR','TUCUMAN','TM'),
('Mexico','MX','TAMAULIPAS','TM'),
('India','IN','Tamil Nadu','TN'),
('Italy','IT','TRENTO','TN'),
('United States','US','Tennessee','TN'),
('Brazil','BR','TOCANTINS','TO'),
('Italy','IT','TRAPANI','TP'),
('India','IN','Tripura','TR'),
('Italy','IT','TERNI','TR'),
('Italy','IT','TRIESTE','TS'),
('Japan','JP','TOKUSHIMA','TS'),
('Japan','JP','TOTTORI','TT'),
('Italy','IT','TREVISO','TV'),
('United States','US','Texas','TX'),
('Japan','JP','TOYAMA','TY'),
('Italy','IT','UDINE','UD'),
('Republic of Korea','KR','ULSAN','UL'),
('India','IN','Uttar Pradesh','UP'),
('Sweden','SE','UPPSALA','UP'),
('India','IN','Uttarakhand','UT'),
('Netherlands','NL','UTRECHT','UT'),
('United States','US','Utah','UT'),
('Italy','IT','VARESE','VA'),
('United States','US','Virginia','VA'),
('Belgium','BE','FLEMISH BRABANT','VB'),
('Italy','IT','VERBANO-CUSIO-OSSOLA','VB'),
('Sweden','SE','VÃ„STERBOTTEN','VB'),
('Italy','IT','VERCELLI','VC'),
('Spain','ES','VALENCIA','VC'),
('Mexico','MX','VERACRUZ','VE'),
('Sweden','SE','VÃ„STRA GÃ–TALAND','VG'),
('Italy','IT','VICENZA','VI'),
('United States','US','Virgin Islands','VI'),
('Australia','AU','VICTORIA','VIC'),
('Chile','CL','Victoria','VIC'),
('Trinidad and Tobago','TT','Victoria','VIC'),
('Sweden','SE','VÃ„STMANLAND','VM'),
('Sweden','SE','VÃ„STERNORRLAND','VN'),
('Austria','AT','Vorarlberg','VO'),
('Italy','IT','VERONA','VR'),
('Sweden','SE','VÃ„RMLAND','VR'),
('Chile','CL','Valparaiso','VS'),
('Italy','IT','MEDIO CAMPIDANO','VS'),
('Italy','IT','VITERBO','VT'),
('United States','US','Vermont','VT'),
('Italy','IT','VIBO VALENTIA','VV'),
('Australia','AU','WESTERN AUSTRALIA','WA'),
('United States','US','Washington','WA'),
('India','IN','West Bengal','WB'),
('Indonesia','ID','West Bengal','WB'),
('Austria','AT','Vienna','WI'),
('United States','US','Wisconsin','WI'),
('Japan','JP','WAKAYAMA','WK'),
('United States','US','West Virginia','WV'),
('United States','US','Wyoming','WY'),
('China','CN','Xizang','XZ'),
('Japan','JP','YAMAGUCHI','YC'),
('China','CN','Yunnan','YN'),
('Japan','JP','YAMANASHI','YN'),
('Japan','JP','YAMAGATA','YT'),
('Mexico','MX','YUCATAN','YU'),
('Mexico','MX','ZACATECAS','ZA'),
('Netherlands','NL','ZEELAND','ZE'),
('Netherlands','NL','ZUID-HOLLAND','ZH'),
('China','CN','Zhejiang','ZJ'),
('Canada','CA','Newfoundland and Labrador','NL'),
('Canada','CA','Yukon','YT'),
('Chile','CL','Nuble','NB'),
('Chile','CL','Aysen','AI'),
('Chile','CL','Magallanes','MA'),
('Chile','CL','Arica and Parinacota','AP'),
('Chile','CL','Tarapaca','TA'),
('Chile','CL','Atacama','AT'),
('Chile','CL','Santiago','RM'),
('Chile','CL','O’Higgins','LI'),
('China','CN','Guangxi','GX'),
('China','CN','Inner Mongolia','NM'),
('China','CN','Ningxia','NX'),
('China','CN','Xinjiang','XJ'),
('Colombia','CO','Quindio','QUI'),
('Colombia','CO','San Andreas and Providencia','SAP'),
('Colombia','CO','Santander','SAN'),
('Colombia','CO','Sucre','SUC'),
('Colombia','CO','Tolima','TOL'),
('Colombia','CO','Valle del Cauca','VAC'),
('Colombia','CO','Vaupes','VAU'),
('Colombia','CO','Vichada','VID'),
('Colombia','CO','Guaviare','GUV'),
('Colombia','CO','Huila','HUI'),
('Colombia','CO','La Guajira','LAG'),
('Colombia','CO','Magdalena','MAG'),
('Colombia','CO','Meta','MET'),
('Colombia','CO','Narino','NAR'),
('Colombia','CO','Norte de Santander','NSA'),
('Colombia','CO','Putumayo','PUT'),
('Colombia','CO','Risaralda','RIS'),
('Colombia','CO','Bogota (Capital District of)','DC'),
('Colombia','CO','Antioquia','ANT'),
('Colombia','CO','Arauca','ARA'),
('Colombia','CO','Atlantico','ATL'),
('Colombia','CO','Bolivar','BOL'),
('Colombia','CO','Boyaca','BOY'),
('Colombia','CO','Caldas','CAL'),
('Colombia','CO','Caqueta','CAQ'),
('Colombia','CO','Casanare','CAS'),
('Colombia','CO','Cauca','CAU'),
('Colombia','CO','Cesar','CES'),
('Colombia','CO','Choco','CHO'),
('Colombia','CO','Cundinamarca','CUN'),
('Colombia','CO','Guainia','GUA'),
('India','IN','Telangana','TG'),
('India','IN','Andaman and Nicobar Islands','AN'),
('India','IN','Dadra and Nagar Haveli','DN'),
('India','IN','Daman & Diu','DD'),
('India','IN','Jammu & Kashmir','JK'),
('Peru','PE','Cajamarca','CAJ'),
('Peru','PE','Ucayali','UCA'),
('Peru','PE','Tumbes','TUM'),
('Peru','PE','Tacna','TAC'),
('Peru','PE','San Martin','SAM'),
('Peru','PE','Puno','PUN'),
('Peru','PE','Piura','PIU'),
('Peru','PE','Pasco','PAS'),
('Peru','PE','Moquegua','MOQ'),
('Peru','PE','Madre de Dios','MDD'),
('Peru','PE','Lima','LIM'),
('Peru','PE','Lambayeque','LAM'),
('Peru','PE','La Libertad','LAL'),
('Peru','PE','Junin','JUN'),
('Peru','PE','Ica','ICA'),
('Peru','PE','Huanuco','HUC'),
('Peru','PE','Huancavelica','HUV'),
('Peru','PE','Cusco','CUS'),
('Peru','PE','Callao','CAL'),
('Peru','PE','Ayacucho','AYA'),
('Peru','PE','Arequipa','ARE'),
('Peru','PE','Apurimac','APU'),
('Peru','PE','Ancash','ANC'),
('Russia','RU','Bryansk Oblast','BRY'),
('Russia','RU','Ulyanovsk Oblast','ULY'),
('Russia','RU','Penza Oblast','PNZ'),
('Russia','RU','Tver Oblast','TVE'),
('Russia','RU','Kirov Oblast','KIR'),
('Russia','RU','Belgorod Oblast','BEL'),
('Russia','RU','Vladimir Oblast','VLA'),
('Russia','RU','Leningrad Oblast','LEN'),
('Russia','RU','Tula Oblast','TUL'),
('Russia','RU','Omsk Oblast','OMS'),
('Russia','RU','Orenburg Oblast','ORE'),
('Russia','RU','Voronezh Oblast','VOR'),
('Russia','RU','Irkutsk Oblast','IRK'),
('Russia','RU','Saratov Oblast','SAR'),
('Russia','RU','Novosibirsk Oblast','NVS'),
('Russia','RU','Volgograd Oblast','VGG'),
('Russia','RU','Kemerovo Oblast','KEM'),
('Russia','RU','Samara Oblast','SAM'),
('Russia','RU','Tyumen Oblast','TYU'),
('Russia','RU','Chelyabinsk Oblast','CHE'),
('Russia','RU','Rostov Oblast','ROS'),
('Russia','RU','Sverdlovsk Oblast','SVE'),
('Russia','RU','Moscow Oblast','MOS'),
('Russia','RU','Yaroslavl Oblast','YAR'),
('Russia','RU','Arkhangelsk Oblast','ARK'),
('Russia','RU','Vologda Oblast','VLG'),
('Russia','RU','Kursk Oblast','KRS'),
('Russia','RU','Ryazan Oblast','RYA'),
('Russia','RU','Lipetsk Oblast','LIP'),
('Russia','RU','Tambov Oblast','TAM'),
('Russia','RU','Ivanovo Oblast','IVA'),
('Russia','RU','Smolensk Oblast','SMO'),
('Russia','RU','Tomsk Oblast','TOM'),
('Russia','RU','Kaluga Oblast','KLU'),
('Russia','RU','Kurgan Oblast','KGN'),
('Russia','RU','Astrakhan Oblast','AST'),
('Russia','RU','Kaliningrad Oblast','KGD'),
('Russia','RU','Amur Oblast','AMU'),
('Russia','RU','Murmansk Oblast','MUR'),
('Russia','RU','Oryol Oblast','ORL'),
('Russia','RU','Psvok Oblast','PSK'),
('Russia','RU','Kostroma Oblast','KOS'),
('Russia','RU','Novgorod Oblast','NGR'),
('Russia','RU','Sakhalin Oblast','SAK'),
('Russia','RU','Magadan Oblast','MAG'),
('Russia','RU','Bashkortostan','BA'),
('Russia','RU','Tatarstan','TA'),
('Russia','RU','Dagestan','DA'),
('Russia','RU','Udmurtia','UD'),
('Russia','RU','Chuvashia','CU'),
('Russia','RU','Chechnya','CE'),
('Russia','RU','Komi Republic','KO'),
('Russia','RU','Buryatia','BU'),
('Russia','RU','Kabardino-Balkaria','KB'),
('Russia','RU','Mordovia','MO'),
('Russia','RU','Mari El','ME'),
('Russia','RU','Karelia','KR'),
('Russia','RU','Khakassia','KK'),
('Russia','RU','Ingushetia','IN'),
('Russia','RU','Adygea','AD'),
('Russia','RU','Karachay-Cherkessia','KC'),
('Russia','RU','Tuva','TY'),
('Russia','RU','Kalmykia','KL'),
('Russia','RU','Altai Republic','AL'),
('Russia','RU','Krasnodar Krai','KDA'),
('Russia','RU','Krasnoyarsk Krai','KYA'),
('Russia','RU','Perm Krai','PER'),
('Russia','RU','Stavropol Krai','STA'),
('Russia','RU','Altai Krai','ALT'),
('Russia','RU','Primorsky Krai','PRI'),
('Russia','RU','Khabarovsk Krai','KHA'),
('Russia','RU','Zabaykalsky Krai','ZAB'),
('Russia','RU','Kamchatka Krai','KAM'),
('Russia','RU','Moscow','MOW'),
('Russia','RU','Saint Petersburg','SPE'),
('Russia','RU','Sevastop','SE'),
('Mexico','MX','Mexico','MEX'),
('Mexico','MX','Mexico City (Federal entity of)','MEX'),
('Russia','RU','North Ossetia-Alania','SE'),
('Russia','RU','Yakutia','SA'),
('Russia','RU','Crimea','01'),
('China','CN','Tibet','XZ');

create extension if not exists pg_trgm;

update metadata_administrativearea
set area_code = sub.state_code -- Or what ever the new state code field is called
from
	(select meta.id, ints.state_code,  metc.name as country_name, meta.name as state_name, similarity(meta.name, ints.state_name) as similarity_calc
	 from international_state_mapping ints
		inner join metadata_country metc on ints.country_code = metc.iso_alpha2_code
		inner join metadata_administrativearea meta on similarity(meta.name, ints.state_name) > 0.6 and metc.id = meta.country_id
	 order by similarity_calc desc, country_name, state_name
	) as sub
where
	metadata_administrativearea.id = sub.id
	and nullif(metadata_administrativearea.area_code, '') is null;

drop table if exists international_state_mapping;
drop extension if exists pg_trgm;