# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0001_squashed_0012_auto_20170523_0940'),
        ('company', '0001_squash_0030_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nda_signed', models.BooleanField()),
                ('estimated_land_date', models.DateField()),
                ('cdms_project_code', models.CharField(blank=True, max_length=255, null=True)),
                ('project_shareable', models.NullBooleanField()),
                ('anonymous_description', models.TextField(blank=True, null=True)),
                ('not_shareable_reason', models.TextField(blank=True, null=True)),
                ('referral_source_activity_event', models.CharField(blank=True, max_length=255, null=True)),
                ('client_cannot_provide_total_investment', models.NullBooleanField()),
                ('total_investment', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('client_cannot_provide_foreign_investment', models.NullBooleanField()),
                ('foreign_equity_investment', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('government_assistance', models.NullBooleanField()),
                ('number_new_jobs', models.IntegerField(blank=True, null=True)),
                ('number_safeguarded_jobs', models.IntegerField(blank=True, null=True)),
                ('r_and_d_budget', models.NullBooleanField()),
                ('non_fdi_r_and_d_budget', models.NullBooleanField()),
                ('new_tech_to_uk', models.NullBooleanField()),
                ('export_revenue', models.NullBooleanField()),
                ('client_requirements', models.TextField(blank=True, null=True)),
                ('site_decided', models.NullBooleanField()),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_postcode', models.CharField(blank=True, max_length=255, null=True)),
                ('client_considering_other_countries', models.NullBooleanField()),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('average_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metadata.SalaryRange')),
                ('business_activities', models.ManyToManyField(blank=True, related_name='_investmentproject_business_activities_+', to='metadata.InvestmentBusinessActivity')),
                ('client_contacts', models.ManyToManyField(blank=True, related_name='investment_projects', to='company.Contact')),
                ('client_relationship_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to=settings.AUTH_USER_MODEL)),
                ('competitor_countries', models.ManyToManyField(blank=True, related_name='_investmentproject_competitor_countries_+', to='metadata.Country')),
                ('fdi_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.FDIType')),
                ('intermediate_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_investment_projects', to='company.Company')),
                ('investment_recipient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_investment_projects', to='company.Company')),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.InvestmentType')),
                ('investor_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_investment_projects', to='company.Company')),
                ('non_fdi_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.NonFDIType')),
                ('phase', models.ForeignKey(default='8a320cc9-ae2e-443e-9d26-2f36452c2ced', on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.InvestmentProjectPhase')),
                ('project_assurance_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referral_source_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.ReferralSourceActivity')),
                ('referral_source_activity_marketing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.ReferralSourceMarketing')),
                ('referral_source_activity_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.ReferralSourceWebsite')),
                ('referral_source_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_investment_projects', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metadata.Sector')),
                ('strategic_drivers', models.ManyToManyField(blank=True, related_name='investment_projects', to='metadata.InvestmentStrategicDriver')),
                ('uk_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investee_projects', to='company.Company')),
                ('uk_region_locations', models.ManyToManyField(blank=True, related_name='_investmentproject_uk_region_locations_+', to='metadata.UKRegion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentProjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investment.InvestmentProject')),
            ],
        ),
    ]
