# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_squash_0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='average_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.SalaryRange'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='client_relationship_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='fdi_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_projects', to='metadata.FDIType'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='intermediate_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intermediate_investment_projects', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='investment_recipient_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_investment_projects', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='investment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_projects', to='metadata.InvestmentType'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='non_fdi_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_projects', to='metadata.NonFDIType'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='phase',
            field=models.ForeignKey(default='8a320cc9-ae2e-443e-9d26-2f36452c2ced', on_delete=django.db.models.deletion.PROTECT, related_name='investment_projects', to='metadata.InvestmentProjectPhase'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='project_assurance_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_projects', to='metadata.ReferralSourceActivity'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_activity_marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_projects', to='metadata.ReferralSourceMarketing'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_activity_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_projects', to='metadata.ReferralSourceWebsite'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_investment_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.Sector'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='uk_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investee_projects', to='company.Company'),
        ),
    ]
