# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='average_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metadata.SalaryRange'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='business_activity',
            field=models.ManyToManyField(blank=True, related_name='_investmentproject_business_activity_+', to='metadata.InvestmentBusinessActivity'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='client_contacts',
            field=models.ManyToManyField(blank=True, related_name='investment_projects', to='company.Contact'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='client_relationship_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='competitor_countries',
            field=models.ManyToManyField(blank=True, related_name='_investmentproject_competitor_countries_+', to='metadata.Country'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='fdi_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.FDIType'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='foreign_equity_investment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='intermediate_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_investment_projects', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='investment_recipient_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_investment_projects', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='investor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_investment_projects', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='non_fdi_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.NonFDIType'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='number_new_jobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='number_safeguarded_jobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='project_assurance_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.ReferralSourceActivity'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_activity_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.Event'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_activity_marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.ReferralSourceMarketing'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_activity_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.ReferralSourceWebsite'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='referral_source_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_investment_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metadata.Sector'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='strategic_drivers',
            field=models.ManyToManyField(blank=True, related_name='investment_projects', to='metadata.InvestmentStrategicDriver'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='total_investment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='uk_region_locations',
            field=models.ManyToManyField(blank=True, related_name='_investmentproject_uk_region_locations_+', to='metadata.UKRegion'),
        ),
    ]
