# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0002_rename_advsor_fkeys_to_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
