# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20170502_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='phase',
            field=models.ForeignKey(default='8a320cc9-ae2e-443e-9d26-2f36452c2ced', on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='metadata.InvestmentProjectPhase'),
        ),
    ]
