# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_merge_20170509_1053'),
        ('investment', '0003_auto_20170510_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='client_cannot_provide_foreign_investment',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='client_cannot_provide_total_investment',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='client_considering_other_countries',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='uk_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investee_projects', to='company.Company'),
        ),
    ]
