# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_add_investment_archiving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='anonymous_description',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='investment_recipient_company',
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='actual_land_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
