# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_auto_20170515_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='referral_source_activity_event',
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='referral_source_activity_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
