# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_change_event_to_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
