# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_add_investemnt_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentproject',
            old_name='phase',
            new_name='stage',
        ),
    ]
