# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_add_investemnt_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprojectdocument',
            name='doc_type',
            field=models.CharField(choices=[('actual_land_date', 'Actual land date'), ('fdi_type', 'Fdi type'), ('operations_commenced', 'Operations commenced'), ('total_investment', 'Total investment'), ('foreign_equity_investment', 'Foreign equity investment'), ('number_new_jobs', 'Number new jobs'), ('number_safeguarded_jobs', 'Number safeguarded jobs'), ('r_and_d_budget', 'R and D budget'), ('new_tech_to_uk', 'New tech to uk'), ('export_revenue', 'Export revenue'), ('average_salary', 'Average salary')], max_length=255),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE investment_iprojectdocument "
                "SET doc_type = 'number_safeguarded_jobs' "
                "WHERE doc_type = 'number_safeguarded jobs'"
            ),
            reverse_sql=(
                "UPDATE investment_iprojectdocument "
                "SET doc_type = 'number_safeguarded jobs' "
                "WHERE doc_type = 'number_safeguarded_jobs'"
            ),
            elidable=True,
        ),
    ]
