# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_fix_doc_type'),
        ('investment', '0007_rename_phase_to_stage'),
    ]

    operations = [
    ]
