# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_fix_created_on_modified_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentproject',
            old_name='project_assurance_advisor',
            new_name='project_assurance_adviser',
        ),
        migrations.RenameField(
            model_name='investmentproject',
            old_name='referral_source_advisor',
            new_name='referral_source_adviser',
        ),
    ]
