# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_merge_20170707_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='likelihood_of_landing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('1_low', 'Low'), ('2_medium', 'Medium'), ('3_high', 'High')], max_length=255, null=True),
        ),
    ]
