# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0009_add_likelihood_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProjectTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investment_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='investment.InvestmentProject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='investmentprojectteammember',
            unique_together=set([('investment_project', 'adviser')]),
        ),
    ]
