# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_add_fdi_value'),
        ('investment', '0010_add_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='fdi_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_projects', to='metadata.FDIValue'),
        ),
    ]
