# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_add_fdi_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='some_new_jobs',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='uk_company_decided',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='will_new_jobs_last_two_years',
            field=models.NullBooleanField(),
        ),
    ]
