# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_add_additional_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'permissions': (('view_investmentproject', 'Can View Investment Project'),)},
        ),
        migrations.AlterModelOptions(
            name='investmentprojectcode',
            options={'permissions': (('view_investmentprojectcode', 'Can View Investment Project Code'),)},
        ),
        migrations.AlterModelOptions(
            name='investmentprojectteammember',
            options={'permissions': (('view_investmentprojectteammember', 'Can View Investment Project Team Member'),)},
        ),
        migrations.AlterModelOptions(
            name='iprojectdocument',
            options={'permissions': (('view_iprojectdocument', 'Can View Investment Project Document'),), 'verbose_name': 'investment project document', 'verbose_name_plural': 'investment project documents'},
        ),
    ]
