# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_add_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='quotable_as_public_case_study',
            field=models.NullBooleanField(),
        ),
    ]
