# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_created_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'permissions': (('view_investmentproject', 'Can view investment project'),)},
        ),
        migrations.AlterModelOptions(
            name='investmentprojectcode',
            options={'permissions': (('view_investmentprojectcode', 'Can view investment project code'),)},
        ),
        migrations.AlterModelOptions(
            name='investmentprojectteammember',
            options={'permissions': (('view_investmentprojectteammember', 'Can view investment project team member'),)},
        ),
        migrations.AlterModelOptions(
            name='iprojectdocument',
            options={'permissions': (('view_iprojectdocument', 'Can view investment project document'),), 'verbose_name': 'investment project document', 'verbose_name_plural': 'investment project documents'},
        ),
    ]
