# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0017_merge_20170808_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='anonymous_description',
            field=models.TextField(blank=True),
        ),
    ]
