# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0018_add_anon_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='associated_non_fdi_r_and_d_project',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='+', to='investment.InvestmentProject',
                verbose_name='associated non-FDI R&D project'
            ),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='non_fdi_r_and_d_budget',
            field=models.NullBooleanField(verbose_name='has associated non-FDI R&D project'),
        ),
    ]
