# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_auto_20171018_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'permissions': (('read_investmentproject', 'Can read investment project'),)},
        ),
        migrations.AlterModelOptions(
            name='investmentprojectteammember',
            options={'permissions': (('read_investmentprojectteammember', 'Can read investment project team member'),)},
        ),
        migrations.AlterModelOptions(
            name='iprojectdocument',
            options={'permissions': (('read_iprojectdocument', 'Can read project document'),), 'verbose_name': 'investment project document', 'verbose_name_plural': 'investment project documents'},
        ),
    ]
