# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_auto_20171018_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='nda_signed',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='not_shareable_reason',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='project_shareable',
        ),
    ]
