# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0022_investortype_involvement_specificprogramme'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='investor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investment.InvestorType'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='level_of_involvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investment.Involvement'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='specific_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investment.SpecificProgramme'),
        ),
    ]
