# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_squashed_0025_remove_non_fdi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='archived_documents_url_path',
            field=models.CharField(blank=True, help_text='Legacy field. File browser path to the archived documents for this investment project.', max_length=255),
        ),
    ]
