# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0026_add_archived_documents_url_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'permissions': (('read_investmentproject', 'Can read investment project'), ('read_associated_investmentproject', 'Can read associated investment project'))},
        ),
    ]
