# Generated by Django 2.0.1 on 2018-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0031_remove_team_member_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
