# Generated by Django 2.0.1 on 2018-01-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_add_default_id_for_metadata'),
        ('investment', '0033_add_investment_document_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='actual_uk_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.UKRegion', verbose_name='actual UK region'),
        ),
    ]
