# Generated by Django 2.0.1 on 2018-01-17 14:24

from pathlib import PurePath

from django.db import migrations, models
import uuid
from datahub.core.migration_utils import load_yaml_data_in_migration


def load_initial_delivery_partners(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0037_initial_delivery_partners.yaml'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0036_allow_blank_poss_uk_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDeliveryPartner',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='delivery_partners',
            field=models.ManyToManyField(blank=True, help_text='These are the delivery partner(s) in the region(s) where the project landed.', related_name='_investmentproject_delivery_partners_+', to='investment.InvestmentDeliveryPartner', verbose_name='investment delivery partners'),
        ),
        migrations.RunPython(load_initial_delivery_partners, migrations.RunPython.noop)
    ]
