# Generated by Django 2.0.1 on 2018-01-22 09:32

from django.db import migrations
from django.db.models import Count


def correct_migrated_site_decided(apps, schema_editor):
    """
    Updates migrated projects that have actual UK regions set, but don't have have
    site_decided=True.

    This is needed because actual UK regions is nested under the site decided question in the UI.
    """
    InvestmentProject = apps.get_model('investment', 'InvestmentProject')
    InvestmentProject.objects.annotate(
        num_actual_uk_regions=Count('actual_uk_regions')
    ).filter(
        cdms_project_code__isnull=False, num_actual_uk_regions__gt=0
    ).update(
        site_decided=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0037_add_delivery_partners'),
    ]

    operations = [
        migrations.RunPython(correct_migrated_site_decided, migrations.RunPython.noop, elidable=True),
    ]
