# Generated by Django 2.0.2 on 2018-03-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0040_add_sector_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProjectStageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='project_arrived_in_triage_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='proposal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentprojectstagelog',
            name='investment_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_log', to='investment.InvestmentProject'),
        ),
        migrations.AddField(
            model_name='investmentprojectstagelog',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='metadata.InvestmentProjectStage'),
        ),
    ]
