# Generated by Django 2.1 on 2018-08-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0048_update_permissions_django_21'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'default_permissions': ('add', 'change_all', 'delete', 'view_all'), 'permissions': (('view_associated_investmentproject', 'Can view associated investment project'), ('change_associated_investmentproject', 'Can change associated investment project'), ('export_investmentproject', 'Can export investment project'), ('view_investmentproject_document', 'Can view investment project document'), ('change_stage_to_won_investmentproject', 'Can change investment project stage to won'))},
        ),
    ]
