# Generated by Django 3.1.5 on 2021-02-10 17:17

import uuid
from pathlib import PurePath

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db import migrations, models

from datahub.core.migration_utils import load_yaml_data_in_migration

metadata_files = [
    '0001_abandonment_reason.yaml',
    '0001_opportunity_status.yaml',
    '0001_opportunity_type.yaml',
    '0001_opportunity_value_type.yaml',
    '0001_source_of_funding.yaml',
]


def load_metadata(apps, schema_editor):
    for file_name in metadata_files:
        load_yaml_data_in_migration(
            apps,
            PurePath(__file__).parent / file_name,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0107_remove_accepts_dit_email_marketing_from_django'),
        ('investment', '0003_remove_change_stage_to_won_permission'),
        ('metadata', '0006_update_services'),
        ('investor_profile', '0001_squashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonmentReason',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityStatus',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityType',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityValueType',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceOfFunding',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LargeCapitalOpportunity',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_checks_conducted_on', models.DateField(blank=True, null=True)),
                ('opportunity_value', models.DecimalField(blank=True, decimal_places=0, help_text='Opportunity value (£)', max_digits=19, null=True)),
                ('total_investment_sought', models.DecimalField(blank=True, decimal_places=0, help_text='Total investment sought (£)', max_digits=19, null=True)),
                ('current_investment_secured', models.DecimalField(blank=True, decimal_places=0, help_text='Current investment secured (£)', max_digits=19, null=True)),
                ('funding_supporting_details', models.TextField(blank=True)),
                ('dit_support_provided', models.BooleanField()),
                ('why_abandoned', models.TextField(blank=True)),
                ('why_suspended', models.TextField(blank=True)),
                ('asset_classes', models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_asset_classes_+', to='investor_profile.AssetClassInterest')),
                ('construction_risks', models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_construction_risks_+', to='investor_profile.ConstructionRisk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estimated_return_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.ReturnRate')),
                ('investment_projects', models.ManyToManyField(blank=True, related_name='opportunities', to='investment.InvestmentProject')),
                ('investment_types', models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_investment_types_+', to='investor_profile.LargeCapitalInvestmentType')),
                ('lead_dit_relationship_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity_value_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='opportunity.OpportunityValueType', verbose_name='Type of opportunity value')),
                ('other_dit_contacts', models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_other_dit_contacts_+', to=settings.AUTH_USER_MODEL, verbose_name='List of DIT contacts')),
                ('promoters', models.ManyToManyField(blank=True, related_name='opportunities', to='company.Company', verbose_name='List of Promoters')),
                ('reasons_for_abandonment', models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_reasons_for_abandonment_+', to='opportunity.AbandonmentReason')),
                ('required_checks_conducted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.RequiredChecksConducted')),
                ('required_checks_conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sources_of_funding', models.ManyToManyField(blank=True, null=True, related_name='_largecapitalopportunity_sources_of_funding_+', to='opportunity.SourceOfFunding')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='opportunity.OpportunityStatus')),
                ('time_horizons', models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_time_horizons_+', to='investor_profile.TimeHorizon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='opportunity.OpportunityType')),
                ('uk_region_locations', models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_uk_region_locations_+', to='metadata.UKRegion', verbose_name='List of UK regions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(load_metadata, migrations.RunPython.noop),
    ]
