# Generated by Django 3.1.6 on 2021-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='sources_of_funding',
            field=models.ManyToManyField(blank=True, related_name='_largecapitalopportunity_sources_of_funding_+', to='opportunity.SourceOfFunding'),
        ),
    ]
