# Generated by Django 4.2.11 on 2024-05-30 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0080_update_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor_profile', '0002_alter_largecapitalinvestorprofile_asset_classes_of_interest_and_more'),
        ('opportunity', '0003_add_export_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='asset_classes',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.assetclassinterest'),
        ),
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='construction_risks',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.constructionrisk'),
        ),
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='investment_types',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.largecapitalinvestmenttype'),
        ),
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='other_dit_contacts',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='List of DIT contacts'),
        ),
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='reasons_for_abandonment',
            field=models.ManyToManyField(blank=True, related_name='+', to='opportunity.abandonmentreason'),
        ),
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='sources_of_funding',
            field=models.ManyToManyField(blank=True, related_name='+', to='opportunity.sourceoffunding'),
        ),
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='time_horizons',
            field=models.ManyToManyField(blank=True, related_name='+', to='investor_profile.timehorizon'),
        ),
        migrations.AlterField(
            model_name='largecapitalopportunity',
            name='uk_region_locations',
            field=models.ManyToManyField(blank=True, related_name='+', to='metadata.ukregion', verbose_name='List of UK regions'),
        ),
    ]
