# Generated by Django 3.0.5 on 2020-04-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_squashed_0063_add_created_on_id_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'default_permissions': ('add', 'change_all', 'delete', 'view_all'), 'permissions': (('view_associated_investmentproject', 'Can view associated investment project'), ('change_associated_investmentproject', 'Can change associated investment project'), ('export_investmentproject', 'Can export investment project'), ('view_investmentproject_document', 'Can view investment project document'), ('change_stage_to_won_investmentproject', 'Can change investment project stage to won'), ('change_to_any_stage_investmentproject', 'Can change investment project to any stage'))},
        ),
    ]
