# Generated by Django 3.1.12 on 2021-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_remove_change_stage_to_won_permission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='investmentproject',
            name='investment__created_b91445_idx',
        ),
        migrations.AddIndex(
            model_name='investmentproject',
            index=models.Index(fields=['modified_on', 'id'], name='investment__modifie_30238e_idx'),
        ),
    ]
