# Generated by Django 3.2.16 on 2023-02-09 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0009_update_specific_programmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='project_assurance_adviser',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='investment_project_project_assurance_adviser',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='project_manager',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='investment_project_project_manager',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
