# Generated by Django 4.2.10 on 2024-03-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0076_alter_sector_sector_cluster_alter_team_country_and_more'),
        ('investment', '0015_remove_existing_gva_multipliers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gvamultiplier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='sector',
            field=models.ForeignKey(default='b422c9d2-5f95-e211-a939-e4115bead28a', on_delete=django.db.models.deletion.PROTECT, to='metadata.sector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='sector_classification_gva_multiplier',
            field=models.CharField(choices=[('labour', 'Labour intensive'), ('capital', 'Capital intensive')], default='capital', max_length=255),
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='sector_classification_value_band',
            field=models.CharField(choices=[('labour', 'Labour intensive'), ('capital', 'Capital intensive')], default='capital', max_length=255),
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='value_band_a_minimum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='value_band_b_minimum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='value_band_c_minimum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='value_band_d_minimum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gvamultiplier',
            name='value_band_e_minimum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='fdi_sic_grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gva_multipliers', to='investment.fdisicgrouping'),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='actual_uk_regions',
            field=models.ManyToManyField(blank=True, related_name='+', to='metadata.ukregion', verbose_name='actual UK regions'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='business_activities',
            field=models.ManyToManyField(blank=True, related_name='+', to='metadata.investmentbusinessactivity'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='competitor_countries',
            field=models.ManyToManyField(blank=True, related_name='+', to='metadata.country'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='delivery_partners',
            field=models.ManyToManyField(blank=True, help_text='These are the delivery partner(s) in the region(s) where the project landed.', related_name='+', to='investment.investmentdeliverypartner', verbose_name='investment delivery partners'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='uk_region_locations',
            field=models.ManyToManyField(blank=True, related_name='+', to='metadata.ukregion', verbose_name='possible UK regions'),
        ),
        migrations.AddConstraint(
            model_name='gvamultiplier',
            constraint=models.UniqueConstraint(fields=('financial_year', 'sector'), name='unique_year_sector_multiplier'),
        ),
    ]
