# Generated by Django 4.2.11 on 2024-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0018_update_specific_programmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('delayed', 'Delayed'), ('dormant', 'Dormant'), ('lost', 'Lost'), ('abandoned', 'Abandoned'), ('won', 'Won'), ('referred', 'Referred')], default='ongoing', max_length=255),
        ),
    ]
