# Generated by Django 4.2.10 on 2024-03-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0077_alter_sector_sector_cluster_alter_team_country_and_more'),
        ('investment', '0018_relink_gva_multipliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvamultiplier',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gva_multiplier', to='metadata.sector'),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='value_band_a_minimum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='value_band_b_minimum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='value_band_c_minimum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='value_band_d_minimum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='value_band_e_minimum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='gross_value_added',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Denormalised GVA value which is automatically populated using the gva multiplier and either the foreign equity investment value or number of new jobs.', max_digits=25, null=True),
        ),
    ]
