# Generated by Django 4.2.11 on 2024-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0019_alter_investmentproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='specific_programme_new',
            field=models.ManyToManyField(blank=True, related_name='investment_projects', to='investment.specificprogramme'),
        ),
    ]
