# Generated by Django 4.2.11 on 2024-06-07 14:19

from django.db import migrations


def add_existing_data_to_new_field(apps, schema_editor):
    InvestmentProject = apps.get_model('investment', "InvestmentProject")
    for project in InvestmentProject.objects.exclude(specific_programme__isnull=True):
        project.specific_programme_new.add(project.specific_programme)


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_investmentproject_specific_programme_new'),
    ]

    operations = [
        migrations.RunPython(add_existing_data_to_new_field, migrations.RunPython.noop),
    ]
