# Generated by Django 4.2.11 on 2024-06-12 08:08
from logging import getLogger

from django.db import migrations
from django.db.models import Exists, OuterRef

logger = getLogger(__name__)


def copy_specific_programmes(apps, schema_editor):
    """Copies specific_programme to specific_programmes."""
    InvestmentProject = apps.get_model('investment', 'InvestmentProject')
    no_specific_programmes_subquery = Exists(
        InvestmentProject.objects.filter(
            pk=OuterRef('pk'),
            specific_programmes__id__isnull=True,
        ).only('pk')
    )

    projects_with_uncopied_specific_programmes = InvestmentProject.objects.select_for_update().annotate(
        has_no_specific_programmes=no_specific_programmes_subquery
    ).filter(
        specific_programme__isnull=False,
        has_no_specific_programmes=True,
    ).only('pk', 'specific_programme')

    num_updated = 0

    for project in projects_with_uncopied_specific_programmes:
        project.specific_programmes.add(project.specific_programme)
        num_updated += 1

    logger.info(
        f'''Field specific_programme copied to specific_progrmmes for {
            num_updated} investment projects.''',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_investmentproject_specific_programmes'),
    ]

    operations = [
        migrations.RunPython(copy_specific_programmes, migrations.RunPython.noop)
    ]
