# Generated by Django 4.2.11 on 2024-06-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0021_auto_20240607_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='specific_programme',
        ),
        migrations.RenameField(
            model_name='investmentproject',
            old_name='specific_programme_new',
            new_name='specific_programme',
        ),
    ]
