# Generated by Django 4.2.11 on 2024-06-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0022_update_specific_programmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='specific_programme',
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='specific_programmes',
            field=models.ManyToManyField(blank=True, related_name='+',
                                         to='investment.specificprogramme'),
        ),
    ]
