# Generated by Django 4.2.16 on 2025-01-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0024_add_referred_to_eyb_specific_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='site_address_is_company_address',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
