# Generated by Django 4.2.17 on 2025-01-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0025_investmentproject_site_address_is_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('delayed', 'Delayed'), ('dormant', 'Dormant'), ('lost', 'Lost'), ('abandoned', 'Abandoned'), ('won', 'Won')], default='ongoing', max_length=255),
        ),
    ]
