# Generated by Django 4.2.20 on 2025-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0026_alter_investmentproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='actual_average_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
