# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0027_add_default_id_for_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'permissions': (('read_investmentproject', 'Can read investment project'), ('read_associated_investmentproject', 'Can read associated investment project'))},
        ),
    ]
