# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0028_add_custom_lep_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'permissions': (('read_investmentproject', 'Can read investment project'), ('read_associated_investmentproject', 'Can read associated investment project'), ('change_associated_investmentproject', 'Can change associated investment project'))},
        ),
    ]
