# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:33
from __future__ import unicode_literals

from django.db import migrations


# Django does not automatically handle permission renames. So, we have to rename these ourselves.


permission_rename_operations = (
    (
        'read_investmentproject',
        'Can read investment project',
        'read_all_investmentproject',
        'Can read all investment project',
    ),
    (
        'change_investmentproject',
        'Can change investment project',
        'change_all_investmentproject',
        'Can change all investment project',
    )
)


def update_permissions(apps, schema_editor):
    Permission = apps.get_model('auth.Permission')

    for old_codename, old_name, new_codename, new_name in permission_rename_operations:
        try:
            permission = Permission.objects.get(codename=old_codename)
            permission.codename = new_codename
            permission.name = new_name
            permission.save()
        except Permission.DoesNotExist:
            # Permissions won't exist yet when running tests or in new environments
            pass


def update_permissions_reverse(apps, schema_editor):
    Permission = apps.get_model('auth.Permission')

    for old_codename, old_name, new_codename, new_name in permission_rename_operations:
        permission = Permission.objects.get(codename=new_codename)
        permission.codename = old_codename
        permission.name = old_name
        permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0029_add_change_associated_investmentproject_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'default_permissions': ('add', 'change_all', 'delete'), 'permissions': (('read_all_investmentproject', 'Can read all investment project'), ('read_associated_investmentproject', 'Can read associated investment project'), ('change_associated_investmentproject', 'Can change associated investment project'))},
        ),
        migrations.RunPython(update_permissions, update_permissions_reverse, elidable=True),
    ]
