# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 11:55
from __future__ import unicode_literals

from django.db import migrations


permissions_to_remove = (
    'read_investmentprojectteammember',
    'add_investmentprojectteammember',
    'change_investmentprojectteammember',
    'delete_investmentprojectteammember',
)


def update_permissions(apps, schema_editor):
    Permission = apps.get_model('auth.Permission')
    Permission.objects.filter(codename__in=permissions_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0030_rename_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentprojectteammember',
            options={'default_permissions': ()},
        ),
        migrations.RunPython(update_permissions, migrations.RunPython.noop, elidable=True)
    ]
