# Generated by Django 2.0.1 on 2018-01-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0011_add_default_id_for_metadata'),
        ('investment', '0033_add_investment_document_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='actual_uk_regions',
            field=models.ManyToManyField(blank=True, related_name='_investmentproject_actual_uk_regions_+', to='metadata.UKRegion', verbose_name='actual UK regions'),
        ),
    ]
