# Generated by Django 2.0.1 on 2018-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0034_add_actual_uk_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='allow_blank_estimated_land_date',
            field=models.BooleanField(default=False, help_text='Controls whether estimated land date is a required field. Intended for projects migrated from CDMS in the verify win and won stages where legacy data for estimated land date does not exist.'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='estimated_land_date',
            field=models.DateField(null=True, blank=True),
        ),
    ]
