# Generated by Django 2.0.3 on 2018-03-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0039_add_additional_delivery_partners'),
    ]

    operations = [
    ]
