# Generated by Django 2.0.6 on 2018-06-22 15:29

from logging import getLogger

from django.db import migrations
from django.db.models import F
from django.db.models.functions import Lower


logger = getLogger(__name__)


def correct_migrated_statuses(apps, schema_editor):
    investment_project_model = apps.get_model('investment', 'InvestmentProject')
    num_rows_updated = investment_project_model.objects.annotate(
        status_lower=Lower('status')
    ).exclude(
        status_lower=F('status')
    ).update(
        status=Lower('status')
    )
    logger.info(f'{num_rows_updated} InvestmentProject statuses corrected')


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0044_add_change_stage_to_won_permission'),
    ]

    operations = [
        migrations.RunPython(correct_migrated_statuses, migrations.RunPython.noop, elidable=True)
    ]
