# Generated by Django 2.0.7 on 2018-08-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0045_correct_migrated_statuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iprojectdocument',
            old_name='filename',
            new_name='original_filename',
        ),
        migrations.AlterField(
            model_name='iprojectdocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
        migrations.AlterUniqueTogether(
            name='iprojectdocument',
            unique_together=set(),
        ),
    ]
