# Generated by Django 2.0.8 on 2018-08-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0046_updated_iprojectdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iprojectdocument',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='iprojectdocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='iprojectdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='iprojectdocument',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='iprojectdocument',
            name='project',
        ),
        migrations.DeleteModel(
            name='IProjectDocument',
        ),
    ]
