# Generated by Django 2.1.3 on 2018-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0050_investmentproject_project_manager_first_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='approved_commitment_to_invest',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='approved_fdi',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='approved_good_value',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='approved_high_value',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='approved_landed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='approved_non_fdi',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='client_cannot_provide_foreign_investment',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='client_cannot_provide_total_investment',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='client_considering_other_countries',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='export_revenue',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='government_assistance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='new_tech_to_uk',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='non_fdi_r_and_d_budget',
            field=models.BooleanField(null=True, verbose_name='has associated non-FDI R&D project'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='quotable_as_public_case_study',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='r_and_d_budget',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='site_decided',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='some_new_jobs',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='uk_company_decided',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='will_new_jobs_last_two_years',
            field=models.BooleanField(null=True),
        ),
    ]
