# Generated by Django 2.1.3 on 2018-12-03 15:50

from pathlib import PurePath

from django.db import migrations, models
from datahub.core.migration_utils import load_yaml_data_in_migration
import uuid


def load_likelihood_to_land_data(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0053_initial_likelihood_to_land.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0052_investmentproject_country_investment_originates_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikelihoodToLand',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.RunPython(load_likelihood_to_land_data, migrations.RunPython.noop),
    ]
