# Generated by Django 2.1.3 on 2018-12-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0053_likelihood_to_land'),

    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='likelihood_to_land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investment.LikelihoodToLand'),
        ),
    ]
