# Generated by Django 2.1.7 on 2019-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0057_remove_investmentproject_likelihood_of_landing'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='investmentproject',
                    name='likelihood_of_landing',
                    field=models.IntegerField(
                        blank=True,
                        null=True,
                    )
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='likelihood_of_landing',
        ),
    ]
