# Generated by Django 2.1.7 on 2019-03-27 15:57

from pathlib import PurePath

from django.db import migrations, models
from datahub.core.migration_utils import load_yaml_data_in_migration
import uuid


def load_gva_multiplier(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0060_gvamultiplier.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0059_fdi_sicgrouping_and_investmentsector'),
    ]

    operations = [
        migrations.CreateModel(
            name='GVAMultiplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('multiplier', models.FloatField()),
                ('financial_year', models.IntegerField(help_text='The year from which the gva multiplier should apply from.')),
                ('fdi_sic_grouping', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='gva_multipliers', to='investment.FDISICGrouping')),
            ],
            options={'verbose_name': 'GVA Multiplier'},
        ),
        migrations.AlterUniqueTogether(
            name='gvamultiplier',
            unique_together={('fdi_sic_grouping', 'financial_year')},
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='gva_multiplier',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=models.deletion.SET_NULL,
                                    related_name='investment_projects',
                                    to='investment.GVAMultiplier'),
        ),
        migrations.RunPython(load_gva_multiplier, migrations.RunPython.noop),
    ]
