# Generated by Django 2.1.7 on 2019-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0060_gvamultiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='gross_value_added',
            field=models.IntegerField(null=True),
        ),
    ]
