# Generated by Django 2.1.7 on 2019-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0060_gvamultiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='gross_value_added',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Denormalised GVA value which is automatically populated using the gva multiplier and the foreign equity investment value.', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='gvamultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
    ]
