# Generated by Django 2.1.7 on 2019-04-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0061_investmentproject_gross_value_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='gross_value_added',
            field=models.IntegerField(blank=True, help_text='Denormalised GVA value which is automatically populated using the gva multiplier and the foreign equity investment value.', null=True),
        ),
    ]
