# Generated by Django 3.2.15 on 2022-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_create_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='norecentinvestmentinteractionreminder',
            name='email_delivery_status',
            field=models.CharField(blank=True, choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('permanent-failure', 'Permanent failure'), ('temporary-failure', 'Temporary failure'), ('technical-failure', 'Technical failure'), ('unknown', 'Unknown')], default='unknown', help_text='Email delivery status', max_length=255),
        ),
        migrations.AddField(
            model_name='norecentinvestmentinteractionreminder',
            name='email_notification_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='norecentinvestmentinteractionreminder',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='norecentinvestmentinteractionreminder',
            name='status',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('dismissed', 'Dismissed')], default='live', max_length=255),
        ),
        migrations.AddField(
            model_name='upcomingestimatedlanddatereminder',
            name='email_delivery_status',
            field=models.CharField(blank=True, choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('permanent-failure', 'Permanent failure'), ('temporary-failure', 'Temporary failure'), ('technical-failure', 'Technical failure'), ('unknown', 'Unknown')], default='unknown', help_text='Email delivery status', max_length=255),
        ),
        migrations.AddField(
            model_name='upcomingestimatedlanddatereminder',
            name='email_notification_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingestimatedlanddatereminder',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingestimatedlanddatereminder',
            name='status',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('dismissed', 'Dismissed')], default='live', max_length=255),
        ),
    ]
