# Generated by Django 3.2.16 on 2022-11-08 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0120_advisor_sso_user_id'),
        ('interaction', '0079_add_new_policy_areas'),
        ('reminder', '0004_create_export_no_interaction_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoRecentExportInteractionReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('live', 'Live'), ('dismissed', 'Dismissed')], default='live', max_length=255)),
                ('email_notification_id', models.UUIDField(blank=True, null=True)),
                ('email_delivery_status', models.CharField(blank=True, choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('permanent-failure', 'Permanent failure'), ('temporary-failure', 'Temporary failure'), ('technical-failure', 'Technical failure'), ('unknown', 'Unknown')], default='unknown', help_text='Email delivery status', max_length=255)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_recent_export_interaction_reminders', to='company.company')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_recent_export_interaction_reminders', to='interaction.interaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
