# Generated by Django 3.2.16 on 2022-11-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0079_add_new_policy_areas'),
        ('reminder', '0005_create_reminder_for_no_export_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norecentexportinteractionreminder',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_recent_export_interaction_reminders', to='interaction.interaction'),
        ),
    ]
