# Generated by Django 3.2.20 on 2023-09-14 10:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0008_create_reminder_for_new_export_interactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingTaskSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reminder_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=5)),
                ('email_reminders_enabled', models.BooleanField(default=False)),
                ('adviser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpcomingTaskReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('live', 'Live'), ('dismissed', 'Dismissed')], default='live', max_length=255)),
                ('email_notification_id', models.UUIDField(blank=True, null=True)),
                ('email_delivery_status', models.CharField(blank=True, choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('permanent-failure', 'Permanent failure'), ('temporary-failure', 'Temporary failure'), ('technical-failure', 'Technical failure'), ('unknown', 'Unknown')], default='unknown', help_text='Email delivery status', max_length=255)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_task_reminders', to='task.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
