# Generated by Django 3.2.20 on 2023-09-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_upcomingtaskreminder_upcomingtasksubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingTaskReminder',
        ),
    ]
