# Generated by Django 3.2.21 on 2023-10-19 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20230927_1039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0011_taskassignedtomefromotherssubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProjectTaskTaskAssignedToMeFromOthersReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('live', 'Live'), ('dismissed', 'Dismissed')], default='live', max_length=255)),
                ('email_notification_id', models.UUIDField(blank=True, null=True)),
                ('email_delivery_status', models.CharField(blank=True, choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('permanent-failure', 'Permanent failure'), ('temporary-failure', 'Temporary failure'), ('technical-failure', 'Technical failure'), ('unknown', 'Unknown')], default='unknown', help_text='Email delivery status', max_length=255)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
