# Generated by Django 3.2.21 on 2023-10-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0011_taskassignedtomefromotherssubscription'),
        ('reminder', '0011_upcomingtaskreminder'),
    ]

    operations = [
    ]
