# Generated by Django 3.2.20 on 2023-11-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0015_taskassignedtomefromothersreminder'),
        ('reminder', '0015_taskoverduesubscription'),
    ]

    operations = [
    ]
