# Generated by Django 3.2.22 on 2023-11-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0016_merge_20231102_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentProjectTaskTaskAssignedToMeFromOthersReminder',
        ),
    ]
