# Generated by Django 3.2.20 on 2023-11-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0017_delete_investmentprojecttasktaskassignedtomefromothersreminder'),
        ('reminder', '0017_taskamendedbyothersreminder_taskamendedbyotherssubscription'),
    ]

    operations = [
    ]
