# Generated by Django 3.2.23 on 2023-11-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0018_merge_20231110_1611'),
        ('reminder', '0019_taskoverduereminder'),
    ]

    operations = [
    ]
