# Generated by Django 4.2.14 on 2024-09-10 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0142_alter_company_address_country'),
        ('interaction', '0081_auto_20230130_1124.py'),
        ('company_referral', '0008_add_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activity_source', models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255)),
                ('date', models.DateTimeField(help_text='A date field copied from the activity_source model, so it can be sorted in the API.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='company.company')),
                ('interaction', models.ForeignKey(blank=True, help_text='If related to an interaction, must not have relations to any other activity (referral, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='interaction.interaction')),
                ('referral', models.ForeignKey(blank=True, help_text='If related to an referral, must not have relations to any other activity (interaction, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='company_referral.companyreferral')),
            ],
        ),
    ]
