# Generated by Django 4.2.15 on 2024-09-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0023_remove_investmentproject_specific_programme_and_more'),
        ('company_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyactivity',
            name='investment',
            field=models.ForeignKey(blank=True, help_text='investment project for company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='investment.investmentproject', unique=True),
        ),
    ]
