# Generated by Django 4.2.15 on 2024-09-30 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0087_update_services"),
        ("company_activity", "0003_ingestedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Great",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(max_length=255, unique=True)),
                ("published", models.DateTimeField()),
                ("attributed_to_type", models.CharField(max_length=255)),
                ("attributed_to_id", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("meta_action_name", models.CharField(max_length=255)),
                ("meta_template_id", models.CharField(max_length=255)),
                ("meta_email_address", models.CharField(max_length=255)),
                ("data_comment", models.CharField(max_length=255)),
                ("data_full_name", models.CharField(max_length=255)),
                ("data_website_url", models.CharField(max_length=255)),
                ("data_company_name", models.CharField(max_length=255)),
                ("data_company_size", models.CharField(max_length=255)),
                ("data_phone_number", models.CharField(max_length=255)),
                ("data_email_address", models.CharField(max_length=255)),
                ("data_terms_agreed", models.BooleanField()),
                ("data_opportunities", models.CharField(max_length=255)),
                ("data_role_in_company", models.CharField(max_length=255)),
                ("data_opportunity_urls", models.CharField(max_length=255)),
                ("actor_type", models.CharField(max_length=255)),
                ("actor_id", models.CharField(max_length=255)),
                ("actor_dit_email_address", models.CharField(max_length=255)),
                ("actor_dit_is_blacklisted", models.BooleanField()),
                ("actor_dit_is_whitelisted", models.BooleanField()),
                (
                    "actor_dit_blacklisted_reason",
                    models.CharField(max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "data_country",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="metadata.country",
                    ),
                ),
            ],
        ),
    ]
