# Generated by Django 4.2.15 on 2024-10-08 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_activity", "0004_great"),
    ]

    operations = [
        migrations.AlterField(
            model_name="great",
            name="actor_dit_email_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="great",
            name="actor_dit_is_blacklisted",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="great",
            name="actor_dit_is_whitelisted",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="great",
            name="actor_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="great",
            name="actor_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="great",
            name="data_opportunities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="great",
            name="form_id",
            field=models.IntegerField(unique=True),
        ),
    ]
