# Generated by Django 4.2.15 on 2024-10-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_activity", "0005_alter_great_actor_dit_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="great",
            name="data_comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="great",
            name="data_opportunity_urls",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="great",
            name="url",
            field=models.TextField(),
        ),
    ]
