# Generated by Django 4.2.15 on 2024-10-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_activity", "0005_alter_great_actor_dit_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="great",
            name="actor_dit_blacklisted_reason",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="great",
            name="actor_dit_email_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="great",
            name="actor_type",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="great",
            name="url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
