# Generated by Django 4.2.16 on 2024-10-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_company_alter_order_contact_and_more'),
        ('company_activity', '0006_alter_great_data_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyactivity',
            name='order',
            field=models.ForeignKey(blank=True, help_text='If related to an omis order, must not have relations to any other activity (referral, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='order.order', unique=True),
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='activity_source',
            field=models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment'), ('order', 'order')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255),
        ),
    ]
