# Generated by Django 4.2.15 on 2024-10-29 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0087_update_services"),
        ("company", "0142_alter_company_address_country"),
        ("company_activity", "0007_companyactivity_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreatExportEnquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.IntegerField(unique=True)),
                ("url", models.TextField()),
                ("meta_sender_ip_address", models.CharField(max_length=255)),
                ("meta_sender_email_address", models.CharField(max_length=255)),
                ("meta_subject", models.CharField(max_length=255)),
                ("meta_full_name", models.CharField(max_length=255)),
                ("meta_subdomain", models.CharField(max_length=255)),
                ("meta_action_name", models.CharField(max_length=255)),
                ("meta_service_name", models.CharField(max_length=255)),
                ("meta_spam_control", models.CharField(max_length=255)),
                ("meta_email_address", models.CharField(max_length=255)),
                ("data_search", models.CharField(max_length=255)),
                ("data_enquiry", models.CharField(max_length=255)),
                ("data_find_out_about", models.CharField(max_length=255)),
                ("data_sector_primary_other", models.CharField(max_length=255)),
                ("data_triage_journey", models.TextField()),
                ("data_received_support", models.BooleanField(null=True)),
                ("data_uk_telephone_number", models.CharField(max_length=255)),
                ("data_product_or_service_1", models.CharField(max_length=255)),
                ("data_product_or_service_2", models.CharField(max_length=255)),
                ("data_product_or_service_3", models.CharField(max_length=255)),
                ("data_product_or_service_4", models.CharField(max_length=255)),
                ("data_product_or_service_5", models.CharField(max_length=255)),
                ("data_about_your_experience", models.CharField(max_length=255)),
                ("data_contacted_gov_departments", models.BooleanField(null=True)),
                ("data_help_us_further", models.BooleanField(null=True)),
                ("data_help_us_improve", models.CharField(max_length=255)),
                ("actor_id", models.IntegerField(null=True)),
                ("actor_type", models.CharField(max_length=255, null=True)),
                (
                    "actor_dit_email_address",
                    models.CharField(max_length=255, null=True),
                ),
                ("actor_dit_is_blacklisted", models.BooleanField(null=True)),
                ("actor_dit_is_whitelisted", models.BooleanField(null=True)),
                (
                    "actor_dit_blacklisted_reason",
                    models.CharField(max_length=255, null=True),
                ),
                ("form_created_at", models.DateTimeField()),
                ("actor_email", models.CharField(max_length=255)),
                ("submission_type", models.CharField(max_length=255)),
                ("submission_action", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="great_export_enquiries",
                        to="company.company",
                    ),
                ),
                (
                    "data_markets",
                    models.ManyToManyField(
                        related_name="great_export_market_enquiries",
                        to="metadata.country",
                    ),
                ),
                (
                    "data_sector_primary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="great_export_primary_sector_enquiries",
                        to="metadata.sector",
                    ),
                ),
                (
                    "data_sector_secondary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="great_export_secondary_sector_enquiries",
                        to="metadata.sector",
                    ),
                ),
                (
                    "data_sector_tertiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="great_export_tertiary_sector_enquiries",
                        to="metadata.sector",
                    ),
                ),
                (
                    "meta_sender_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="great_export_enquiries",
                        to="metadata.country",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Great",
        ),
    ]
