# Generated by Django 4.2.16 on 2024-10-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0023_remove_investmentproject_specific_programme_and_more'),
        ('interaction', '0082_alter_interaction_company_alter_interaction_contacts_and_more'),
        ('company_referral', '0008_add_help_text'),
        ('order', '0014_alter_order_company_alter_order_contact_and_more'),
        ('company_activity', '0007_companyactivity_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyactivity',
            name='interaction',
            field=models.OneToOneField(blank=True, help_text='If related to an Interaction, must not have relations to any other activity (referral, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='interaction.interaction'),
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='investment',
            field=models.OneToOneField(blank=True, help_text='InvestmentProject for a company, must not have relations to any other activity (interaction, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='investment.investmentproject'),
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='order',
            field=models.OneToOneField(blank=True, help_text='If related to an omis Order, must not have relations to any other activity (referral, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='order.order'),
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='referral',
            field=models.OneToOneField(blank=True, help_text='If related to a CompanyReferral, must not have relations to any other activity (interaction, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='company_referral.companyreferral'),
        ),
    ]
