# Generated by Django 4.2.15 on 2024-10-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0142_alter_company_address_country"),
        ("company_activity", "0009_greatexportenquiry_delete_great"),
    ]

    operations = [
        migrations.AddField(
            model_name="greatexportenquiry",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="great_export_enquiries",
                to="company.contact",
            ),
        ),
    ]
