# Generated by Django 4.2.16 on 2024-10-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0009_greatexportenquiry_delete_great'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyactivity',
            name='great',
            field=models.OneToOneField(blank=True, help_text='If related to an great export enquiry, must not have relations to any other activity (referral, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='company_activity.greatexportenquiry'),
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='activity_source',
            field=models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment'), ('order', 'order'), ('great', 'great')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255),
        ),
    ]
