# Generated by Django 4.2.16 on 2024-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('company_activity', '0013_alter_greatexportenquiry_data_enquiry'), ('company_activity', '0014_rename_great_companyactivity_great_export_enquiry_and_more'), ('company_activity', '0015_alter_companyactivity_activity_source')]

    dependencies = [
        ('company_activity', '0012_companyactivity_great_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='data_enquiry',
            field=models.TextField(),
        ),
        migrations.RenameField(
            model_name='companyactivity',
            old_name='great',
            new_name='great_export_enquiry',
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='activity_source',
            field=models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment'), ('order', 'order'), ('greatExportEnquiry', 'greatExportEnquiry')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='activity_source',
            field=models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment'), ('order', 'order'), ('great_export_enquiry', 'great_export_enquiry')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255),
        ),
    ]
