# Generated by Django 4.2.16 on 2024-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0012_companyactivity_great_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='data_enquiry',
            field=models.TextField(),
        ),
    ]
