# Generated by Django 4.2.16 on 2024-11-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_lead', '0009_alter_eyblead_marketing_hashed_uuid'),
        ('company_activity', '0012_companyactivity_great_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyactivity',
            name='eyb_lead',
            field=models.ForeignKey(blank=True, help_text='If related to an EYB leady, must not have relations to any other activity (referral, event etc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='investment_lead.eyblead', unique=True),
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='activity_source',
            field=models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment'), ('order', 'order'), ('great', 'great'), ('eyb_lead', 'eyb_lead')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255),
        ),
    ]
