# Generated by Django 4.2.16 on 2024-11-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0013_alter_greatexportenquiry_data_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyactivity',
            old_name='great',
            new_name='great_export_enquiry',
        ),
        migrations.AlterField(
            model_name='companyactivity',
            name='activity_source',
            field=models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment'), ('order', 'order'), ('greatExportEnquiry', 'greatExportEnquiry')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255),
        ),
    ]
