# Generated by Django 4.2.16 on 2024-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0014_rename_great_companyactivity_great_export_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyactivity',
            name='activity_source',
            field=models.CharField(choices=[('interaction', 'interaction'), ('referral', 'referral'), ('event', 'event'), ('investment', 'investment'), ('order', 'order'), ('great_export_enquiry', 'great_export_enquiry')], help_text='The type of company activity, such as an interaction, event, referral etc.', max_length=255),
        ),
    ]
