# Generated by Django 4.2.16 on 2024-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0013_alter_greatexportenquiry_data_enquiry_squashed_0015_alter_companyactivity_activity_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='data_product_or_service_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='data_product_or_service_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='data_product_or_service_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='data_product_or_service_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='data_product_or_service_5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='greatexportenquiry',
            name='meta_subject',
            field=models.TextField(),
        ),
    ]
