# Generated by Django 4.2.16 on 2024-11-19 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0016_companyactivity_eyb_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestedfile',
            name='file_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='DateTime the ingested file was last modified in S3'),
        ),
        migrations.AlterField(
            model_name='ingestedfile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='DateTime the instance was created'),
        ),
    ]
