# Generated by Django 4.2.16 on 2024-12-03 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0018_companyactivity_eyb_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StovaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(unique=True)),
                ('url', models.TextField()),
                ('city', models.TextField()),
                ('code', models.CharField()),
                ('name', models.TextField()),
                ('state', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('max_reg', models.IntegerField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('timezone', models.CharField(max_length=255)),
                ('folder_id', models.IntegerField(null=True)),
                ('live_date', models.DateTimeField(null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('price_type', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('modified_by', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('location_city', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField()),
                ('client_contact', models.CharField(max_length=255)),
                ('location_state', models.CharField(max_length=255)),
                ('default_language', models.CharField(max_length=255)),
                ('location_country', models.CharField(max_length=255)),
                ('approval_required', models.BooleanField()),
                ('location_address1', models.CharField(max_length=255)),
                ('location_address2', models.CharField(max_length=255)),
                ('location_address3', models.CharField(max_length=255)),
                ('location_postcode', models.CharField(max_length=255)),
                ('standard_currency', models.CharField(max_length=255)),
            ],
        ),
    ]
