# Generated by Django 4.2.16 on 2024-12-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0019_add_stova_event_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stovaevent',
            old_name='event_id',
            new_name='stova_event_id',
        ),
    ]
