# Generated by Django 4.2.17 on 2024-12-24 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0021_match_ingested_stova_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StovaAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stova_event_id', models.IntegerField(unique=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateTimeField()),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('attendee_questions', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('registration_status', models.CharField(max_length=255)),
                ('virtual_event_attendance', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('last_lobby_login', models.DateTimeField()),
            ],
        ),
    ]
