# Generated by Django 4.2.17 on 2024-12-31 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0144_update_company_export_experience'),
        ('company_activity', '0021_match_ingested_stova_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StovaAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stova_attendee_id', models.IntegerField(unique=True)),
                ('stova_event_id', models.IntegerField(unique=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField()),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('attendee_questions', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('registration_status', models.CharField(max_length=255)),
                ('virtual_event_attendance', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('last_lobby_login', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='If a company match can be found from company_name, the relation is added.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stova_attendee', to='company.company')),
                ('contact', models.ForeignKey(blank=True, help_text='If a contact match can be found from the email, the relation is added.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stova_attendee', to='company.contact')),
            ],
        ),
    ]
