# Generated by Django 4.2.16 on 2025-01-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0022_add_stova_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='stovaevent',
            name='attendee',
            field=models.ForeignKey(blank=True, help_text='If a stova attendee can match a stova event', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stova_event', to='company_activity.stovaattendee'),
        ),
    ]
