# Generated by Django 4.2.17 on 2024-12-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0144_update_company_export_experience'),
        ('company_activity', '0022_add_stova_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='stovaattendee',
            name='company',
            field=models.ForeignKey(blank=True, help_text='If a company match can be found from company_name, the relation is added.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stova_attendee', to='company.company'),
        ),
        migrations.AddField(
            model_name='stovaattendee',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='If a contact match can be found from the email, the relation is added.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stova_attendee', to='company.contact'),
        ),
    ]
