# Generated by Django 4.2.17 on 2025-01-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0022_add_stova_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='stovaattendee',
            name='ingested_stova_event',
            field=models.ForeignKey(blank=True, help_text=('Each attendee comes with a Stova Event ID which is stored as its raw value under stova_attendee_id. This field is the FK to the ingrested Stova Event in Data Hub.',), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stova_attendee', to='company_activity.stovaevent'),
        ),
    ]
