# Generated by Django 4.2.17 on 2025-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0023_link_stova_attendee_to_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaevent',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
