# Generated by Django 4.2.17 on 2025-01-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0024_stova_event_integer_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaevent',
            name='client_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
