# Generated by Django 4.2.17 on 2025-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0025_stova_event_client_contact_integer_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaevent',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
