# Generated by Django 4.2.17 on 2025-02-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0027_stova_event_allow_empty_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='location_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='location_address3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='location_postcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
