# Generated by Django 4.2.17 on 2025-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0028_update_stova_event_fields_to_match_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaattendee',
            name='attendee_questions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='contact_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaevent',
            name='location_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
