# Generated by Django 4.2.17 on 2025-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0029_stova_model_match_real_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaevent',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
