# Generated by Django 4.2.17 on 2025-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0030_match_stova_data_for_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaattendee',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='last_lobby_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='registration_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='virtual_event_attendance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
