# Generated by Django 4.2.17 on 2025-02-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_activity', '0031_match_stova_attendee_model_to_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaattendee',
            name='stova_event_id',
            field=models.IntegerField(),
        ),
    ]
