# Generated by Django 4.2.20 on 2025-03-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0147_update_onelisttier'),
        ('company_activity', '0033_stova_event_contact_info_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stovaattendee',
            name='company',
            field=models.ForeignKey(blank=True, help_text='If a company match can be found from company_name, the relation is added.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stova_attendee', to='company.company'),
        ),
        migrations.AlterField(
            model_name='stovaattendee',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='If a contact match can be found from the email, the relation is added.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stova_attendee', to='company.contact'),
        ),
    ]
