# Generated by Django 4.2.20 on 2025-04-25 15:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0147_update_onelisttier'),
        ('company_activity', '0035_add_temp_model_for_tracking_deletions'),
    ]

    operations = [
        migrations.CreateModel(
            name='KingsAwardRecipient',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('year_awarded', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1966)])),
                ('category', models.CharField(choices=[('International Trade (Export)', 'International Trade (Export)'), ('Innovation (Technology)', 'Innovation (Technology)'), ('Export and Technology (Combined)', 'Export and Technology (Combined)'), ('Sustainable Development (Environmental Achievement)', 'Sustainable Development (Environmental Achievement)'), ('Promoting Opportunity (Through Social Mobility)', 'Promoting Opportunity (Through Social Mobility)')], max_length=255)),
                ('citation', models.TextField(blank=True, null='')),
                ('year_expired', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1966)])),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kings_awards', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "King's Award",
                'verbose_name_plural': "King's Awards",
                'indexes': [models.Index(fields=['company', 'year_awarded'], name='company_act_company_7d93ec_idx'), models.Index(fields=['category', 'year_awarded'], name='company_act_categor_7e8422_idx')],
                'unique_together': {('company', 'category', 'year_awarded')},
            },
        ),
    ]
