# Generated by Django 5.2.1 on 2025-05-20 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0149_alter_advisor_email'),
        ('company_activity', '0036_kingsawardrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptPayments',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_id', models.BigIntegerField(db_index=True, unique=True)),
                ('reporting_period_start_date', models.DateField()),
                ('reporting_period_end_date', models.DateField()),
                ('filing_date', models.DateField(db_index=True)),
                ('company_name', models.TextField()),
                ('company_house_number', models.TextField(db_index=True)),
                ('email_address', models.TextField(db_index=True)),
                ('approved_by', models.TextField()),
                ('qualifying_contracts_in_period', models.BooleanField()),
                ('average_paid_days', models.IntegerField()),
                ('paid_within_30_days_pct', models.IntegerField()),
                ('paid_31_to_60_days_pct', models.IntegerField()),
                ('paid_after_61_days_pct', models.IntegerField()),
                ('paid_later_than_terms_pct', models.IntegerField()),
                ('payment_shortest_period_days', models.IntegerField()),
                ('payment_longest_period_days', models.IntegerField()),
                ('payment_max_period_days', models.IntegerField()),
                ('payment_terms_changed_comment', models.TextField()),
                ('payment_terms_changed_notified_comment', models.TextField()),
                ('code_of_practice', models.TextField()),
                ('other_electronic_invoicing', models.BooleanField()),
                ('other_supply_chain_finance', models.BooleanField()),
                ('other_retention_charges_in_policy', models.BooleanField()),
                ('other_retention_charges_in_past', models.BooleanField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_payments', to='company.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_payments', to='company.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Payments Data',
                'verbose_name_plural': 'Prompt Payments Data',
                'ordering': ('-filing_date', '-reporting_period_end_date'),
                'indexes': [models.Index(fields=['company', 'filing_date'], name='company_act_company_295b8b_idx'), models.Index(fields=['reporting_period_start_date'], name='company_act_reporti_c10658_idx'), models.Index(fields=['reporting_period_end_date'], name='company_act_reporti_1324ce_idx')],
            },
        ),
    ]
