# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:15
from __future__ import unicode_literals

import core.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('company_number', models.CharField(blank=True, db_index=True, max_length=8)),
                ('uk_based', models.BooleanField(default=True)),
                ('business_type', models.CharField(max_length=160)),
                ('registered_name', models.CharField(max_length=160)),
                ('trading_name', models.CharField(blank=True, max_length=160)),
                ('sectors', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('number_of_employees', models.CharField(blank=True, max_length=20)),
                ('annual_turnover', models.BigIntegerField(blank=True, null=True)),
                ('trading_address_1', models.CharField(max_length=300, null=True)),
                ('trading_address_2', models.CharField(blank=True, max_length=300)),
                ('trading_address_town', models.CharField(blank=True, max_length=50)),
                ('trading_address_county', models.CharField(blank=True, max_length=50)),
                ('trading_address_country', models.CharField(blank=True, max_length=100)),
                ('trading_address_postcode', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('account_manager', models.CharField(blank=True, max_length=100)),
                ('countries_of_interest', models.TextField(blank=True)),
                ('currently_exporting_to', models.TextField(blank=True)),
                ('connections', models.CharField(blank=True, max_length=200)),
                ('business_description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.ReadOnlyModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyHouseCompany',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_number', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=160)),
                ('registered_address_care_of', models.CharField(blank=True, max_length=100)),
                ('registered_address_po_box', models.CharField(blank=True, max_length=10)),
                ('registered_address_address_1', models.CharField(blank=True, max_length=300)),
                ('registered_address_address_2', models.CharField(blank=True, max_length=300)),
                ('registered_address_town', models.CharField(blank=True, max_length=50)),
                ('registered_address_county', models.CharField(blank=True, max_length=50)),
                ('registered_address_country', models.CharField(blank=True, max_length=100)),
                ('registered_address_postcode', models.CharField(blank=True, max_length=20)),
                ('company_category', models.CharField(blank=True, max_length=100)),
                ('company_status', models.CharField(blank=True, max_length=70)),
                ('sic_code_1', models.CharField(blank=True, max_length=170)),
                ('sic_code_2', models.CharField(blank=True, max_length=170)),
                ('sic_code_3', models.CharField(blank=True, max_length=170)),
                ('sic_code_4', models.CharField(blank=True, max_length=170)),
                ('uri', models.CharField(blank=True, max_length=100)),
                ('incorporation_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.ReadOnlyModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_1', models.CharField(blank=True, max_length=300)),
                ('address_2', models.CharField(blank=True, max_length=300)),
                ('address_town', models.CharField(blank=True, max_length=50)),
                ('address_county', models.CharField(blank=True, max_length=50)),
                ('address_country', models.CharField(blank=True, max_length=100)),
                ('address_postcode', models.CharField(blank=True, max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=30)),
                ('alt_email', models.EmailField(max_length=254, null=True)),
                ('notes', models.TextField(blank=True)),
                ('primary_contact_team', models.TextField(blank=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.Company')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.ReadOnlyModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('date_of_interaction', models.DateField()),
                ('advisor', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Contact')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.ReadOnlyModelMixin, models.Model),
        ),
    ]
