# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:41
from __future__ import unicode_literals

import core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompaniesHouseCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('archived_reason', models.TextField(null=True)),
                ('company_number', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('registered_address_1', models.CharField(max_length=255)),
                ('registered_address_2', models.CharField(blank=True, max_length=255)),
                ('registered_address_3', models.CharField(blank=True, max_length=255)),
                ('registered_address_4', models.CharField(blank=True, max_length=255)),
                ('registered_address_town', models.CharField(max_length=255)),
                ('registered_address_county', models.CharField(blank=True, max_length=255)),
                ('registered_address_postcode', models.CharField(blank=True, max_length=255)),
                ('company_category', models.CharField(blank=True, max_length=255)),
                ('company_status', models.CharField(blank=True, max_length=255)),
                ('sic_code_1', models.CharField(blank=True, max_length=255)),
                ('sic_code_2', models.CharField(blank=True, max_length=255)),
                ('sic_code_3', models.CharField(blank=True, max_length=255)),
                ('sic_code_4', models.CharField(blank=True, max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255)),
                ('incorporation_date', models.DateField(null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.DeferredSaveModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('archived_reason', models.TextField(null=True)),
                ('company_number', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('registered_address_1', models.CharField(max_length=255)),
                ('registered_address_2', models.CharField(blank=True, max_length=255)),
                ('registered_address_3', models.CharField(blank=True, max_length=255)),
                ('registered_address_4', models.CharField(blank=True, max_length=255)),
                ('registered_address_town', models.CharField(max_length=255)),
                ('registered_address_county', models.CharField(blank=True, max_length=255)),
                ('registered_address_postcode', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, help_text='Trading name', max_length=255)),
                ('description', models.TextField(null=True)),
                ('trading_address_1', models.CharField(blank=True, max_length=255)),
                ('trading_address_2', models.CharField(blank=True, max_length=255)),
                ('trading_address_3', models.CharField(blank=True, max_length=255)),
                ('trading_address_4', models.CharField(blank=True, max_length=255)),
                ('trading_address_town', models.CharField(blank=True, max_length=255)),
                ('trading_address_county', models.CharField(blank=True, max_length=255)),
                ('trading_address_postcode', models.CharField(blank=True, max_length=255)),
                ('account_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Advisor')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.BusinessType')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.DeferredSaveModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('archived_reason', models.TextField(null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('telephone_countrycode', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address_same_as_company', models.BooleanField(default=False)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('address_3', models.CharField(blank=True, max_length=255)),
                ('address_4', models.CharField(blank=True, max_length=255)),
                ('address_town', models.CharField(blank=True, max_length=255)),
                ('address_county', models.CharField(blank=True, max_length=255)),
                ('address_postcode', models.CharField(blank=True, max_length=255)),
                ('telephone_alternative', models.CharField(max_length=255, null=True)),
                ('email_alternative', models.EmailField(max_length=254, null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.DeferredSaveModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeRange',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('archived_reason', models.TextField(null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('subject', models.TextField(null=True)),
                ('date_of_interaction', models.DateTimeField(null=True)),
                ('notes', models.TextField(null=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Advisor')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Company')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='company.Contact')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.DeferredSaveModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoverRange',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UKRegion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.InteractionType'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.Company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Role'),
        ),
        migrations.AddField(
            model_name='contact',
            name='teams',
            field=models.ManyToManyField(to='company.Team'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Title'),
        ),
        migrations.AddField(
            model_name='contact',
            name='uk_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.UKRegion'),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.EmployeeRange'),
        ),
        migrations.AddField(
            model_name='company',
            name='export_to_countries',
            field=models.ManyToManyField(blank=True, related_name='company_export_to_countries', to='company.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='future_interest_countries',
            field=models.ManyToManyField(blank=True, related_name='company_future_interest_countries', to='company.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_company_related', related_query_name='company_companys', to='company.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='trading_address_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_trading_address_country', to='company.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='turnover_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.TurnoverRange'),
        ),
        migrations.AddField(
            model_name='companieshousecompany',
            name='registered_address_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_companieshousecompany_related', related_query_name='company_companieshousecompanys', to='company.Country'),
        ),
    ]
