# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companieshousecompany',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companieshousecompany',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companieshousecompany',
            name='archived_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companieshousecompany',
            name='archived_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='archived_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='archived_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_reason',
            field=models.TextField(null=True),
        ),
    ]
