# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uk_region',
            field=models.ForeignKey(default='8a4cd12a-6095-e211-a939-e4115bead28a', on_delete=django.db.models.deletion.CASCADE, to='company.UKRegion'),
            preserve_default=False,
        ),
    ]
