# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20161014_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companieshousecompany',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='companieshousecompany',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='companieshousecompany',
            name='archived_on',
        ),
        migrations.RemoveField(
            model_name='companieshousecompany',
            name='archived_reason',
        ),
    ]
