# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160929_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieshousecompany',
            name='archived_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='archived_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='archived_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='archived_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
