# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_uk_region'),
        ('company', '0003_auto_20161017_1446'),
    ]

    operations = [
    ]
