# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_merge_20161017_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='archived_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='archived_reason',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='archived_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='archived_reason',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='archived_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='archived_reason',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
