# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20161024_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='uk_region',
        ),
        migrations.AlterField(
            model_name='company',
            name='uk_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.UKRegion'),
        ),
    ]
