# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20161018_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='primary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
