# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_contact_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
