# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_auto_20161103_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advisor',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisor',
            name='archived_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
