# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_auto_20161103_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.EmailField(default='fake@no-email-address-supplied.com', max_length=254),
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
