# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_auto_20161103_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='archived_on',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='archived_reason',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.EmailField(default='fake@no-email-address-supplied.com', max_length=254),
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
