# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20161107_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
