# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20161019_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={},
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='name',
        ),
        migrations.AddField(
            model_name='advisor',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisor',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advisor',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
