# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20161019_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'ordering': ('name',),
            },
        ),
    ]
