# Generated by Django 4.2.15 on 2024-09-05 14:15

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0085_update_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0142_alter_company_address_country'),
        ('investment_lead', '0002_remove_investment_and_eyb_lead_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='EYBLead',
            fields=[
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('triage_hashed_uuid', models.CharField(max_length=256)),
                ('triage_created', models.DateTimeField()),
                ('triage_modified', models.DateTimeField()),
                ('sector_sub', models.CharField(blank=True, default='', max_length=256)),
                ('intent', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SET_UP_NEW_PREMISES', 'Set up new premises'), ('SET_UP_A_NEW_DISTRIBUTION_CENTRE', 'Set up a new distribution centre'), ('ONWARD_SALES_AND_EXPORTS_FROM_THE_UK', 'Onward sales and exports from the UK'), ('RESEARCH_DEVELOP_AND_COLLABORATE', 'Research, develop and collaborate'), ('FIND_PEOPLE_WITH_SPECIALIST_SKILLS', 'Find people with specialist skills'), ('OTHER', 'Other')], max_length=256), default=list, size=6)),
                ('intent_other', models.CharField(blank=True, default='', max_length=256)),
                ('location_city', models.CharField(blank=True, default='', max_length=256)),
                ('location_none', models.BooleanField(default=None, null=True)),
                ('hiring', models.CharField(choices=[('1-5', '1 to 5'), ('6-50', '6 to 50'), ('51-100', '51 to 100'), ('101+', 'More than 100'), ('NO_PLANS_TO_HIRE_YET', 'No plans to hire')], max_length=256)),
                ('spend', models.CharField(choices=[('0-9999', 'Less than £10,000'), ('10000-500000', '£10,000 to £500,000'), ('500000-1000000', '£500,000 to £1 million'), ('1000000-2000000', '£1 million to £2 million'), ('2000000-5000000', '£2 million to £5 million'), ('5000000-10000000', '£5 million to £10 million'), ('10000000+', 'More than £10 million')], max_length=256)),
                ('spend_other', models.CharField(blank=True, default='', max_length=256)),
                ('is_high_value', models.BooleanField(default=False)),
                ('user_hashed_uuid', models.CharField(max_length=256)),
                ('user_created', models.DateTimeField()),
                ('user_modified', models.DateTimeField()),
                ('company_name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('telephone_number', models.CharField(max_length=256)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_info_email', models.BooleanField(default=False)),
                ('landing_timeframe', models.CharField(blank=True, choices=[('UNDER_SIX_MONTHS', 'In the next 6 months'), ('SIX_TO_TWELVE_MONTHS', '6 to 12 months'), ('ONE_TO_TWO_YEARS', '1 to 2 years'), ('OVER_TWO_YEARS', "In more than 2 years' time")], default='', max_length=256)),
                ('company_website', models.CharField(blank=True, default='', max_length=256)),
                ('duns_number', models.CharField(blank=True, help_text='Dun & Bradstreet unique identifier. Nine-digit number with leading zeros.', max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')])),
                ('address_1', models.CharField(blank=True, max_length=256)),
                ('address_2', models.CharField(blank=True, max_length=256)),
                ('address_town', models.CharField(blank=True, max_length=256)),
                ('address_county', models.CharField(blank=True, max_length=256)),
                ('address_postcode', models.CharField(blank=True, max_length=256)),
                ('address_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.administrativearea')),
                ('address_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.country')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='Company associated with this EYB lead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eyb_leads', to='company.company')),
                ('company_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.country')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.ukregion')),
                ('sector', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
