# Generated by Django 4.2.15 on 2024-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_lead', '0003_redefine_initial_eyb_lead_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyblead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='eyblead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='eyblead',
            name='utm_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='eyblead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
