# Generated by Django 4.2.16 on 2024-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0023_remove_investmentproject_specific_programme_and_more'),
        ('investment_lead', '0004_eyblead_utm_content_eyblead_utm_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyblead',
            name='investment_projects',
            field=models.ManyToManyField(blank=True, help_text='Investment Projects associated with this EYB lead.', null=True, related_name='eyb_leads', to='investment.investmentproject'),
        ),
    ]
