# Generated by Django 4.2.16 on 2024-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_lead', '0005_remove_eyblead_address_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyblead',
            name='address_county',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
