# Generated by Django 4.2.16 on 2024-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_lead', '0005_eyblead_investment_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyblead',
            name='address_area',
        ),
        migrations.RemoveField(
            model_name='eyblead',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='eyblead',
            name='sector_sub',
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='address_1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='address_county',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='address_postcode',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='address_town',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='agree_info_email',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='agree_terms',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='email',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='hiring',
            field=models.CharField(blank=True, choices=[('1-5', '1 to 5'), ('6-50', '6 to 50'), ('51-100', '51 to 100'), ('101+', 'More than 100'), ('NO_PLANS_TO_HIRE_YET', 'No plans to hire')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='is_high_value',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='location_none',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='role',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='spend',
            field=models.CharField(blank=True, choices=[('0-9999', 'Less than £10,000'), ('10000-500000', '£10,000 to £500,000'), ('500000-1000000', '£500,000 to £1 million'), ('1000000-2000000', '£1 million to £2 million'), ('2000000-5000000', '£2 million to £5 million'), ('5000000-10000000', '£5 million to £10 million'), ('10000000+', 'More than £10 million')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='telephone_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='triage_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='triage_hashed_uuid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='triage_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='user_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='user_hashed_uuid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='user_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='utm_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
