# Generated by Django 4.2.16 on 2024-11-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_lead', '0008_add_marketing_hashed_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyblead',
            name='marketing_hashed_uuid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
