# Generated by Django 4.2.16 on 2024-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_lead', '0009_alter_eyblead_marketing_hashed_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyblead',
            name='hiring',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
