# Generated by Django 4.2.16 on 2024-12-11 21:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_lead', '0010_alter_eyblead_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyblead',
            name='intent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=6),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='landing_timeframe',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eyblead',
            name='spend',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
