# Generated by Django 2.0.7 on 2018-08-08 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_bucket_id_status_av_reason_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionDocument',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proposition.Proposition')),
            ],
            options={
                'verbose_name': 'investment project proposition document',
                'permissions': (('read_all_propositiondocument', 'Can read all proposition document'), ('read_associated_propositiondocument', 'Can read proposition document for associated investment projects'), ('add_associated_investmentproject_propositiondocument', 'Can add proposition document for associated investment projects'), ('change_associated_investmentproject_propositiondocument', 'Can change proposition document for associated investment projects'), ('deleted_associated_investmentproject_propositiondocument', 'Can delete proposition document for associated investment projects')),
                'default_permissions': ('add_all', 'change_all', 'delete'),
            },
        ),
    ]
