# Generated by Django 2.0.8 on 2018-08-31 09:23

from django.db import migrations


def rename_permissions(apps, schema_editor):
    """
    This fixes the typo in delete_associated_propositiondocument and renames delete_propositiondocument to
    delete_all_propositiondocument so it is consistent with corresponding permission of evidencedocument.
    It also removed _investmentproject_ from proposition permissions to make it consistent.
    """
    permission_model = apps.get_model('auth', 'Permission')

    old_new_codename = (
        ('deleted_associated_propositiondocument', 'delete_associated_propositiondocument'),
        ('delete_propositiondocument', 'delete_all_propositiondocument'),
        ('view_associated_investmentproject_proposition', 'view_associated_proposition'),
        ('change_associated_investmentproject_proposition', 'change_associated_proposition'),
        ('add_associated_investmentproject_proposition', 'add_associated_proposition'),
    )

    for old_codename, new_codename in old_new_codename:
        permission_model.objects.filter(
            codename=old_codename
        ).update(
            codename=new_codename
        )


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0005_change_proposition_details'),
    ]

    operations = [
        migrations.RunPython(rename_permissions, elidable=True),
    ]
