# Generated by Django 2.1 on 2018-09-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0006_rename_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposition',
            options={'default_permissions': ('add_all', 'change_all', 'delete_all', 'view_all'), 'permissions': (('view_associated_proposition', 'Can view proposition for associated investment projects'), ('add_associated_proposition', 'Can add proposition for associated investment projects'), ('change_associated_proposition', 'Can change proposition for associated investment projects'))},
        ),
        migrations.AlterModelOptions(
            name='propositiondocument',
            options={'default_permissions': ('add_all', 'change_all', 'delete_all', 'view_all'), 'permissions': (('add_associated_propositiondocument', 'Can add proposition document for associated investment projects'), ('change_associated_propositiondocument', 'Can change proposition document for associated investment projects'), ('delete_associated_propositiondocument', 'Can delete proposition document for associated investment projects'), ('view_associated_propositiondocument', 'Can view proposition document for associated investment projects')), 'verbose_name': 'investment project proposition document'},
        ),
    ]
