# Generated by Django 2.1.3 on 2018-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_bucket_id_status_av_reason_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='av_clean',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
