# Generated by Django 4.2.19 on 2025-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_sharepointdocument_genericdocument'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genericdocument',
            name='documents_g_documen_7d45ae_idx',
        ),
        migrations.RenameField(
            model_name='genericdocument',
            old_name='document_content_type',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='genericdocument',
            old_name='related_object_content_type',
            new_name='related_object_type',
        ),
        migrations.AddIndex(
            model_name='genericdocument',
            index=models.Index(fields=['document_type', 'document_object_id', 'related_object_type', 'related_object_id'], name='documents_g_documen_2aba68_idx'),
        ),
    ]
