# Generated by Django 4.2.19 on 2025-03-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0006_sharepointdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericDocument',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('document_object_id', models.UUIDField()),
                ('related_object_id', models.UUIDField()),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contenttypes.contenttype')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['document_type', 'document_object_id', 'related_object_type', 'related_object_id'], name='documents_g_documen_2aba68_idx')],
            },
        ),
    ]
