# Generated by Django 4.2.20 on 2025-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_uploadabledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='use_default_credentials',
            field=models.BooleanField(default=False, help_text='Indicates whether default credentials should be used when accessing bucket'),
        ),
    ]
