# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_squashed_0030_cancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Autogenerated by the system.', max_length=100)),
                ('transaction_reference', models.CharField(blank=True, help_text='As it appears on the transaction receipt.', max_length=255)),
                ('additional_reference', models.CharField(blank=True, help_text='Legacy field.', max_length=255)),
                ('amount', models.PositiveIntegerField(help_text='Amount paid in pence.')),
                ('method', models.CharField(choices=[('card', 'Card'), ('bacs', 'BACS'), ('cheque', 'Cheque'), ('manual', 'Manual')], default='bacs', max_length=100)),
                ('payment_received_on', models.DateTimeField()),
                ('cardholder_name', models.CharField(blank=True, max_length=255)),
                ('card_brand', models.CharField(blank=True, max_length=100)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=100)),
                ('billing_fax', models.CharField(blank=True, max_length=100)),
                ('billing_address_1', models.CharField(blank=True, max_length=255)),
                ('billing_address_2', models.CharField(blank=True, max_length=255)),
                ('billing_address_town', models.CharField(blank=True, max_length=255)),
                ('billing_address_county', models.CharField(blank=True, max_length=255)),
                ('billing_address_postcode', models.CharField(blank=True, max_length=100)),
                ('billing_address_country', models.CharField(blank=True, max_length=255)),
                ('cheque_number', models.CharField(blank=True, max_length=255)),
                ('giro_slip_number', models.CharField(blank=True, max_length=255)),
                ('sort_code', models.CharField(blank=True, max_length=100)),
                ('cheque_banked_on', models.DateTimeField(blank=True, null=True)),
                ('cheque_paid_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.Order')),
            ],
            options={
                'abstract': False,
                'ordering': ('created_on',)
            },
        ),
    ]
