# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis-payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_received_on',
            new_name='received_on',
        ),
    ]
