# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_squashed_0030_cancellation'),
        ('omis-payment', '0003_auto_20171019_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved and Paid'), ('rejected', 'Rejected')], max_length=100)),
                ('requested_on', models.DateTimeField()),
                ('refund_reason', models.TextField(blank=True)),
                ('requested_amount', models.PositiveIntegerField()),
                ('level1_approved_on', models.DateTimeField(blank=True, null=True)),
                ('level1_approval_notes', models.TextField(blank=True)),
                ('level2_approved_on', models.DateTimeField(blank=True, null=True)),
                ('level2_approval_notes', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, choices=[('card', 'Card'), ('bacs', 'BACS'), ('cheque', 'Cheque'), ('manual', 'Manual')], max_length=100, null=True)),
                ('net_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('vat_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('additional_reference', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level1_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level2_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='order.Order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='omis-payment.Payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
    ]
