# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis-payment', '0003_auto_20171019_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('created_on',), 'permissions': (('read_payment', 'Can read payment'),)},
        ),
    ]
