# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis-payment', '0004_refund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('created_on',), 'permissions': (('read_payment', 'Can read payment'),)},
        ),
    ]
