# Generated by Django 2.0.2 on 2018-02-19 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_populate_uk_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omis-payment', '0005_adding_read_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySession',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('submitted', 'Submitted'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='created', max_length=100)),
                ('govuk_payment_id', models.CharField(verbose_name='GOV.UK payment ID', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway_sessions', to='order.Order')),
            ],
            options={
                'ordering': ('-created_on',),
                'permissions': (('read_paymentgatewaysession', 'Can read payment gateway session'),),
            },
        ),
    ]
