# Generated by Django 2.0.3 on 2018-04-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omis-payment', '0006_paymentgatewaysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='net_amount',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='In pence. E.g. £10 should be 1000.',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='refund',
            name='requested_amount',
            field=models.PositiveIntegerField(
                help_text='In pence. E.g. £10 should be 1000.'
            ),
        ),
        migrations.AlterField(
            model_name='refund',
            name='total_amount',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='In pence. E.g. £10 should be 1000.',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='refund',
            name='vat_amount',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='In pence. E.g. £10 should be 1000.',
                null=True
            ),
        ),
    ]
