# Generated by Django 2.0.8 on 2018-08-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis-payment', '0007_update_refund_amount_fields'),
        ('core', '0003_rename_read_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewaysession',
            options={'ordering': ('-created_on',)},
        ),
    ]
