# Generated by Django 3.2.6 on 2021-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis_payment', '0008_update_permissions_django_21'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='omis-payment_payment',
        ),
        migrations.AlterModelTable(
            name='paymentgatewaysession',
            table='omis-payment_paymentgatewaysession',
        ),
        migrations.AlterModelTable(
            name='refund',
            table='omis-payment_refund',
        ),
    ]
