# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from oauth2_provider.settings import oauth2_settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(oauth2_settings.APPLICATION_MODEL),
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplicationScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Allowed scopes for this application. (Comma separated in Django admin.)', size=None)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=oauth2_settings.APPLICATION_MODEL)),
            ],
            options={
                'verbose_name': 'oauth application scope',
            },
        ),
    ]
