# Generated by Django 3.0.5 on 2020-05-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_add_data_hub_to_scopes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthApplicationScope',
        ),
    ]
