# Generated by Django 4.2.16 on 2024-11-21 17:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DateTime the instance was created')),
                ('object_key', models.CharField(help_text='The S3 object path', max_length=255)),
                ('object_created', models.DateTimeField(default=django.utils.timezone.now, help_text='DateTime the ingested object was last modified in S3')),
            ],
        ),
    ]
