from .common import *


INSTALLED_APPS += ('behave',)


API_CLIENT_SECRET = env('API_CLIENT_SECRET')
API_CLIENT_ID = env('API_CLIENT_ID')
APPLICATION_NAME = env('APPLICATION_NAME', default='Behave test suite')
CDMS_USERNAME = env('CDMS_USERNAME')
CDMS_PASSWORD = env('CDMS_PASSWORD')
TEST_USERNAME = env('TEST_USERNAME')
TEST_USER_PASSWORD = env('TEST_USER_PASSWORD')
