# Generated by Django 3.2.20 on 2023-09-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_investmentprojecttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprojecttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_investmentprojecttask', to='task.task'),
        ),
    ]
