# Generated by Django 3.2.20 on 2023-09-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_update_specific_programmes'),
        ('task', '0003_alter_investmentprojecttask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprojecttask',
            name='investment_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_project_task', to='investment.investmentproject'),
        ),
        migrations.AlterField(
            model_name='investmentprojecttask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_investmentprojecttask', to='task.task'),
        ),
    ]
