# Generated by Django 3.2.20 on 2023-10-13 13:46
from datetime import timedelta

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Task = apps.get_model("task", "Task")

    tasks_needing_reminder_date = Task.objects.filter(
        reminder_days__isnull=False, due_date__isnull=False
    )
    for task in tasks_needing_reminder_date:
        task.reminder_date = task.due_date - timedelta(days=task.reminder_days)
        task.save()


def reverse_func(apps, schema_editor):
    print("This migration removes the reminder_date column, so no data rollback is required")


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0004_auto_20230927_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
