# Generated by Django 3.2.21 on 2023-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20230927_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
