# Generated by Django 3.2.23 on 2023-11-20 13:15

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    InvestmentProjectTask = apps.get_model("task", "InvestmentProjectTask")
    if InvestmentProjectTask is not None:
        investment_project_tasks = InvestmentProjectTask.objects.all()
        for investment_project_task in investment_project_tasks:
            investment_project_task.task.investment_project = (
                investment_project_task.investment_project
            )
            investment_project_task.task.save()


def reverse_func(apps, schema_editor):
    print("This migration removes the investment_project column, so no data rollback is required")


class Migration(migrations.Migration):
    dependencies = [
        ('investment', '0013_update_specific_programmes'),
        ('task', '0005_task_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='investment_project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_investment_project',
                to='investment.investmentproject',
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
