# Generated by Django 3.2.23 on 2023-11-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('investment', '0013_update_specific_programmes'),
        ('task', '0005_task_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='investment_project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_investment_project',
                to='investment.investmentproject',
            ),
        ),
    ]
