# Generated by Django 3.2.23 on 2023-11-29 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0006_task_investment_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentProjectTask',
        ),
    ]
