# Generated by Django 3.2.23 on 2024-01-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0081_auto_20230130_1124'),
        ('task', '0008_task_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_interaction', to='interaction.interaction'),
        ),
    ]
