# Generated by Django 3.2.20 on 2024-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('complete', 'Complete')], default='active', max_length=255),
        ),
    ]
