# Generated by Django 3.2.20 on 2023-10-13 13:46
from datetime import timedelta

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Task = apps.get_model("task", "Task")

    tasks = Task.objects.all()
    for task in tasks:
        task.status = 'complete' if task.archived else 'active'
        task.archived_by = None
        task.archived = False
        task.save()


def reverse_func(apps, schema_editor):
    '''Archived_by will not be recovered'''

    Task = apps.get_model("task", "Task")

    tasks = Task.objects.all()
    for task in tasks:
        task.archived = True if task.status == 'complete' else False
    print("This migration updates status to archived state from status state and archived_by will not be restored")


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0010_task_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
