# Generated by Django 3.2.20 on 2023-10-13 13:46
from django.db import migrations
from datahub.search.tasks import schedule_model_sync
from datahub.task.models import Task

def forwards_func(apps, schema_editor):
    tasks = apps.get_model("task", "Task").objects.all()
    for task in tasks:
        task.status = Task.Status.COMPLETE if task.archived else Task.Status.ACTIVE
        task.archived = False
        task.save()
    schedule_model_sync(('task',))


def reverse_func(apps, schema_editor):
    tasks = apps.get_model("task", "Task").objects.all()
    for task in tasks:
        task.archived = True if (task.status == Task.Status.COMPLETE) else False
        task.save()
    schedule_model_sync(('task',))


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0010_task_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
