# Generated by Django 4.2.15 on 2024-09-25 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0011_archive_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='advisers',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
