EVERY_MINUTE = '* * * * *'
EVERY_TEN_MINUTES = '*/10 * * * *'

EVERY_HOUR = '0 * * * *'

EVERY_ONE_AM = '0 1 * * *'
EVERY_EIGHT_AM = '0 8 * * *'
EVERY_TEN_AM = '0 10 * * *'
EVERY_MIDNIGHT = '0 0 * * *'
EVERY_SEVEN_PM = '0 19 * * *'

EVERY_EIGHT_PM_ON_SATURDAY = '0 20 * * SAT'
EVERY_NINE_PM_ON_SATURDAY = '0 21 * * SAT'

EVERY_THREE_AM_ON_TWENTY_THIRD_EACH_MONTH = '0 3 23 * *'
EVERY_EIGHT_THIRTY_AM_ON_FIRST_EACH_MONTH = '30 8 1 * *'
EVERY_NINE_THIRTY_AM_ON_FIRST_SECOND_THIRD_FOURTH_OF_EACH_MONTH = '30 9 1-4 * *'

THREE_MINUTES_IN_SECONDS = 60 * 3
FIFTEEN_MINUTES_IN_SECONDS = 60 * 15
THIRTY_MINUTES_IN_SECONDS = 60 * 30
ONE_HOUR_IN_SECONDS = 60 * 60
HALF_DAY_IN_SECONDS = 12 * ONE_HOUR_IN_SECONDS
