EVERY_TEN_MINUTES = '*/10 * * * *'
EVERY_MINUTE = '* * * * *'
EVERY_HOUR = '0 * * * *'

THREE_MINUTES_IN_SECONDS = 60 * 3
THIRTY_MINUTES_IN_SECONDS = 60 * 30
ONE_DAY_IN_SECONDS = 60 * 60
ONE_DAY_IN_SECONDS = 24 * ONE_DAY_IN_SECONDS
