EVERY_TEN_MINUTES = '*/10 * * * *'
EVERY_MINUTE = '* * * * *'
EVERY_HOUR = '0 * * * *'
EVERY_ONE_AM = '0 1 * * *'

THREE_MINUTES_IN_SECONDS = 60 * 3
THIRTY_MINUTES_IN_SECONDS = 60 * 30
ONE_HOUR_IN_SECONDS = 60 * 60
ONE_DAY_IN_SECONDS = 24 * ONE_HOUR_IN_SECONDS
