# Generated by Django 3.2.6 on 2021-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omis_region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ukregionalsettings',
            table='omis-region_ukregionalsettings',
        ),
    ]
