# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('metadata', '0001_initial'),]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},),
    ]
