# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0012_auto_20170523_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentProjectPhase',
            new_name='InvestmentProjectStage',
        ),
    ]
