# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_rename_phase_to_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDIValue',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
