# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20161130_0507'),
        ('metadata', '0002_auto_20161129_0528'),
    ]

    operations = [
    ]
