# Generated by Django 2.0.3 on 2018-04-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_remove_sector_name_from_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={},
        ),
    ]
