# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_add_fdi_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='metadata.Country'),
        ),
        migrations.AddField(
            model_name='team',
            name='uk_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='metadata.UKRegion'),
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='metadata.TeamRole'),
        ),
    ]
