# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_team_roles_regions_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='country',
            name='omis_disabled_on',
            field=models.DateTimeField(blank=True, help_text='Empty means enabled for OMIS.', null=True),
        ),
    ]
