# Generated by Django 2.0.3 on 2018-04-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_remove_sector_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headquartertype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='headquartertype',
            name='order',
            field=models.FloatField(default=0.0),
        ),
    ]
