# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20171002_0950'),
    ]

    state_operations = [
    ]

    operations = [
    ]
