# Generated by Django 3.1.7 on 2021-02-25 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid

from datahub.core.migration_utils import load_yaml_data_in_migration
from pathlib import PurePath


def load_services(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0007_initial_us_states.yaml'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_update_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryState',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('state_code', models.CharField(max_length=2)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_states', to='metadata.country')),
            ],
            options={
                'verbose_name_plural': 'country states',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.RunPython(load_services, migrations.RunPython.noop),
    ]
