# Generated by Django 3.1.7 on 2021-03-05 13:17
from pathlib import PurePath

from django.db import migrations, models

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_services(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0007_administrativearea_area_code.yaml'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0006_update_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='area_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.RunPython(load_services, migrations.RunPython.noop),
    ]
