# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_remove_interaction_type'),
    ]

    operations = [
    ]
