# Generated by Django 2.0.4 on 2018-04-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_add_service_contexts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
