# Generated by Django 2.0.3 on 2018-03-27 12:23
from pathlib import PurePath

from django.core.management import call_command
from django.db import migrations
from django.db.migrations import RunPython


def load_service(apps, schema_editor):
    call_command(
        'loaddata',
        PurePath(__file__).parent / '0008_add_policy_feedback_service.yaml'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_remove_role'),
    ]

    operations = [
        RunPython(load_service)
    ]
