# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_companyclassification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerange',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='turnoverrange',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='employeerange',
            name='order',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='turnoverrange',
            name='order',
            field=models.FloatField(default=0.0),
        ),
    ]
