# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_remove_service_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
