# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_adding_read_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonFDIType',
        ),
    ]
