# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20170502_1258'),
        ('metadata', '0009_fditype_investmentbusinessactivity_investmentprojectphase_investmentstrategicdriver_investmenttype_n'),
    ]

    operations = [
    ]
