# Generated by Django 2.0.6 on 2018-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_investment_spi_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyclassification',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='companyclassification',
            name='order',
            field=models.FloatField(default=0.0),
        ),
    ]
