# Generated by Django 2.0.5 on 2018-06-11 11:51

import datahub.core.fields
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20180613_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tags',
            field=datahub.core.fields.MultipleChoiceField(choices=(('investment_services_team', 'Investment Services Team'),), default=[], max_length=255, blank=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='team',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='metadata_te_tags_39ea7c_gin'),
        ),
    ]
