# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_merge_20170502_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentbusinessactivity',
            options={'ordering': ('name',), 'verbose_name_plural': 'investment business activities'},
        ),
        migrations.AlterModelOptions(
            name='referralsourceactivity',
            options={'ordering': ('name',), 'verbose_name_plural': 'referral source activities'},
        ),
        migrations.AlterModelOptions(
            name='servicedeliverystatus',
            options={'ordering': ('name',), 'verbose_name_plural': 'service delivery statuses'},
        ),
    ]
