# Generated by Django 3.1.8 on 2021-05-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_update_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='area_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
