# Generated by Django 2.0.6 on 2018-06-29 12:31
from pathlib import PurePath

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_investment_spi_service_aftercare_offered'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasRegion',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='overseas_region',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='countries', to='metadata.OverseasRegion'),
        ),
    ]
