# Generated by Django 2.1.2 on 2018-10-30 17:24
from pathlib import PurePath

from django.core.management import call_command
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_investmentprojectstage_exclude_from_investment_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_alpha2_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
