# Generated by Django 2.1.2 on 2018-11-02 11:25

from django.db import migrations, models


def _update_exclude_from_investment_flow_property(apps, exclude_from_investment_flow):
    investment_stage_model = apps.get_model('metadata', 'InvestmentProjectStage')
    try:
        assign_pm = investment_stage_model.objects.get(pk='c9864359-fb1a-4646-a4c1-97d10189fc03')
    except investment_stage_model.DoesNotExist:
        pass
    else:
        assign_pm.exclude_from_investment_flow = exclude_from_investment_flow
        assign_pm.save()


def exclude_assign_pm_from_investment_flow(apps, schema_editor):
    _update_exclude_from_investment_flow_property(apps, True)


def include_assign_pm_from_investment_flow(apps, schema_editor):
    _update_exclude_from_investment_flow_property(apps, False)


class Migration(migrations.Migration):


    dependencies = [
        ('metadata', '0015_add_iso_to_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprojectstage',
            name='exclude_from_investment_flow',
            field=models.BooleanField(
                default=False,
                help_text='If set to True the stage will not be part of the linear flow and will be skipped.'
            ),
        ),
        migrations.RunPython(
            exclude_assign_pm_from_investment_flow, include_assign_pm_from_investment_flow
        ),
    ]
