# Generated by Django 2.1.3 on 2018-11-13 16:50
from pathlib import PurePath

from django.db import migrations
from datahub.core.migration_utils import load_yaml_data_in_migration


def load_countries_with_iso_data(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0017_countries_with_iso_data.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_investmentprojectstage_exclude_from_investment_not_null'),
    ]

    operations = [
        migrations.RunPython(load_countries_with_iso_data, migrations.RunPython.noop),
    ]
