# Generated by Django 2.1.3 on 2018-12-18 21:26

import uuid
from pathlib import PurePath

import django.db.models.deletion
from django.db import migrations, models

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_sector_clusters(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0018_add_sector_cluster_to_sector.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_countries_with_iso_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorCluster',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='metadata.SectorCluster'),
        ),
        migrations.RunPython(load_sector_clusters, migrations.RunPython.noop),
    ]
