# Generated by Django 3.1.12 on 2021-10-28 10:58

from django.db import migrations, models

from pathlib import PurePath

from datahub.core.migration_utils import load_yaml_data_in_migration

import uuid

def load_exchange_rate(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0018_add_usd_exchange_rate.yaml'
    )

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('metadata', '0017_update_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('exchange_rate', models.FloatField(blank=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.RunPython(load_exchange_rate, migrations.RunPython.noop),
    ]
