# Generated by Django 3.1.12 on 2021-10-29 11:56

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datahub.core.migration_utils import load_yaml_data_in_migration
from pathlib import PurePath


def load_exchange_rate(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0019_add_gbp_exchange_rate.yaml'
    )

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0018_add_usd_exchange_rate'),
    ]

    operations = [
        migrations.RunPython(load_exchange_rate, migrations.RunPython.noop),
    ]
