# Generated by Django 2.1.5 on 2019-01-11 17:06

import datahub.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_remove_companyclassification_from_django'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='contexts',
            field=datahub.core.fields.MultipleChoiceField(blank=True, choices=(('event', 'Event'), ('export_interaction', 'Export interaction'), ('export_service_delivery', 'Export service delivery'), ('investment_interaction', 'Investment interaction'), ('investment_project_interaction', 'Investment project interaction'), ('other_interaction', 'Other interaction'), ('other_service_delivery', 'Other service delivery'), ('interaction', 'Interaction (deprecated)'), ('service_delivery', 'Service delivery (deprecated)')), max_length=255),
        ),
    ]
