# Generated by Django 2.1.5 on 2019-01-11 17:06

import datahub.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_remove_companyclassification_from_django'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='contexts',
            field=datahub.core.fields.MultipleChoiceField(blank=True, choices=(('event', 'Event'), ('interaction', 'Interaction'), ('investment_project_interaction', 'Investment project interaction'), ('service_delivery', 'Service delivery')), max_length=255),
        ),
    ]
