# Generated by Django 2.1.5 on 2019-01-15 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_remove_policy_feedback_context'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CompanyClassification',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                        ('name', models.TextField(blank=True)),
                        ('disabled_on', models.DateTimeField(blank=True, null=True)),
                        ('order', models.FloatField(default=0.0)),
                    ],
                    options={
                        'abstract': False,
                        'ordering': ('order',),
                    },
                ),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyClassification',
        ),
    ]
