# Generated by Django 2.1.7 on 2019-02-15 14:30
from pathlib import PurePath

from django.db import migrations, models
import django.db.models.deletion
import uuid

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_administrative_areas(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0022_add_administrative_area.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0021_delete_companyclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeArea',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_areas', to='metadata.Country')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.RunPython(load_administrative_areas, migrations.RunPython.noop),
    ]
