# Generated by Django 2.1.5 on 2019-02-26 14:13
from pathlib import PurePath

from django.db import migrations
import django.db.models.deletion
import uuid

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_administrative_areas(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0023_add_chinese_regions.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0022_add_administrative_area'),
    ]

    operations = [
        migrations.RunPython(load_administrative_areas, migrations.RunPython.noop),
    ]
