# Generated by Django 2.1.7 on 2019-04-30 17:12
from pathlib import PurePath

from django.db import migrations
import django.db.models.deletion
import uuid

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_administrative_areas(apps, schema_editor):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0027_add_administrative_areas.yaml',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0026_add_index_upper_team_name'),
    ]

    operations = [
        migrations.RunPython(load_administrative_areas, migrations.RunPython.noop),
    ]
