# Generated by Django 2.2.2 on 2019-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0027_add_administrative_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_service_answers_flow_feature_flag',
            field=models.BooleanField(
                default=False,
                help_text='Temporary field that designates that this service should be hidden '
                          "unless the 'interaction_service_answers_flow' feature flag is active."
            ),
        ),
    ]
