# Generated by Django 3.2.13 on 2022-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0029_update_trade_agreements'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('from_currency_code', 'to_currency_code'), name='unique_from_currency_code_to_currency_code'),
        ),
    ]
