# Generated by Django 3.2.16 on 2023-01-26 10:03

from django.db import migrations, models
from pathlib import PurePath
import uuid

from datahub.core.migration_utils import load_yaml_data_in_migration

def load_export_barriers(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0039_add_export_barrier_type.yaml'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0037_update_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBarrierType',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.RunPython(load_export_barriers, migrations.RunPython.noop),
    ]
