# Generated by Django 2.2.4 on 2019-08-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0037_add_service_hierarchy'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='service',
                    name='name',
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RemoveField('service', 'name'),
    ]
