# Generated by Django 3.2.18 on 2023-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0044_update_countries_and_iso_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_alpha2_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
