# Generated by Django 4.2.10 on 2024-03-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0075_update_trade_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='metadata.sectorcluster'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='metadata.country'),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='metadata.teamrole'),
        ),
        migrations.AlterField(
            model_name='team',
            name='uk_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='metadata.ukregion'),
        ),
    ]
