# Generated by Django 4.2.10 on 2024-03-19 23:38
from pathlib import PurePath

from django.db import migrations, models

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_country_is_export_win(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0077_country_is_export_win.yaml'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0076_update_trade_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_export_win',
            field=models.BooleanField(default=True),
        ),
         migrations.RunPython(load_country_is_export_win, migrations.RunPython.noop),
    ]
