# Generated by Django 4.2.10 on 2024-03-19 23:38
from pathlib import PurePath

from django.db import migrations, models

from datahub.core.migration_utils import load_yaml_data_in_migration


def load_countries(apps, _):
    load_yaml_data_in_migration(
        apps,
        PurePath(__file__).parent / '0088_add_countries.yaml'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0087_update_services'),
    ]

    operations = [
         migrations.RunPython(load_countries, migrations.RunPython.noop),
    ]
