# Generated by Django 4.2.19 on 2025-03-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0089_add_stova_serivce"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostcodeData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("postcode", models.CharField(max_length=255, unique=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="metadata.ukregion",
                    ),
                ),
            ],
        ),
    ]
