# Generated by Django 4.2.17 on 2025-02-18 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0089_add_stova_serivce'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeData',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('hashed_uuid', models.CharField(blank=True, default='', max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('publication_date', models.DateTimeField()),
                ('postcode_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metadata.ukregion')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
