# Generated by Django 4.2.19 on 2025-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0089_add_stova_serivce"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostcodeData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("ccg", models.CharField(blank=True, max_length=255, null=True)),
                ("ced", models.CharField(blank=True, max_length=255, null=True)),
                ("eer", models.CharField(blank=True, max_length=255, null=True)),
                ("imd", models.IntegerField(null=True)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pcd", models.CharField(blank=True, max_length=255, null=True)),
                ("pct", models.CharField(blank=True, max_length=255, null=True)),
                ("pfa", models.CharField(blank=True, max_length=255, null=True)),
                ("rgn", models.CharField(blank=True, max_length=255, null=True)),
                ("stp", models.CharField(blank=True, max_length=255, null=True)),
                ("ctry", models.CharField(blank=True, max_length=255, null=True)),
                ("lep1", models.CharField(blank=True, max_length=255, null=True)),
                ("lep2", models.CharField(blank=True, max_length=255, null=True)),
                ("long", models.DecimalField(decimal_places=6, max_digits=9)),
                ("nuts", models.CharField(blank=True, max_length=255, null=True)),
                ("oa01", models.CharField(blank=True, max_length=255, null=True)),
                ("oa11", models.CharField(blank=True, max_length=255, null=True)),
                ("park", models.CharField(blank=True, max_length=255, null=True)),
                ("pcd2", models.CharField(blank=True, max_length=255, null=True)),
                ("pcds", models.CharField(blank=True, max_length=255, null=True)),
                ("pcon", models.CharField(blank=True, max_length=255, null=True)),
                ("ttwa", models.CharField(blank=True, max_length=255, null=True)),
                ("wz11", models.CharField(blank=True, max_length=255, null=True)),
                ("bua11", models.CharField(blank=True, max_length=255, null=True)),
                ("nhser", models.CharField(blank=True, max_length=255, null=True)),
                ("oac01", models.CharField(blank=True, max_length=255, null=True)),
                ("oac11", models.CharField(blank=True, max_length=255, null=True)),
                ("oscty", models.CharField(blank=True, max_length=255, null=True)),
                ("streg", models.IntegerField(null=True)),
                ("calncv", models.CharField(blank=True, max_length=255, null=True)),
                ("dointr", models.DateTimeField(blank=True, null=True)),
                ("doterm", models.DateTimeField(blank=True, null=True)),
                ("lsoa01", models.CharField(blank=True, max_length=255, null=True)),
                ("lsoa11", models.CharField(blank=True, max_length=255, null=True)),
                ("msoa01", models.CharField(blank=True, max_length=255, null=True)),
                ("msoa11", models.CharField(blank=True, max_length=255, null=True)),
                ("oslaua", models.CharField(blank=True, max_length=255, null=True)),
                ("osward", models.CharField(blank=True, max_length=255, null=True)),
                ("parish", models.CharField(blank=True, max_length=255, null=True)),
                ("teclec", models.CharField(blank=True, max_length=255, null=True)),
                ("buasd11", models.CharField(blank=True, max_length=255, null=True)),
                ("casward", models.CharField(blank=True, max_length=255, null=True)),
                ("ru11ind", models.CharField(blank=True, max_length=255, null=True)),
                ("ur01ind", models.CharField(blank=True, max_length=255, null=True)),
                ("oseast1m", models.CharField(blank=True, max_length=255, null=True)),
                ("osgrdind", models.CharField(blank=True, max_length=255, null=True)),
                ("oshlthau", models.CharField(blank=True, max_length=255, null=True)),
                ("osnrth1m", models.CharField(blank=True, max_length=255, null=True)),
                ("usertype", models.IntegerField(null=True)),
                ("statsward", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pcd_normalised",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uk_super_region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "local_authority_district_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parliamentary_constituency_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lep1_local_enterprise_partnership_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lep2_local_enterprise_partnership_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
