# Generated by Django 4.2.20 on 2025-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0091_update_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcodedata',
            name='lsoa21',
            field=models.CharField(blank=True, help_text='2021 Census Lower Layer Super Output Area', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postcodedata',
            name='msoa21',
            field=models.CharField(blank=True, help_text='2021 Census Middle Layer Super Output Area', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postcodedata',
            name='oa21',
            field=models.CharField(blank=True, help_text='2021 Census Output Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcodedata',
            name='lsoa01',
            field=models.CharField(blank=True, help_text='2001 Census Lower Layer Super Output Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcodedata',
            name='lsoa11',
            field=models.CharField(blank=True, help_text='2011 Census Lower Layer Super Output Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcodedata',
            name='msoa01',
            field=models.CharField(blank=True, help_text='2001 Census Middle Layer Super Output Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcodedata',
            name='msoa11',
            field=models.CharField(blank=True, help_text='2011 Census Middle Layer Super Output Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcodedata',
            name='oa01',
            field=models.CharField(blank=True, help_text='2001 Census Output Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcodedata',
            name='oa11',
            field=models.CharField(blank=True, help_text='2011 Census Output Area/Small Area', max_length=255, null=True),
        ),
    ]
